//  Copyright 2013-2021 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.patientportal2.pojo;

import com.medfusion.common.utils.IHGUtil;
import com.medfusion.common.utils.PropertyFileLoader;
import com.medfusion.pojos.Patient;
import com.medfusion.product.patientportal2.utils.PortalUtil2;

public class JalapenoPatient {

		private String email = "";
		private String username = "";
		private String password = "";
		private String url = "";
		private String firstName = "";
		private String lastName = "";

		private Patient.GenderExtended gender;

		private String DOBDay;
		private String DOBMonth;
		private String DOBMonthText;
		private String DOBYear;

		private String ZipCode;
		private String address1;
		private String address2;
		private String city;
		private String state;

		/**
		 * Verifies autogenerated username uniqueness through credentialMatcher, max 10 attempts
		 *
		 * @param testData
		 * @throws NullPointerException
		 * @throws Exception
		 */
		public JalapenoPatient(PropertyFileLoader testData) throws NullPointerException, Exception {
				IHGUtil.PrintMethodName();

				username = PortalUtil2.generateUniqueUsername(testData.getUserId(),testData);
				email = username + "@mailinator.com";
				firstName = testData.getFirstName() + IHGUtil.createRandomNumber();
				lastName = testData.getLastName();
				password = testData.getPassword();
				gender = Patient.GenderExtended.MALE;
				url = testData.getUrl();
				DOBDay = testData.getDOBDay();
				DOBMonth = testData.getDOBMonth();
				DOBMonthText = testData.getDOBMonthText();
				DOBYear = testData.getDOBYear();
				ZipCode = testData.getZipCode();
				// TODO fix this hack - sak nemame pristup do com.medfusion.common.utils, tak co? :)
				address1 = "U rychtare gejoty 8";
				address2 = "U bobra 12";
				city = "Mamlasov";
				state = "Alabama";
		}

		public String getEmail() {
				return email;
		}

		public void setEmail(String email) {
				this.email = email;
		}

		public String getPassword() {
				return password;
		}

		public void setPassword(String password) {
				this.password = password;
		}

		public String getUrl() {
				return url;
		}

		public void setUrl(String url) {
				this.url = url;
		}

		public String getFirstName() {
				return firstName;
		}

		public void setFirstName(String firstName) {
				this.firstName = firstName;
		}

		public String getLastName() {
				return lastName;
		}

		public void setLastName(String lastName) {
				this.lastName = lastName;
		}

		public Patient.GenderExtended getGender() {
				return gender;
		}

		public void setGender(Patient.GenderExtended gender) {
				this.gender = gender;
		}

		public String getDOBDay() {
				return DOBDay;
		}

		public void setDOBDay(String dobDay) {
				DOBDay = dobDay;
		}

		public String getDOBMonth() {
				return DOBMonth;
		}

		public void setDOBMonth(String dobMonth) {
				DOBMonth = dobMonth;
		}

		public String getDOBMonthText() {
				return DOBMonthText;
		}

		public void setDOBMonthText(String dobMonthText) {
				DOBMonthText = dobMonthText;
		}

		public String getDOBYear() {
				return DOBYear;
		}

		public void setDOBYear(String dobYear) {
				DOBYear = dobYear;
		}

		public String getZipCode() {
				return ZipCode;
		}

		public void setZipCode(String zipCode) {
				ZipCode = zipCode;
		}

		public String getAddress1() {
				return address1;
		}

		public void setAddress1(String address1) {
				this.address1 = address1;
		}

		public String getAddress2() {
				return address2;
		}

		public void setAddress2(String address2) {
				this.address2 = address2;
		}

		public String getCity() {
				return city;
		}

		public void setCity(String city) {
				this.city = city;
		}

		public String getState() {
				return state;
		}

		public void setState(String state) {
				this.state = state;
		}

		public String getUsername() {
				return username;
		}

		public void setUsername(String username) {
				this.username = username;
		}
}
