// Copyright 2021 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.pss2patientapi.payload;

public class PayloadAdapterModulator {
	
	public String openTokenPayload(String practiceid) {
		String openToken = "{\r\n"
				+ "    \"practiceId\": \""+practiceid+"\",\r\n"
				+ "    \"authUserId\": \"mf:ad:username:nshirodkar\"\r\n"
				+ "}";
		return openToken;
	}
	
	public String saveAnnouncementPayload(int id, String type,String code ) {
		String saveAnn = "{\r\n"
				+ "    \"id\": "+id+",\r\n"
				+ "    \"text\": {\r\n"
				+ "        \"EN\": \"Good Night\",\r\n"
				+ "        \"ES\": \"Espanol Good Night\"\r\n"
				+ "    },\r\n"
				+ "    \"display\": \"Your welcome message will be displayed here. Please contact Medfusion support to add your own text or disable this message.\",\r\n"
				+ "    \"type\": \""+type+"\",\r\n"
				+ "    \"code\": \""+code+"\",\r\n"
				+ "    \"selected\": true,\r\n"
				+ "    \"description\": \"Displayed in dialog when PSS first page loads\"\r\n"
				+ "}";
		return saveAnn;
	}
	
	public String updateAnnouncementPayload(int id, String type,String code ) {
		String updateAnn = "{\r\n"
				+ "    \"id\": "+id+",\r\n"
				+ "    \"text\": {\r\n"
				+ "        \"EN\": \"Good Night\",\r\n"
				+ "        \"ES\": \"Espanol Good Night\"\r\n"
				+ "    },\r\n"
				+ "    \"display\": \"Your welcome message will be displayed here. Please contact Medfusion support to add your own text or disable this message.\",\r\n"
				+ "    \"type\": \""+type+"\",\r\n"
				+ "    \"code\": \""+code+"\",\r\n"
				+ "    \"selected\": true,\r\n"
				+ "    \"description\": \"Displayed in dialog when PSS first page loads\"\r\n"
				+ "}";
		return updateAnn;
	}
	
	public String saveApptTypePayload() {
		String saveAppt = "[{\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 201105,\r\n"
				+ "    \"name\": \"Newpatient30\",\r\n"
				+ "    \"displayName\": \"Newpatient30\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "        \"EN\": \"Newpatient30\",\r\n"
				+ "        \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "        \"EN\": \"message\",\r\n"
				+ "        \"ES\": \"message span 1\"\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "        \"EN\": \"Custom question custom question?\",\r\n"
				+ "        \"ES\": \"Custom question custom question span?\"\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "        \"EN\": null,\r\n"
				+ "        \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"categoryId\": \"c9cc92fb-06c2-420b-ab60-e95dd5c7af83\",\r\n"
				+ "    \"categoryName\": \"Newpatient30\",\r\n"
				+ "    \"extAppointmentTypeId\": \"ec5c2faa-57e1-4121-9c0b-fc99a462281d\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"200350\",\r\n"
				+ "            \"name\": \"Main Office\",\r\n"
				+ "            \"displayName\": \"Main Office\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 200350,\r\n"
				+ "                \"address1\": \"2011 Falls Valley Dr\",\r\n"
				+ "                \"address2\": \"#106\",\r\n"
				+ "                \"city\": \"Raleigh\",\r\n"
				+ "                \"state\": \"North Carolina\",\r\n"
				+ "                \"zipCode\": \"27615\",\r\n"
				+ "                \"latitude\": 35.8973143,\r\n"
				+ "                \"longitude\": -78.60541409999999\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"9d971e61-2b5a-4504-9016-7fd863790ee2\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"202403\",\r\n"
				+ "            \"name\": \"RHC Main Office\",\r\n"
				+ "            \"displayName\": \"RHC Main Office\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 202353,\r\n"
				+ "                \"address1\": \"998 Collier Rd\",\r\n"
				+ "                \"city\": \"Atlanta\",\r\n"
				+ "                \"state\": \"GA\",\r\n"
				+ "                \"zipCode\": \"303091234\",\r\n"
				+ "                \"latitude\": 33.8100883,\r\n"
				+ "                \"longitude\": -84.42035880000003\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"5EF9DC47-B3CB-43C3-AA88-FF9D330CF5E9\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"201651\",\r\n"
				+ "            \"name\": \"ABC Optical\",\r\n"
				+ "            \"displayName\": \"ABC Optical span\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 201601,\r\n"
				+ "                \"address1\": \"4421 Lake Boone Trail W\",\r\n"
				+ "                \"address2\": \"Address line 2, Updated #3\",\r\n"
				+ "                \"city\": \"Raleigh\",\r\n"
				+ "                \"state\": \"NC\",\r\n"
				+ "                \"zipCode\": \"27607\",\r\n"
				+ "                \"latitude\": 38.6624944,\r\n"
				+ "                \"longitude\": -90.47854949999999\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"80DE19AE-6BBF-477E-BC8B-371AEF0773DA\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": true,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"202402\",\r\n"
				+ "            \"name\": \"Behavioral Health At Lake Aire Medical\",\r\n"
				+ "            \"displayName\": \"Behavioral Health At Lake Aire Medical\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 202352,\r\n"
				+ "                \"address1\": \"2423 Williams Dr\",\r\n"
				+ "                \"address2\": \"Suite 108\",\r\n"
				+ "                \"city\": \"Georgetown\",\r\n"
				+ "                \"state\": \"TX\",\r\n"
				+ "                \"zipCode\": \"78628\",\r\n"
				+ "                \"latitude\": 30.6605928,\r\n"
				+ "                \"longitude\": -97.68796429999999\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"13E61FF5-7E2A-4FD4-895D-8E79A99F1597\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"200702\",\r\n"
				+ "            \"name\": \"Saint Joseph's Hospital\",\r\n"
				+ "            \"displayName\": \"Triangle Health Knightdale\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 200652,\r\n"
				+ "                \"address1\": \"909 Knightdale Blvd\",\r\n"
				+ "                \"city\": \"Knightdale\",\r\n"
				+ "                \"state\": \"NC\",\r\n"
				+ "                \"zipCode\": \"27545\",\r\n"
				+ "                \"latitude\": 35.7956002,\r\n"
				+ "                \"longitude\": -78.51262750000001\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"c9a32a00-796e-41a6-91ae-1b46f645f5cc\",\r\n"
				+ "            \"directionUrl\": \"https://www.google.com/maps/dir//909+Knightdale+Blvd,+Knightdale,+NC+27545/@35.7956002,-78.5148162,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x89ac5c8255dc5e75:0x30f29823c147509b!2m2!1d-78.5126275!2d35.7956002\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"204152\",\r\n"
				+ "            \"name\": \"Satellite Location 1\",\r\n"
				+ "            \"displayName\": \"Satellite Location 1\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 204052,\r\n"
				+ "                \"address1\": \"449 Roswell Rd\",\r\n"
				+ "                \"city\": \"Atlanta\",\r\n"
				+ "                \"state\": \"GA\",\r\n"
				+ "                \"zipCode\": \"30342\",\r\n"
				+ "                \"latitude\": 0,\r\n"
				+ "                \"longitude\": 0\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"A21148E1-66C3-459A-AD83-C0733D97693A\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "        \"id\": 200402,\r\n"
				+ "        \"appointmentStacking\": false,\r\n"
				+ "        \"slotCount\": 1,\r\n"
				+ "        \"allowSameDayAppts\": true,\r\n"
				+ "        \"apptTimeMark\": 0,\r\n"
				+ "        \"apptTypeAllocated\": true,\r\n"
				+ "        \"isContiguous\": true,\r\n"
				+ "        \"leadTime\": {\r\n"
				+ "            \"days\": \"0\",\r\n"
				+ "            \"hours\": \"0\",\r\n"
				+ "            \"mins\": \"0\"\r\n"
				+ "        },\r\n"
				+ "        \"excludeSlots\": [],\r\n"
				+ "        \"apptTypeReservedReason\": \"n\",\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"allowOnlineCancellation\": true,\r\n"
				+ "        \"slotSize\": 5,\r\n"
				+ "        \"schedulingDuration\": 15,\r\n"
				+ "        \"pttype\": \"PT_ALL\",\r\n"
				+ "        \"lastQuestRequired\": true\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "}]";
		return saveAppt;
	}
	
	public String saveApptTypeWithoutIdPayload() {
		String saveAppt = "[{\r\n"				
				+ "    \"displayNames\": {\r\n"
				+ "        \"EN\": \"Newpatient30\",\r\n"
				+ "        \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "        \"EN\": \"message\",\r\n"
				+ "        \"ES\": \"message span 1\"\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "        \"EN\": \"Custom question custom question?\",\r\n"
				+ "        \"ES\": \"Custom question custom question span?\"\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "        \"EN\": null,\r\n"
				+ "        \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"categoryId\": \"c9cc92fb-06c2-420b-ab60-e95dd5c7af83\",\r\n"
				+ "    \"categoryName\": \"Newpatient30\",\r\n"
				+ "    \"extAppointmentTypeId\": \"ec5c2faa-57e1-4121-9c0b-fc99a462281d\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"200350\",\r\n"
				+ "            \"name\": \"Main Office\",\r\n"
				+ "            \"displayName\": \"Main Office\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 200350,\r\n"
				+ "                \"address1\": \"2011 Falls Valley Dr\",\r\n"
				+ "                \"address2\": \"#106\",\r\n"
				+ "                \"city\": \"Raleigh\",\r\n"
				+ "                \"state\": \"North Carolina\",\r\n"
				+ "                \"zipCode\": \"27615\",\r\n"
				+ "                \"latitude\": 35.8973143,\r\n"
				+ "                \"longitude\": -78.60541409999999\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"9d971e61-2b5a-4504-9016-7fd863790ee2\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"202403\",\r\n"
				+ "            \"name\": \"RHC Main Office\",\r\n"
				+ "            \"displayName\": \"RHC Main Office\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 202353,\r\n"
				+ "                \"address1\": \"998 Collier Rd\",\r\n"
				+ "                \"city\": \"Atlanta\",\r\n"
				+ "                \"state\": \"GA\",\r\n"
				+ "                \"zipCode\": \"303091234\",\r\n"
				+ "                \"latitude\": 33.8100883,\r\n"
				+ "                \"longitude\": -84.42035880000003\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"5EF9DC47-B3CB-43C3-AA88-FF9D330CF5E9\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"201651\",\r\n"
				+ "            \"name\": \"ABC Optical\",\r\n"
				+ "            \"displayName\": \"ABC Optical span\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 201601,\r\n"
				+ "                \"address1\": \"4421 Lake Boone Trail W\",\r\n"
				+ "                \"address2\": \"Address line 2, Updated #3\",\r\n"
				+ "                \"city\": \"Raleigh\",\r\n"
				+ "                \"state\": \"NC\",\r\n"
				+ "                \"zipCode\": \"27607\",\r\n"
				+ "                \"latitude\": 38.6624944,\r\n"
				+ "                \"longitude\": -90.47854949999999\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"80DE19AE-6BBF-477E-BC8B-371AEF0773DA\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": true,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"202402\",\r\n"
				+ "            \"name\": \"Behavioral Health At Lake Aire Medical\",\r\n"
				+ "            \"displayName\": \"Behavioral Health At Lake Aire Medical\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 202352,\r\n"
				+ "                \"address1\": \"2423 Williams Dr\",\r\n"
				+ "                \"address2\": \"Suite 108\",\r\n"
				+ "                \"city\": \"Georgetown\",\r\n"
				+ "                \"state\": \"TX\",\r\n"
				+ "                \"zipCode\": \"78628\",\r\n"
				+ "                \"latitude\": 30.6605928,\r\n"
				+ "                \"longitude\": -97.68796429999999\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"13E61FF5-7E2A-4FD4-895D-8E79A99F1597\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"200702\",\r\n"
				+ "            \"name\": \"Saint Joseph's Hospital\",\r\n"
				+ "            \"displayName\": \"Triangle Health Knightdale\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 200652,\r\n"
				+ "                \"address1\": \"909 Knightdale Blvd\",\r\n"
				+ "                \"city\": \"Knightdale\",\r\n"
				+ "                \"state\": \"NC\",\r\n"
				+ "                \"zipCode\": \"27545\",\r\n"
				+ "                \"latitude\": 35.7956002,\r\n"
				+ "                \"longitude\": -78.51262750000001\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"c9a32a00-796e-41a6-91ae-1b46f645f5cc\",\r\n"
				+ "            \"directionUrl\": \"https://www.google.com/maps/dir//909+Knightdale+Blvd,+Knightdale,+NC+27545/@35.7956002,-78.5148162,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x89ac5c8255dc5e75:0x30f29823c147509b!2m2!1d-78.5126275!2d35.7956002\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"204152\",\r\n"
				+ "            \"name\": \"Satellite Location 1\",\r\n"
				+ "            \"displayName\": \"Satellite Location 1\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 204052,\r\n"
				+ "                \"address1\": \"449 Roswell Rd\",\r\n"
				+ "                \"city\": \"Atlanta\",\r\n"
				+ "                \"state\": \"GA\",\r\n"
				+ "                \"zipCode\": \"30342\",\r\n"
				+ "                \"latitude\": 0,\r\n"
				+ "                \"longitude\": 0\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"A21148E1-66C3-459A-AD83-C0733D97693A\",\r\n"
				+ "            \"selected\": false,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "        \"id\": 200402,\r\n"
				+ "        \"appointmentStacking\": false,\r\n"
				+ "        \"slotCount\": 1,\r\n"
				+ "        \"allowSameDayAppts\": true,\r\n"
				+ "        \"apptTimeMark\": 0,\r\n"
				+ "        \"apptTypeAllocated\": true,\r\n"
				+ "        \"isContiguous\": true,\r\n"
				+ "        \"leadTime\": {\r\n"
				+ "            \"days\": \"0\",\r\n"
				+ "            \"hours\": \"0\",\r\n"
				+ "            \"mins\": \"0\"\r\n"
				+ "        },\r\n"
				+ "        \"excludeSlots\": [],\r\n"
				+ "        \"apptTypeReservedReason\": \"n\",\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"allowOnlineCancellation\": true,\r\n"
				+ "        \"slotSize\": 5,\r\n"
				+ "        \"schedulingDuration\": 15,\r\n"
				+ "        \"pttype\": \"PT_ALL\",\r\n"
				+ "        \"lastQuestRequired\": true\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "}]";
		return saveAppt;
	}
	
	public String saveBookAppointmentTypePayload() {
		String saveBookAppt = "{\r\n"
				+ "    \"book\": {\r\n"
				+ "        \"id\": 4247\r\n"
				+ "    },\r\n"
				+ "    \"appointmentType\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": 4195\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return saveBookAppt;
	}
	
	public String reorderApptPayload() {
		String reorder = "{\r\n"
				+ "    \"source\": 2,\r\n"
				+ "    \"target\": 0\r\n"
				+ "}";
		return reorder;
	}
	
	public String saveBookLocationPayload() {
		String booklocation="{\r\n"
				+ "    \"book\": {\r\n"
				+ "        \"id\": 4248\r\n"
				+ "    },\r\n"
				+ "    \"location\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"4161\"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return booklocation;
	}
	
	public String bookAppointmentTypeSavePayload(String bookid, String apptid) {
		String bookAppointment="{\r\n"
				+ "    \"book\": {\r\n"
				+ "        \"id\": "+bookid+"\r\n"
				+ "    },\r\n"
				+ "    \"appointmentType\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": "+apptid+"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return bookAppointment;
	}
	
	public String bookAppointmentTypUpdatePayload(String bookid, String apptid) {
		String bookAppointment="{\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 4442,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"book\": {\r\n"
				+ "        \"id\": 206501,\r\n"
				+ "        \"name\": null,\r\n"
				+ "        \"displayName\": null,\r\n"
				+ "        \"emailAddress\": null,\r\n"
				+ "        \"extBookId\": null,\r\n"
				+ "        \"acceptComment\": null,\r\n"
				+ "        \"acceptEmail\": null,\r\n"
				+ "        \"acceptNew\": null,\r\n"
				+ "        \"ageRule\": null,\r\n"
				+ "        \"deleted\": null,\r\n"
				+ "        \"providerMessage\": null,\r\n"
				+ "        \"sharePatients\": null,\r\n"
				+ "        \"slotSize\": null,\r\n"
				+ "        \"status\": false,\r\n"
				+ "        \"categoryId\": null,\r\n"
				+ "        \"categoryName\": null,\r\n"
				+ "        \"practice\": null,\r\n"
				+ "        \"specialty\": null,\r\n"
				+ "        \"bookSort\": null,\r\n"
				+ "        \"bookTranslations\": null,\r\n"
				+ "        \"bookType\": null,\r\n"
				+ "        \"bookLevel\": null,\r\n"
				+ "        \"careteam\": null,\r\n"
				+ "        \"links\": null\r\n"
				+ "    },\r\n"
				+ "    \"appointmentType\": {\r\n"
				+ "        \"id\": 206533,\r\n"
				+ "        \"name\": null,\r\n"
				+ "        \"displayName\": null,\r\n"
				+ "        \"description\": null,\r\n"
				+ "        \"extAppointmentTypeId\": null,\r\n"
				+ "        \"duration\": null,\r\n"
				+ "        \"categoryId\": null,\r\n"
				+ "        \"categoryName\": null,\r\n"
				+ "        \"messages\": null,\r\n"
				+ "        \"customQuestion\": null,\r\n"
				+ "        \"customMessage\": null,\r\n"
				+ "        \"appointmentTypeTranslation\": null,\r\n"
				+ "        \"preventRescheduleOnCancel\": null,\r\n"
				+ "        \"ageRule\": null,\r\n"
				+ "        \"preventScheduling\": null,\r\n"
				+ "        \"appointmentTypeSort\": null\r\n"
				+ "    },\r\n"
				+ "    \"appointmentStacking\": false,\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"slotCount\": 1,\r\n"
				+ "    \"allowSameDayAppts\": true,\r\n"
				+ "    \"apptTimeMark\": 0,\r\n"
				+ "    \"apptTypeAllocated\": true,\r\n"
				+ "    \"isContiguous\": false,\r\n"
				+ "    \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "    },\r\n"
				+ "    \"maxPerDay\": 0,\r\n"
				+ "    \"excludeSlots\": [],\r\n"
				+ "    \"apptTypeReservedReason\": \"n\",\r\n"
				+ "    \"ageRule\": \"\",\r\n"
				+ "    \"status\": true,\r\n"
				+ "    \"allowOnlineCancellation\": true,\r\n"
				+ "    \"providerAvailabilityDays\": 0,\r\n"
				+ "    \"schedulingDuration\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"206350\",\r\n"
				+ "            \"name\": \"Interfaces Location\",\r\n"
				+ "            \"displayName\": \"Interfaces Location\",\r\n"
				+ "            \"address\": {\r\n"
				+ "                \"id\": 206250,\r\n"
				+ "                \"address1\": \"50 Marcus\",\r\n"
				+ "                \"address2\": \"\",\r\n"
				+ "                \"city\": \"Melville\",\r\n"
				+ "                \"state\": \"NY\",\r\n"
				+ "                \"zipCode\": \"11747\",\r\n"
				+ "                \"latitude\": 40.75729159999999,\r\n"
				+ "                \"longitude\": -73.4121919,\r\n"
				+ "                \"locAddress\": \"50 Marcus  Melville NY 11747\"\r\n"
				+ "            },\r\n"
				+ "            \"timezone\": \"\",\r\n"
				+ "            \"extLocationId\": \"97624552-7991-41E8-87FD-464362D1EAF8\",\r\n"
				+ "            \"selected\": true,\r\n"
				+ "            \"phoneNumber\": \"\",\r\n"
				+ "            \"restrictToCareteam\": false,\r\n"
				+ "            \"locationLinks\": {}\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"pttype\": \"PT_ALL\",\r\n"
				+ "    \"lastQuestRequired\": false\r\n"
				+ "}";
		return bookAppointment;
	}
	
	public String bookLocationSavePayload(String bookid, String locationid) {
		String booklocation="{\r\n"
				+ "    \"book\": {\r\n"
				+ "        \"id\": "+bookid+"\r\n"
				+ "    },\r\n"
				+ "    \"location\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \""+locationid+"\"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return booklocation;
	}
	
	
	
	

}
