// Copyright 2022 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.pss2patientapi.payload;

public class PayloadAM01 {
	
	public String openTokenPayload(String practiceid,String authUser) {
		String openToken = "{\r\n"
				+ "    \"practiceId\": \""+practiceid+"\",\r\n"
				+ "    \"authUserId\": \""+authUser+"\"\r\n"
				+ "}";
		return openToken;
	}
	

	public String timeMark() {
		String timeMark = "{\r\n"
				+ "    \"id\": 201750,\r\n"
				+ "    \"appointmentStacking\": false,\r\n"
				+ "    \"slotCount\": 1,\r\n"
				+ "    \"allowSameDayAppts\": true,\r\n"
				+ "    \"apptTimeMark\": 30,\r\n"
				+ "    \"apptTypeAllocated\": true,\r\n"
				+ "    \"isContiguous\": false,\r\n"
				+ "    \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "    },\r\n"
				+ "    \"excludeSlots\": [],\r\n"
				+ "    \"apptTypeReservedReason\": \"n\",\r\n"
				+ "    \"acceptComment\": false,\r\n"
				+ "    \"allowOnlineCancellation\": true,\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"schedulingDuration\": 0,\r\n"
				+ "    \"pttype\": \"PT_ALL\",\r\n"
				+ "    \"lastQuestRequired\": false\r\n"
				+ "}";
		return timeMark;
	}
	
	
	
	public String turnONOFFShowProvider(boolean value) {
		String turnONShowProvider = "[\r\n"
				+ "    {\r\n"
				+ "        \"group\": \"RULEENGINE\",\r\n"
				+ "        \"key\": \"showProvider\",\r\n"
				+ "        \"value\": "+value+"\r\n"
				+ "    }\r\n"
				+ "]";
		return turnONShowProvider;
	}

	
	public String turnONOFFDecisionTree(boolean value) {
		String turnOFFShowProvider = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"showCategory\",\r\n"
				+ "    \"value\": "+value+"\r\n"
				+ "  }\r\n"
				+ "]";
		return turnOFFShowProvider;
	}
	
	public String reserveForSameDay(String reserveValue,boolean acceptValue,int timeMark,int confirmId) {
		String reserveForSameDay = "{\r\n"
				+ "    \"id\": "+confirmId+",\r\n"
				+ "    \"appointmentStacking\": false,\r\n"
				+ "    \"slotCount\": 1,\r\n"
				+ "    \"allowSameDayAppts\": "+acceptValue+",\r\n"
				+ "    \"apptTimeMark\": "+timeMark+",\r\n"
				+ "    \"apptTypeAllocated\": true,\r\n"
				+ "    \"isContiguous\": false,\r\n"
				+ "    \"leadTime\": {\r\n"
				+ "        \"days\": 0,\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "    },\r\n"
				+ "    \"excludeSlots\": [],\r\n"
				+ "    \"apptTypeReservedReason\": \""+reserveValue+"\",\r\n"
				+ "    \"acceptComment\": false,\r\n"
				+ "    \"allowOnlineCancellation\": true,\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"schedulingDuration\": 0,\r\n"
				+ "    \"pttype\": \"PT_ALL\",\r\n"
				+ "    \"lastQuestRequired\": false\r\n"
				+ "}";
		return reserveForSameDay;
	}
	
	public String hideSlots(int leadValue,int configId)
	{
		String hideSlots="{\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"appointmentStacking\": true,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": "+leadValue+",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": false,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return hideSlots;
		
	}
	
	public String showUpcomingToggle()
	{
		String showUpcomingToggle="[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"allowCancellationHours\",\r\n"
				+ "    \"value\": \"00:00\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PATIENT_ACCESS\",\r\n"
				+ "    \"key\": \"ValidDuration\",\r\n"
				+ "    \"value\": \"1\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"displaySlotsCount\",\r\n"
				+ "    \"value\": \"50\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"maxCalendarMonths\",\r\n"
				+ "    \"value\": \"100\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ageRestriction\",\r\n"
				+ "    \"value\": \"30\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"maxAppointments\",\r\n"
				+ "    \"value\": \"10\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ShowPastAppointmentMonths\",\r\n"
				+ "    \"value\": \"10\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"showNextAvailable\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"LOCATION\",\r\n"
				+ "    \"key\": \"searchLocation\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showUpcoming\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showPast\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"patientUpdateConfig\",\r\n"
				+ "    \"value\": \"UPDATE_INFO\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"establishPatientLastVisit\",\r\n"
				+ "    \"value\": \"365\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showCancelReason\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"patientCreationDuration\",\r\n"
				+ "    \"value\": \"365\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MULTI_PRACTICE_SETTING\",\r\n"
				+ "    \"key\": \"sharePatientAcrossPractices\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  }\r\n"
				+ "]";
		return showUpcomingToggle;
		
	}
	

	public String acceptForSameDayONOFF(String value) {
		String reserveForSameDay = "{\r\n"
				+ "    \"id\": 203099,\r\n"
				+ "    \"appointmentStacking\": false,\r\n"
				+ "    \"slotCount\": 1,\r\n"
				+ "    \"allowSameDayAppts\": true,\r\n"
				+ "    \"apptTimeMark\": 0,\r\n"
				+ "    \"apptTypeAllocated\": true,\r\n"
				+ "    \"isContiguous\": false,\r\n"
				+ "    \"leadTime\": {\r\n"
				+ "        \"days\": 0,\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "    },\r\n"
				+ "    \"excludeSlots\": [],\r\n"
				+ "    \"apptTypeReservedReason\": \""+value+"\",\r\n"
				+ "    \"acceptComment\": false,\r\n"
				+ "    \"allowOnlineCancellation\": true,\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"schedulingDuration\": 0,\r\n"
				+ "    \"pttype\": \"PT_ALL\",\r\n"
				+ "    \"lastQuestRequired\": false\r\n"
				+ "}";
		return reserveForSameDay;
	}
	
	public String specialityAgeRulePost(int specialityId,String specialityName,String displayName,String firstValue,String secondValue) {
		String specialityPost = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": true,\r\n"
				+ "    \"isgenderRule\": false,\r\n"
				+ "    \"id\": "+specialityId+",\r\n"
				+ "    \"name\": \""+specialityName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Internal Medicine\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \""+displayName+"\",\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"ageRule\": \"> "+firstValue+" And < "+secondValue+"\",\r\n"
				+ "    \"genderRule\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Female\",\r\n"
				+ "        \"pssCode\": \"F\",\r\n"
				+ "        \"partnerCode\": \"F\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 2,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Male\",\r\n"
				+ "        \"pssCode\": \"M\",\r\n"
				+ "        \"partnerCode\": \"M\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 1,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Unknown\",\r\n"
				+ "        \"pssCode\": \"U\",\r\n"
				+ "        \"partnerCode\": \"U\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 3,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Undifferentiated (Other)\",\r\n"
				+ "        \"pssCode\": \"UN\",\r\n"
				+ "        \"partnerCode\": \"O\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 5,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		return specialityPost;

	}
	
	public String specialityAgeRuleResetPost(int specialityId,String specialityName,String displayName)
	{
		String specialityAgeRulePost="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"isgenderRule\": false,\r\n"
				+ "    \"id\": "+specialityId+",\r\n"
				+ "    \"name\": \""+specialityName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \""+displayName+"\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \"Internal Medicine\",\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"ageRule\": \"\",\r\n"
				+ "    \"genderRule\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Female\",\r\n"
				+ "        \"pssCode\": \"F\",\r\n"
				+ "        \"partnerCode\": \"F\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 2,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Male\",\r\n"
				+ "        \"pssCode\": \"M\",\r\n"
				+ "        \"partnerCode\": \"M\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 1,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Unknown\",\r\n"
				+ "        \"pssCode\": \"U\",\r\n"
				+ "        \"partnerCode\": \"U\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 3,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Undifferentiated (Other)\",\r\n"
				+ "        \"pssCode\": \"UN\",\r\n"
				+ "        \"partnerCode\": \"O\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 5,\r\n"
				+ "        \"codeGroup\": \"gender\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		return specialityAgeRulePost;
	}
	
	public String bookAgeRulePost(int providerId,String providerName,String displayName,String extId,String firstValue,String secondValue) {
		String bookAgeRulePost = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": true,\r\n"
				+ "    \"id\": "+providerId+",\r\n"
				+ "    \"name\": \""+providerName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Ng3 Pss [PSS,NG3]\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \""+displayName+"\",\r\n"
				+ "    \"ageRule\": \"> "+firstValue+" And < "+secondValue+"\",\r\n"
				+ "    \"extBookId\": \""+extId+"\",\r\n"
				+ "    \"sharePatients\": false,\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"status\": true,\r\n"
				+ "    \"providerImage\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/pss-adapter-modulator/24293/book/C20178B6-BE4A-4176-B7FD-B6901C38A051/image\",\r\n"
				+ "    \"specialty\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"isgenderRule\": false,\r\n"
				+ "        \"id\": 203767,\r\n"
				+ "        \"name\": \"abc's\",\r\n"
				+ "        \"displayName\": \"abc's\",\r\n"
				+ "        \"ageRule\": \"\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"location\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"appointmentType\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 205754,\r\n"
				+ "        \"name\": \"Covid-19\",\r\n"
				+ "        \"displayName\": \"Covid-19\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"8F563A6C-7098-4446-97E2-7EF9345ED469\",\r\n"
				+ "        \"categoryName\": \"Covid-19\",\r\n"
				+ "        \"extAppointmentTypeId\": \"86D0E00F-C136-4A24-BF7A-6C17E9AB35ED\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 209164,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"362C3DF3-A4D9-490A-AFC8-3BD6017BD025\",\r\n"
				+ "        \"categoryName\": \"Aapt Category1\",\r\n"
				+ "        \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 4237,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"24A7DC4F-4DB6-427C-9FA5-EB76FA2142D0\",\r\n"
				+ "        \"categoryName\": \"Insomnia\",\r\n"
				+ "        \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"sortOrder\": 25,\r\n"
				+ "    \"acceptComment\": true,\r\n"
				+ "    \"acceptNew\": false,\r\n"
				+ "    \"categoryId\": \"185541C1-D44B-4D12-AA7E-F25A7B0F4A7D\",\r\n"
				+ "    \"categoryName\": \"Ng3 Pss [PSS,NG3]\",\r\n"
				+ "    \"bookType\": {\r\n"
				+ "      \"name\": \"PERSON\",\r\n"
				+ "      \"code\": \"RS_PERSON\",\r\n"
				+ "      \"grouptype\": \"RESOURCE\"\r\n"
				+ "    },\r\n"
				+ "    \"bookLevel\": {\r\n"
				+ "      \"name\": \"None\",\r\n"
				+ "      \"code\": \"RS_NONE\",\r\n"
				+ "      \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "    },\r\n"
				+ "    \"careteam\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 4060,\r\n"
				+ "        \"name\": \"ct\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"providerlinks\": {\r\n"
				+ "      \"baseurl\": \"https://dev3-pss.dev.medfusion.net/psspatient/login\",\r\n"
				+ "      \"links\": [\r\n"
				+ "        {\r\n"
				+ "          \"id\": 0,\r\n"
				+ "          \"type\": \"ANONYMOUS\",\r\n"
				+ "          \"guid\": \"9515140d-fc88-49eb-b1a3-8895a6eaf2b0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"id\": 0,\r\n"
				+ "          \"type\": \"LOGINLESS\",\r\n"
				+ "          \"guid\": \"72d3c86c-8689-4a95-9414-d0b7149b8f2a\"\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "]";
		return bookAgeRulePost;

	}
	
	public String resetBookAgeRulePost(int providerId,String providerName,String displayName,String extId) {
		String bookAgeRulePost = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": "+providerId+",\r\n"
				+ "    \"name\": \""+providerName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Ng3 Pss [PSS,NG3]\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \""+displayName+"\",\r\n"
				+ "    \"ageRule\": \"\",\r\n"
				+ "    \"extBookId\": \""+extId+"\",\r\n"
				+ "    \"sharePatients\": false,\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"status\": true,\r\n"
				+ "    \"providerImage\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/pss-adapter-modulator/24293/book/C20178B6-BE4A-4176-B7FD-B6901C38A051/image\",\r\n"
				+ "    \"specialty\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"isgenderRule\": false,\r\n"
				+ "        \"id\": 203767,\r\n"
				+ "        \"name\": \"abc's\",\r\n"
				+ "        \"displayName\": \"abc's\",\r\n"
				+ "        \"ageRule\": \"\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"location\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"appointmentType\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 205754,\r\n"
				+ "        \"name\": \"Covid-19\",\r\n"
				+ "        \"displayName\": \"Covid-19\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"8F563A6C-7098-4446-97E2-7EF9345ED469\",\r\n"
				+ "        \"categoryName\": \"Covid-19\",\r\n"
				+ "        \"extAppointmentTypeId\": \"86D0E00F-C136-4A24-BF7A-6C17E9AB35ED\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 209164,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"362C3DF3-A4D9-490A-AFC8-3BD6017BD025\",\r\n"
				+ "        \"categoryName\": \"Aapt Category1\",\r\n"
				+ "        \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 4237,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"24A7DC4F-4DB6-427C-9FA5-EB76FA2142D0\",\r\n"
				+ "        \"categoryName\": \"Insomnia\",\r\n"
				+ "        \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"sortOrder\": 25,\r\n"
				+ "    \"acceptComment\": true,\r\n"
				+ "    \"acceptNew\": false,\r\n"
				+ "    \"categoryId\": \"185541C1-D44B-4D12-AA7E-F25A7B0F4A7D\",\r\n"
				+ "    \"categoryName\": \"Ng3 Pss [PSS,NG3]\",\r\n"
				+ "    \"bookType\": {\r\n"
				+ "      \"name\": \"PERSON\",\r\n"
				+ "      \"code\": \"RS_PERSON\",\r\n"
				+ "      \"grouptype\": \"RESOURCE\"\r\n"
				+ "    },\r\n"
				+ "    \"bookLevel\": {\r\n"
				+ "      \"name\": \"None\",\r\n"
				+ "      \"code\": \"RS_NONE\",\r\n"
				+ "      \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "    },\r\n"
				+ "    \"careteam\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 4060,\r\n"
				+ "        \"name\": \"ct\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"providerlinks\": {\r\n"
				+ "      \"baseurl\": \"https://dev3-pss.dev.medfusion.net/psspatient/login\",\r\n"
				+ "      \"links\": [\r\n"
				+ "        {\r\n"
				+ "          \"id\": 0,\r\n"
				+ "          \"type\": \"ANONYMOUS\",\r\n"
				+ "          \"guid\": \"9515140d-fc88-49eb-b1a3-8895a6eaf2b0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"id\": 0,\r\n"
				+ "          \"type\": \"LOGINLESS\",\r\n"
				+ "          \"guid\": \"72d3c86c-8689-4a95-9414-d0b7149b8f2a\"\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "]";
		return bookAgeRulePost;

	}
	
	
	public String mergeSlotPyaload(int slotCount,int slotSize,int configId)
	{
		String mergeSlotPyaload="{\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": "+slotCount+",\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": "+slotSize+",\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return mergeSlotPyaload;
		
	}
	
	public String excludeSlotPyaload(int configId)
	{
		String excludeSlotPyaload="{\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [\r\n"
				+ "    {\r\n"
				+ "      \"startTime\": \"01:00\",\r\n"
				+ "      \"endTime\": \"00:00\",\r\n"
				+ "      \"beforeAfterStart\": \"<\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"startTime\": \"01:15\",\r\n"
				+ "      \"endTime\": \"00:00\",\r\n"
				+ "      \"beforeAfterStart\": \">\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": false,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return excludeSlotPyaload;
		
	}
	
	public String resetExcludeSlotPyaload(int configId)
	{
		String resetExcludeSlotPyaload="{\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": false,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return resetExcludeSlotPyaload;
		
	}
	
	public String lastQEnableshowProviderOFF(boolean lastValue,boolean lastQueRequired,int configId)
	{
		String lastQEnable="{\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": "+lastValue+",\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": "+lastQueRequired+"\r\n"
				+ "}";
		return lastQEnable;
		
	}
	
	public String bookAppTypePayload(String bookId,String apptId,boolean lastQueRequired,int configId)
	{
		String lastQEnable="{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": "+bookId+",\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": "+apptId+",\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"205604\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"pss wla\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 205504,\r\n"
				+ "        \"address1\": \"5501\",\r\n"
				+ "        \"address2\": \"Dillard Dr\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"North Carolina\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"latitude\": 35.7531299,\r\n"
				+ "        \"longitude\": -78.73247119999999,\r\n"
				+ "        \"locAddress\": \"5501 Dillard Dr Cary North Carolina 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": true,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": "+lastQueRequired+"\r\n"
				+ "}";
		return lastQEnable;
		
	}
	
	public String bookPayload(String bookId,String bookName,String extId,boolean lastQueEnable,String catId,String appExtId)
	{
		String bookPayload="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": "+bookId+",\r\n"
				+ "    \"name\": \""+bookName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Ng3 Pss [PSS,NG3]\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \"Ng3 Pss [PSS,NG3]\",\r\n"
				+ "    \"ageRule\": \"\",\r\n"
				+ "    \"extBookId\": \""+extId+"\",\r\n"
				+ "    \"sharePatients\": false,\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"status\": true,\r\n"
				+ "    \"providerImage\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/pss-adapter-modulator/24293/book/C20178B6-BE4A-4176-B7FD-B6901C38A051/image\",\r\n"
				+ "    \"specialty\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"isgenderRule\": false,\r\n"
				+ "        \"id\": 203767,\r\n"
				+ "        \"name\": \"abc's\",\r\n"
				+ "        \"displayName\": \"abc's\",\r\n"
				+ "        \"ageRule\": \"\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"location\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"appointmentType\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 205754,\r\n"
				+ "        \"name\": \"Covid-19\",\r\n"
				+ "        \"displayName\": \"Covid-19\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"8F563A6C-7098-4446-97E2-7EF9345ED469\",\r\n"
				+ "        \"categoryName\": \"Covid-19\",\r\n"
				+ "        \"extAppointmentTypeId\": \"86D0E00F-C136-4A24-BF7A-6C17E9AB35ED\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 209164,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \""+catId+"\",\r\n"
				+ "        \"categoryName\": \"Aapt Category1\",\r\n"
				+ "        \"extAppointmentTypeId\": \""+appExtId+"\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 4237,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"24A7DC4F-4DB6-427C-9FA5-EB76FA2142D0\",\r\n"
				+ "        \"categoryName\": \"Insomnia\",\r\n"
				+ "        \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"sortOrder\": 25,\r\n"
				+ "    \"acceptComment\": "+lastQueEnable+",\r\n"
				+ "    \"acceptNew\": false,\r\n"
				+ "    \"categoryId\": \"185541C1-D44B-4D12-AA7E-F25A7B0F4A7D\",\r\n"
				+ "    \"categoryName\": \"Ng3 Pss [PSS,NG3]\",\r\n"
				+ "    \"bookType\": {\r\n"
				+ "      \"name\": \"PERSON\",\r\n"
				+ "      \"code\": \"RS_PERSON\",\r\n"
				+ "      \"grouptype\": \"RESOURCE\"\r\n"
				+ "    },\r\n"
				+ "    \"bookLevel\": {\r\n"
				+ "      \"name\": \"None\",\r\n"
				+ "      \"code\": \"RS_NONE\",\r\n"
				+ "      \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "    },\r\n"
				+ "    \"careteam\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 4060,\r\n"
				+ "        \"name\": \"ct\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"providerlinks\": {\r\n"
				+ "      \"baseurl\": \"https://dev3-pss.dev.medfusion.net/psspatient/login\",\r\n"
				+ "      \"links\": [\r\n"
				+ "        {\r\n"
				+ "          \"id\": 0,\r\n"
				+ "          \"type\": \"ANONYMOUS\",\r\n"
				+ "          \"guid\": \"9515140d-fc88-49eb-b1a3-8895a6eaf2b0\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"id\": 0,\r\n"
				+ "          \"type\": \"LOGINLESS\",\r\n"
				+ "          \"guid\": \"72d3c86c-8689-4a95-9414-d0b7149b8f2a\"\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "]";
		return bookPayload;
	}

	public String genderMap(String dispName,String Code,String partnerCode,int seq)
	{
		String gendeMap="[\r\n"
				+ "  {\r\n"
				+ "    \"id\": 0,\r\n"
				+ "    \"displayName\": \""+dispName+"\",\r\n"
				+ "    \"pssCode\": \""+Code+"\",\r\n"
				+ "    \"partnerCode\": \""+partnerCode+"\",\r\n"
				+ "    \"active\": true,\r\n"
				+ "    \"seq\": "+seq+",\r\n"
				+ "    \"codeGroup\": \"gender\"\r\n"
				+ "  }\r\n"
				+ "]";
		return gendeMap;
	}
	public String genderRuleSpeciality()
	{
		String gendeMap="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"isgenderRule\": true,\r\n"
				+ "    \"id\": 201250,\r\n"
				+ "    \"name\": \"Internal Medicine\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Internal Medicine\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \"Internal Medicine\",\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"genderRule\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Male\",\r\n"
				+ "        \"pssCode\": \"M\",\r\n"
				+ "        \"partnerCode\": \"M\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 1,\r\n"
				+ "        \"codeGroup\": \"gender\",\r\n"
				+ "        \"selected\": true\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Female\",\r\n"
				+ "        \"pssCode\": \"F\",\r\n"
				+ "        \"partnerCode\": \"F\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 2,\r\n"
				+ "        \"codeGroup\": \"gender\",\r\n"
				+ "        \"selected\": true\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return gendeMap;
	}
	
	public String resetGenderRuleSpeciality()
	{
		String gendeMap="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"isgenderRule\": false,\r\n"
				+ "    \"id\": 201250,\r\n"
				+ "    \"name\": \"Internal Medicine\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Internal Medicine\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \"Internal Medicine\",\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"genderRule\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Male\",\r\n"
				+ "        \"pssCode\": \"M\",\r\n"
				+ "        \"partnerCode\": \"M\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 1,\r\n"
				+ "        \"codeGroup\": \"gender\",\r\n"
				+ "        \"selected\": false\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": 0,\r\n"
				+ "        \"displayName\": \"Female\",\r\n"
				+ "        \"pssCode\": \"F\",\r\n"
				+ "        \"partnerCode\": \"F\",\r\n"
				+ "        \"active\": true,\r\n"
				+ "        \"seq\": 2,\r\n"
				+ "        \"codeGroup\": \"gender\",\r\n"
				+ "        \"selected\": false\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return gendeMap;
	}
	
	
	public String preventBackToBackPyaload(boolean backToBack,int confirmId )
	{
		String preventBackToBackPyaload="{\r\n"
				+ "  \"id\": "+confirmId+",\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": "+backToBack+",\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return preventBackToBackPyaload;
	}
	
	public String preventSchedulePyaload(int appId,int preventSchedulingDays,String name,String dispName,String extId,String catId)
	{
		String preventSchedulePyaload="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": "+appId+",\r\n"
				+ "    \"name\": \""+name+"\",\r\n"
				+ "    \"displayName\": \""+dispName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": \"This is confirmation message\",\r\n"
				+ "      \"ES\": \"This is confirmation message\"\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"categoryId\": \""+catId+"\",\r\n"
				+ "    \"categoryName\": \"Insomnia\",\r\n"
				+ "    \"extAppointmentTypeId\": \""+extId+"\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": "+preventSchedulingDays+",\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4054,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": true,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 0,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return preventSchedulePyaload;
	}
	
	public String lockoutBillingNotesPayload()
	{
		String lockoutPayload="{\r\n"
				+ "    \"group\": \"LOCKOUT\",\r\n"
				+ "    \"messages\": {\r\n"
				+ "        \"EN\": \"Billing Notes EN \",\r\n"
				+ "        \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"type\": \"BILLING_NOTES\",\r\n"
				+ "    \"value\": \"KK\",\r\n"
				+ "    \"key\": \"KK\"\r\n"
				+ "}";
		return lockoutPayload;
	}
	
	public String lockoutPatientNotesPayload()
	{
		String lockoutPayload="{\r\n"
				+ "    \"group\": \"ALERTS\",\r\n"
				+ "    \"messages\": {\r\n"
				+ "        \"EN\": \"Patient Notes - English\",\r\n"
				+ "        \"ES\": \"Patient Notes - Spanish\"\r\n"
				+ "    },\r\n"
				+ "    \"type\": \"NOTES\",\r\n"
				+ "    \"value\": \"KK\",\r\n"
				+ "    \"key\": \"KK\"\r\n"
				+ "}";
		return lockoutPayload;
	}
	
	public String overBookingPayload(boolean stackingValue,int confirmId)
	{
		String overBookingPayload="{\r\n"
				+ "  \"id\": "+confirmId+",\r\n"
				+ "  \"appointmentStacking\": "+stackingValue+",\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": false,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return overBookingPayload;
	}
	
	public String providerImages(boolean ShowProviderImages)
	{
		String providerImages="[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MF_SERVICES\",\r\n"
				+ "    \"key\": \"ShowProviderImages\",\r\n"
				+ "    \"value\": "+ShowProviderImages+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"PrimaryCareProvider\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"displayLastSeenProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"lastSeenProviderMonths\",\r\n"
				+ "    \"value\": \"5\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeam\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeamDuration\",\r\n"
				+ "    \"value\": \"7\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"pcpAvailabilityDuration\",\r\n"
				+ "    \"value\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"rcp\",\r\n"
				+ "    \"value\": \"false\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"pcp\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  }\r\n"
				+ "]";
		return providerImages;
	}
	
	public String ageRuleOnBookAppointmentType(int bookId,int apptId,String firstValue,String secondValue,int bookConfigId)
	{
		String ageRuleBookAppType="{\r\n"
				+ "  \"isageRule\": true,\r\n"
				+ "  \"id\": "+bookConfigId+",\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": "+bookId+",\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": "+apptId+",\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"> "+firstValue+" And < "+secondValue+"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"205604\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"pss wla\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 205504,\r\n"
				+ "        \"address1\": \"5501\",\r\n"
				+ "        \"address2\": \"Dillard Dr\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"North Carolina\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"latitude\": 35.7531299,\r\n"
				+ "        \"longitude\": -78.73247119999999,\r\n"
				+ "        \"locAddress\": \"5501 Dillard Dr Cary North Carolina 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": true,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": true\r\n"
				+ "}";
		return ageRuleBookAppType;
	}
	
	public String resetAgeRuleOnBookAppointmentType(int bookId,int apptId )
	{
		String ageRuleBookAppType="{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212088,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4310,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209179,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"205604\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"pss wla\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 205504,\r\n"
				+ "        \"address1\": \"5501\",\r\n"
				+ "        \"address2\": \"Dillard Dr\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"North Carolina\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"latitude\": 35.7531299,\r\n"
				+ "        \"longitude\": -78.73247119999999,\r\n"
				+ "        \"locAddress\": \"5501 Dillard Dr Cary North Carolina 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": true,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": true\r\n"
				+ "}";
		return ageRuleBookAppType;
	}
	
	public String createDecisionTree()
	{
		
		String createDecisionTree="[\r\n"
				+ "  {\r\n"
				+ "    \"id\": 210200,\r\n"
				+ "    \"name\": \"NewCat\",\r\n"
				+ "    \"type\": \"CG_APPOINTMENT_TYPE\",\r\n"
				+ "    \"nodes\": [\r\n"
				+ "      {\r\n"
				+ "        \"guid\": 210200,\r\n"
				+ "        \"type\": \"CATEGORY\",\r\n"
				+ "        \"displayName\": \"NewCat\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"NewCat\",\r\n"
				+ "          \"ES\": \"NewCat\"\r\n"
				+ "        },\r\n"
				+ "        \"entity\": null,\r\n"
				+ "        \"children\": [\r\n"
				+ "          \"747ff512-133a-4c8e-9dfc-c59a85bde07a\"\r\n"
				+ "        ]\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"guid\": \"747ff512-133a-4c8e-9dfc-c59a85bde07a\",\r\n"
				+ "        \"type\": \"QUESTION\",\r\n"
				+ "        \"displayName\": \"[QUESTION0]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Tester\",\r\n"
				+ "          \"ES\": \"[QUESTION0]\"\r\n"
				+ "        },\r\n"
				+ "        \"parentId\": 210200,\r\n"
				+ "        \"entity\": null,\r\n"
				+ "        \"children\": [\r\n"
				+ "          \"1d5411ce-68a9-4aaa-8db1-c1d22870f489\",\r\n"
				+ "          \"5e75ce3c-e630-4c1f-8486-c65219921c3e\"\r\n"
				+ "        ]\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"guid\": \"1d5411ce-68a9-4aaa-8db1-c1d22870f489\",\r\n"
				+ "        \"type\": \"ANSWER\",\r\n"
				+ "        \"displayName\": \"[ANSWER0]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Selenium\",\r\n"
				+ "          \"ES\": \"[ANSWER0]\"\r\n"
				+ "        },\r\n"
				+ "        \"parentId\": \"747ff512-133a-4c8e-9dfc-c59a85bde07a\",\r\n"
				+ "        \"entity\": {\r\n"
				+ "          \"type\": \"appointment_type\",\r\n"
				+ "          \"id\": 209179,\r\n"
				+ "          \"name\": \"Insomnia\",\r\n"
				+ "          \"categoryId\": \"73D35CC3-EACA-447C-B728-17BD077D3FD5\",\r\n"
				+ "          \"categoryName\": \"Insomnia\",\r\n"
				+ "          \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\"\r\n"
				+ "        },\r\n"
				+ "        \"children\": []\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"guid\": \"5e75ce3c-e630-4c1f-8486-c65219921c3e\",\r\n"
				+ "        \"type\": \"ANSWER\",\r\n"
				+ "        \"displayName\": \"[ANSWER1]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Manual\",\r\n"
				+ "          \"ES\": \"[ANSWER1]\"\r\n"
				+ "        },\r\n"
				+ "        \"parentId\": \"747ff512-133a-4c8e-9dfc-c59a85bde07a\",\r\n"
				+ "        \"entity\": {\r\n"
				+ "          \"type\": \"appointment_type\",\r\n"
				+ "          \"id\": 209179,\r\n"
				+ "          \"name\": \"Insomnia\",\r\n"
				+ "          \"categoryId\": \"73D35CC3-EACA-447C-B728-17BD077D3FD5\",\r\n"
				+ "          \"categoryName\": \"Insomnia\",\r\n"
				+ "          \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\"\r\n"
				+ "        },\r\n"
				+ "        \"children\": []\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"displayName\": \"NewCat\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"NewCat\",\r\n"
				+ "      \"ES\": \"NewCat\"\r\n"
				+ "    },\r\n"
				+ "    \"status\": \"PUBLISHED\"\r\n"
				+ "  }\r\n"
				+ "]";
		return createDecisionTree;
		
	}
	
	public String bookAppointmentTypePatientType(int bookId,int apptId,String patientType,int configId)
	{
		String bookAppointmentTypePatientType="{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": "+configId+",\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": "+bookId+",\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": "+apptId+",\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"205604\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"pss wla\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 205504,\r\n"
				+ "        \"address1\": \"5501\",\r\n"
				+ "        \"address2\": \"Dillard Dr\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"North Carolina\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"latitude\": 35.7531299,\r\n"
				+ "        \"longitude\": -78.73247119999999,\r\n"
				+ "        \"locAddress\": \"5501 Dillard Dr Cary North Carolina 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": true,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \""+patientType+"\",\r\n"
				+ "  \"lastQuestRequired\": true\r\n"
				+ "}";
		return bookAppointmentTypePatientType;
	}
	
	
	public String appTypeDuration()
	{
		String payload="{\r\n"
				+ "  \"id\": 4048,\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 30,\r\n"
				+ "  \"pttype\": \"PT_EXISTING\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}
	
	public String resetAppTypeDuration()
	{
		String payload="{\r\n"
				+ "  \"id\": 4048,\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \"PT_EXISTING\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}
	
	public String ageRuleAppType(int apptId,String firstValue,String secondValue)
	{
		String payload="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": true,\r\n"
				+ "    \"id\": "+apptId+",\r\n"
				+ "    \"name\": \"Insomnia\",\r\n"
				+ "    \"displayName\": \"Insomnia\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": \"This is confirmation message\",\r\n"
				+ "      \"ES\": \"This is confirmation message\"\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"categoryId\": \"24A7DC4F-4DB6-427C-9FA5-EB76FA2142D0\",\r\n"
				+ "    \"categoryName\": \"Insomnia\",\r\n"
				+ "    \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4054,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": false,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 0,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"> "+firstValue+" And < "+secondValue+"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	
	public String resetAgeRuleAppType()
	{
		String payload="[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 4237,\r\n"
				+ "    \"name\": \"Insomnia\",\r\n"
				+ "    \"displayName\": \"Insomnia\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": \"This is confirmation message\",\r\n"
				+ "      \"ES\": \"This is confirmation message\"\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"categoryId\": \"24A7DC4F-4DB6-427C-9FA5-EB76FA2142D0\",\r\n"
				+ "    \"categoryName\": \"Insomnia\",\r\n"
				+ "    \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4054,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": false,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 0,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
	    return payload;
	}
	
	public String patientTypeShowProviderOFF(String patientType,int apptConfigId) {
		String payload = "{\r\n"
				+ "  \"id\": "+apptConfigId+",\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": false,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"pttype\": \""+patientType+"\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}
	
	public String ageRuleAppTypeLevel(String fValue,String lValue,int apptId,String apptName,String catId) {
		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": true,\r\n"
				+ "    \"id\": "+apptId+",\r\n"
				+ "    \"name\": \"Insomnia\",\r\n"
				+ "    \"displayName\": \""+apptName+"\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\",\r\n"
				+ "      \"ES\": \"\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null,\r\n"
				+ "      \"ES\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": \"This is confirmation message\",\r\n"
				+ "      \"ES\": \"This is confirmation message\"\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 0,\r\n"
				+ "    \"categoryId\": \""+catId+"\",\r\n"
				+ "    \"categoryName\": \"Insomnia\",\r\n"
				+ "    \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"205604\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"pss wla\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 205504,\r\n"
				+ "          \"address1\": \"5501\",\r\n"
				+ "          \"address2\": \"Dillard Dr\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"North Carolina\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"latitude\": 35.7531299,\r\n"
				+ "          \"longitude\": -78.73247119999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": true,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4054,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": false,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 0,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"> "+fValue+" And < "+lValue+"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	
	public String careTeamSettingPyaload(int a,int b)
	{
		String payload="[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MF_SERVICES\",\r\n"
				+ "    \"key\": \"ShowProviderImages\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"PrimaryCareProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"displayLastSeenProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"lastSeenProviderMonths\",\r\n"
				+ "    \"value\": \"5\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeam\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeamDuration\",\r\n"
				+ "    \"value\": "+a+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"pcpAvailabilityDuration\",\r\n"
				+ "    \"value\": "+b+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"rcp\",\r\n"
				+ "    \"value\": \"false\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"pcp\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
		
	}
	
	public String updateBusinessHoursNG(String startTime,String endTime,String practiceId,String practiceName,String timeZone,String logo)
	{
		String updateBusinessHours="{\r\n"
				+ "  \"id\": "+practiceId+",\r\n"
				+ "  \"name\": \""+practiceName+"\",\r\n"
				+ "  \"practiceId\": \""+practiceId+"\",\r\n"
				+ "  \"themeColor\": \"#235ba8\",\r\n"
				+ "  \"extPracticeId\": \""+practiceId+"\",\r\n"
				+ "  \"partner\": \"NG\",\r\n"
				+ "  \"timezone\": \""+timeZone+"\",\r\n"
				+ "  \"active\": true,\r\n"
				+ "  \"languages\": [\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"EN\",\r\n"
				+ "      \"flag\": \"us\",\r\n"
				+ "      \"name\": \"English\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"ES\",\r\n"
				+ "      \"flag\": \"mx\",\r\n"
				+ "      \"name\": \"Español\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"starttime\": \""+startTime+"\",\r\n"
				+ "  \"endtime\": \""+endTime+"\",\r\n"
				+ "  \"logo\": \""+logo+"\",\r\n"
				+ "  \"type\": null\r\n"
				+ "}";
		return updateBusinessHours;
	}
	
	public String updateBusinessHoursGW(String startTime,String endTime,String extPracticeId,String practiceId,String practiceName,String timeZone,String logo)
	{
		String updateBusinessHours="{\r\n"
				+ "  \"id\": "+practiceId+",\r\n"
				+ "  \"name\": \"   "+practiceName+"\",\r\n"
				+ "  \"practiceId\": \""+practiceId+"\",\r\n"
				+ "  \"themeColor\": \"#7b3333\",\r\n"
				+ "  \"extPracticeId\": \""+extPracticeId+"\",\r\n"
				+ "  \"partner\": \"GW\",\r\n"
				+ "  \"timezone\": \""+timeZone+"\",\r\n"
				+ "  \"active\": true,\r\n"
				+ "  \"languages\": [\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"EN\",\r\n"
				+ "      \"flag\": \"us\",\r\n"
				+ "      \"name\": \"English\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"ES\",\r\n"
				+ "      \"flag\": \"mx\",\r\n"
				+ "      \"name\": \"Español\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"starttime\": \""+startTime+"\",\r\n"
				+ "  \"endtime\": \""+endTime+"\",\r\n"
				+ "  \"logo\": \""+logo+"\",\r\n"
				+ "  \"type\": null\r\n"
				+ "}";
		return updateBusinessHours;
	}

	public String updateBusinessHoursAT(String startTime,String endTime,String practiceId,String practiceName,String timeZone,String logo)
	{
		String updateBusinessHours="{\r\n"
				+ "  \"id\": "+practiceId+",\r\n"
				+ "  \"name\": \""+practiceName+"\",\r\n"
				+ "  \"practiceId\": \""+practiceId+"\",\r\n"
				+ "  \"themeColor\": \"#4caf50\",\r\n"
				+ "  \"extPracticeId\": \""+practiceId+"\",\r\n"
				+ "  \"partner\": \"ATHENA\",\r\n"
				+ "  \"timezone\": \""+timeZone+"\",\r\n"
				+ "  \"active\": true,\r\n"
				+ "  \"languages\": [\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"EN\",\r\n"
				+ "      \"flag\": \"us\",\r\n"
				+ "      \"name\": \"English\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"ES\",\r\n"
				+ "      \"flag\": \"mx\",\r\n"
				+ "      \"name\": \"Español\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"starttime\": \""+startTime+"\",\r\n"
				+ "  \"endtime\": \""+endTime+"\",\r\n"
				+ "  \"logo\": \""+logo+"\",\r\n"
				+ "  \"type\": null\r\n"
				+ "}";
		return updateBusinessHours;
	}
}

