// Copyright 2021 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.pss2patientapi.payload;

public class PayloadPMNGFeature01 {
	
	
	public String ssoSchedulewithDectree()
	{
		String ssoPost="{\r\n"
				+ "  \"patientType\": \"PT_NEW\",\r\n"
				+ "  \"slotId\": \"0001\",\r\n"
				+ "  \"specialty\": null,\r\n"
				+ "  \"book\": null,\r\n"
				+ "  \"appointmentType\": 4237,\r\n"
				+ "  \"location\": 201251,\r\n"
				+ "  \"startDateTime\": \"11/21/2021 13:10:00\",\r\n"
				+ "  \"customQuestion\": null,\r\n"
				+ "  \"insuranceInfo\": null,\r\n"
				+ "  \"patientInfo\": {},\r\n"
				+ "  \"allowDuplicatePatient\": true,\r\n"
				+ "  \"flow\": \"sso\",\r\n"
				+ "  \"appTypeDetail\": {\r\n"
				+ "    \"categoryId\": \"200857\",\r\n"
				+ "    \"guid\": \"68fc2ad8-4a85-48b3-a33e-d3fb279b99b1\",\r\n"
				+ "    \"appTypeId\": \"4130\"\r\n"
				+ "  },\r\n"
				+ "  \"rule\": \"T,L\",\r\n"
				+ "  \"leafNode\": \"Inso reason\"\r\n"
				+ "}";
		return ssoPost;
		
	}
	
	public String ssoSchedulewithDectree1()
	{
		String ssoPost="{\r\n"
				+ "  \"patientType\": \"PT_EXISTING\",\r\n"
				+ "  \"slotId\": \"0001\",\r\n"
				+ "  \"specialty\": null,\r\n"
				+ "  \"book\": 4309,\r\n"
				+ "  \"appointmentType\": 4237,\r\n"
				+ "  \"location\": 205604,\r\n"
				+ "  \"startDateTime\": \"01/03/2022 07:35:00\",\r\n"
				+ "  \"customQuestion\": null,\r\n"
				+ "  \"insuranceInfo\": null,\r\n"
				+ "  \"patientInfo\": {},\r\n"
				+ "  \"allowDuplicatePatient\": false,\r\n"
				+ "  \"updatePatientDetails\": {\r\n"
				+ "    \"FN\": \"anong\",\r\n"
				+ "    \"LN\": \"anong\",\r\n"
				+ "    \"DOB\": \"01/01/2000\",\r\n"
				+ "    \"GENDER\": \"M\",\r\n"
				+ "    \"EMAIL\": null,\r\n"
				+ "    \"PHONE\": null,\r\n"
				+ "    \"INSID\": null,\r\n"
				+ "    \"ADDR1\": null,\r\n"
				+ "    \"ADDR2\": null,\r\n"
				+ "    \"CITY\": null,\r\n"
				+ "    \"STATE\": null,\r\n"
				+ "    \"ZIP\": null\r\n"
				+ "  },\r\n"
				+ "  \"flow\": \"loginless\",\r\n"
				+ "  \"appTypeDetail\": {\r\n"
				+ "    \"categoryId\": \"205277\",\r\n"
				+ "    \"guid\": \"3d4a9022-0cd8-4112-b7f2-e2566ada9640\",\r\n"
				+ "    \"appTypeId\": \"4237\"\r\n"
				+ "  },\r\n"
				+ "  \"rule\": \"L,T,B\",\r\n"
				+ "  \"leafNode\": \"Inso reason\"\r\n"
				+ "}";
		return ssoPost;
		
	}

	public String ssoPostwithoutDecTree()
	{
		String ssoPostwithoutDecTree="{\r\n"
				+ "    \"apptToSchedule\": {\r\n"
				+ "        \"patientType\": \"PT_NEW\",\r\n"
				+ "        \"slotId\": \"0001\",\r\n"
				+ "        \"specialty\": null,\r\n"
				+ "        \"book\": null,\r\n"
				+ "        \"appointmentType\": 4130,\r\n"
				+ "        \"location\": 201251,\r\n"
				+ "        \"startDateTime\": \"11/21/2021 14:20:00\",\r\n"
				+ "        \"customQuestion\": null,\r\n"
				+ "        \"insuranceInfo\": null,\r\n"
				+ "        \"patientInfo\": {},\r\n"
				+ "        \"allowDuplicatePatient\": true,\r\n"
				+ "        \"flow\": \"sso\",\r\n"
				+ "        \"appTypeDetail\": null,\r\n"
				+ "        \"rule\": \"T,L\",\r\n"
				+ "        \"leafNode\": null\r\n"
				+ "    },\r\n"
				+ "    \"apptToReschedule\": {\r\n"
				+ "        \"appointmentId\": \"211054\",\r\n"
				+ "        \"cancellationMap\": {\r\n"
				+ "            \"id\": null,\r\n"
				+ "            \"name\": \"test\"\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "}";
		return ssoPostwithoutDecTree;
		
	}		
	public String ssoPostwithoutDecTreeShowProviderOFF()
	{
		String ssoPostwithoutDecTreeShowProviderOFF="{\r\n"
				+ "    \"patientType\": \"PT_NEW\",\r\n"
				+ "    \"slotId\": \"0001\",\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"book\": null,\r\n"
				+ "    \"appointmentType\": 4130,\r\n"
				+ "    \"location\": 201251,\r\n"
				+ "    \"startDateTime\": \"11/21/2021 14:30:00\",\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"insuranceInfo\": null,\r\n"
				+ "    \"patientInfo\": {},\r\n"
				+ "    \"allowDuplicatePatient\": true,\r\n"
				+ "    \"flow\": \"sso\",\r\n"
				+ "    \"appTypeDetail\": null,\r\n"
				+ "    \"rule\": \"T,L\",\r\n"
				+ "    \"leafNode\": null\r\n"
				+ "},\r\n"
				+ "\"apptToReschedule\": {\r\n"
				+ "    \"appointmentId\": \"211058\",\r\n"
				+ "    \"cancellationMap\": {\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"name\": \"test\"\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "}";
		return ssoPostwithoutDecTreeShowProviderOFF;
		
	}
	public String ssoPostwithDecTreeShowProviderOFF()
	{
		String ssoPostwithDecTreeShowProviderOFF="{\r\n"
				+ "    \"apptToSchedule\": {\r\n"
				+ "        \"patientType\": \"PT_NEW\",\r\n"
				+ "        \"slotId\": \"0001\",\r\n"
				+ "        \"specialty\": null,\r\n"
				+ "        \"book\": null,\r\n"
				+ "        \"appointmentType\": 4130,\r\n"
				+ "        \"location\": 201251,\r\n"
				+ "        \"startDateTime\": \"11/21/2021 14:10:00\",\r\n"
				+ "        \"customQuestion\": null,\r\n"
				+ "        \"insuranceInfo\": null,\r\n"
				+ "        \"patientInfo\": {},\r\n"
				+ "        \"allowDuplicatePatient\": true,\r\n"
				+ "        \"flow\": \"sso\",\r\n"
				+ "        \"appTypeDetail\": {\r\n"
				+ "            \"categoryId\": \"200857\",\r\n"
				+ "            \"guid\": \"68fc2ad8-4a85-48b3-a33e-d3fb279b99b1\",\r\n"
				+ "            \"appTypeId\": \"4130\"\r\n"
				+ "        },\r\n"
				+ "        \"rule\": \"T,L\",\r\n"
				+ "        \"leafNode\": \"Inso reason\"\r\n"
				+ "    },\r\n"
				+ "    \"apptToReschedule\": {\r\n"
				+ "        \"appointmentId\": \"211060\",\r\n"
				+ "        \"cancellationMap\": {\r\n"
				+ "            \"id\": \"B02315FC-A614-40E2-8B96-CF5D7703A325\",\r\n"
				+ "            \"name\": \"No Referral / Authorization\"\r\n"
				+ "        }\r\n"
				+ "    }\r\n"
				+ "}";
		return ssoPostwithDecTreeShowProviderOFF;
		
	}
	public String avaliableSlot(String currentDate)
	{
		String avaliableSlot="{\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"location\": 206321,\r\n"
				+ "    \"book\": null,\r\n"
				+ "    \"appointmentType\": 206528,\r\n"
				+ "    \"startDateTime\": \""+currentDate+"\",\r\n"
				+ "    \"slotId\": null,\r\n"
				+ "    \"traversal\": false,\r\n"
				+ "    \"patientType\": \"PT_NEW\",\r\n"
				+ "    \"extApptId\": null\r\n"
				+ "}";
		return avaliableSlot;
		
	}
	
//	public String scheduleApp(String currentDate)
//	{
//		String scheduleApp="{\r\n"
//				+ "    \"patientType\": \"PT_ALL\",\r\n"
//				+ "    \"slotId\": \"0001\",\r\n"
//				+ "    \"specialty\": null,\r\n"
//				+ "    \"book\": 205662,\r\n"
//				+ "    \"appointmentType\": 205754,\r\n"
//				+ "    \"location\": 205604,\r\n"
//				+ "    \"startDateTime\": \""+currentDate+"\",\r\n"
//				+ "    \"customQuestion\": null,\r\n"
//				+ "    \"insuranceInfo\": null,\r\n"
//				+ "    \"patientInfo\": {},\r\n"
//				+ "    \"allowDuplicatePatient\": false,\r\n"
//				+ "    \"flow\": \"anonymous\",\r\n"
//				+ "    \"appTypeDetail\": null,\r\n"
//				+ "    \"rule\": \"L,T,B\",\r\n"
//				+ "    \"leafNode\": null\r\n"
//				+ "}";
//		return scheduleApp;
//		
//	}
	
//	public String scheduleAppForPTNEW(String currentDate)
//	{
//		String scheduleApp="{\r\n"
//				+ "    \"patientType\": \"PT_ALL\",\r\n"
//				+ "    \"slotId\": \"0001\",\r\n"
//				+ "    \"specialty\": null,\r\n"
//				+ "    \"book\": 205662,\r\n"
//				+ "    \"appointmentType\": 205754,\r\n"
//				+ "    \"location\": 205604,\r\n"
//				+ "    \"startDateTime\": \""+currentDate+"\",\r\n"
//				+ "    \"customQuestion\": null,\r\n"
//				+ "    \"insuranceInfo\": null,\r\n"
//				+ "    \"patientInfo\": {},\r\n"
//				+ "    \"allowDuplicatePatient\": false,\r\n"
//				+ "    \"flow\": \"anonymous\",\r\n"
//				+ "    \"appTypeDetail\": null,\r\n"
//				+ "    \"rule\": \"L,T,B\",\r\n"
//				+ "    \"leafNode\": null\r\n"
//				+ "}";
//		return scheduleApp;
//		
//	}
//public String schedulewithoutProvider()
//{
//	String schedulewithoutProvider="{\r\n"
//			+ "  \"patientType\": \"PT_EXISTING\",\r\n"
//			+ "  \"slotId\": \"0001\",\r\n"
//			+ "  \"specialty\": null,\r\n"
//			+ "  \"book\": null,\r\n"
//			+ "  \"appointmentType\": 4237,\r\n"
//			+ "  \"location\": 205604,\r\n"
//			+ "  \"startDateTime\": \"01/03/2022 09:10:00\",\r\n"
//			+ "  \"customQuestion\": null,\r\n"
//			+ "  \"insuranceInfo\": null,\r\n"
//			+ "  \"patientInfo\": {},\r\n"
//			+ "  \"allowDuplicatePatient\": false,\r\n"
//			+ "  \"updatePatientDetails\": {\r\n"
//			+ "    \"FN\": \"anong\",\r\n"
//			+ "    \"LN\": \"anong\",\r\n"
//			+ "    \"DOB\": \"01/01/2000\",\r\n"
//			+ "    \"GENDER\": \"M\",\r\n"
//			+ "    \"EMAIL\": null,\r\n"
//			+ "    \"PHONE\": null,\r\n"
//			+ "    \"INSID\": null,\r\n"
//			+ "    \"ADDR1\": null,\r\n"
//			+ "    \"ADDR2\": null,\r\n"
//			+ "    \"CITY\": null,\r\n"
//			+ "    \"STATE\": null,\r\n"
//			+ "    \"ZIP\": null\r\n"
//			+ "  },\r\n"
//			+ "  \"flow\": \"loginless\",\r\n"
//			+ "  \"appTypeDetail\": null,\r\n"
//			+ "  \"rule\": \"L,T\",\r\n"
//			+ "  \"leafNode\": null\r\n"
//			+ "}";
//	return schedulewithoutProvider;
//	
//}

public String  availableslotsPayloadLT(String date, String locationid, String apptid)
{
	String  availableSlots="{\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"book\": null,\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"slotId\": \"0001\",\r\n"
			+ "    \"traversal\": false,\r\n"
			+ "    \"patientType\": \"PT_NEW\",\r\n"
			+ "    \"extApptId\": null\r\n"
			+ "}";
	return availableSlots;
}

public String  availableslotsPayloadLTB(String date, String locationid, String apptid,String bookId)
{
	String  availableSlots="{\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"book\": "+bookId+",\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"slotId\": null,\r\n"
			+ "    \"traversal\": false,\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"extApptId\": null\r\n"
			+ "}";
	return availableSlots;
}


public String  anoscheduleAppointmentPayloadWithDecTreeLT(String slotid, String date,String slottime,String locationid, String apptid)
{   
	String  scheduleAppointment="{\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": null,\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {},\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": {\r\n"
			+ "        \"categoryId\": \"210138\",\r\n"
			+ "        \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "        \"appTypeId\": \"4237\"\r\n"
			+ "    },\r\n"
			+ "    \"rule\": \"L,T\",\r\n"
			+ "    \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  anoscheduleAppointmentPayloadWithoutDecTreeLT(String slotid, String date,String slottime,String locationid, String apptid)
{   
	String  scheduleAppointment="{\r\n"
			+ "  \"patientType\": \"PT_ALL\",\r\n"
			+ "  \"slotId\": \""+slotid+"\",\r\n"
			+ "  \"specialty\": null,\r\n"
			+ "  \"book\": null,\r\n"
			+ "  \"appointmentType\": "+apptid+",\r\n"
			+ "  \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "  \"customQuestion\": null,\r\n"
			+ "  \"insuranceInfo\": null,\r\n"
			+ "  \"patientInfo\": {},\r\n"
			+ "  \"allowDuplicatePatient\": false,\r\n"
			+ "  \"flow\": \"anonymous\",\r\n"
			+ "  \"appTypeDetail\": null,\r\n"
			+ "  \"rule\": \"L,T\",\r\n"
			+ "  \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  anoScheduleAppointmentPayloadLTBWithDecTree(String slotid, String date,String slottime,String locationid, String apptid,String bookId)
{   
	String  scheduleAppointment="{\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": "+bookId+",\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {},\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": {\r\n"
			+ "        \"categoryId\": \"210138\",\r\n"
			+ "        \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "        \"appTypeId\": \"4237\"\r\n"
			+ "    },\r\n"
			+ "    \"rule\": \"L,T,B\",\r\n"
			+ "    \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  anoScheduleAppointmentPayloadLTBWithoutDecTree(String slotid, String date,String slottime,String locationid, String apptid,String bookId)
{   
	String  scheduleAppointment="{\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": "+bookId+",\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {},\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": null,\r\n"
			+ "    \"rule\": \"L,T,B\",\r\n"
			+ "    \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  llScheduleAppointmentPayloadLTBWithoutDecTree(String slotid, String date,String slottime,String locationid, String apptid,String bookId)
{   
	String  scheduleAppointment="{\r\n"
			+ "  \"patientType\": \"PT_NEW\",\r\n"
			+ "  \"slotId\": \""+slotid+"\",\r\n"
			+ "  \"specialty\": null,\r\n"
			+ "  \"book\": "+bookId+",\r\n"
			+ "  \"appointmentType\": "+apptid+",\r\n"
			+ "  \"location\": "+locationid+",\r\n"
			+ "  \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "  \"customQuestion\": null,\r\n"
			+ "  \"insuranceInfo\": null,\r\n"
			+ "  \"patientInfo\": {},\r\n"
			+ "  \"allowDuplicatePatient\": false,\r\n"
			+ "  \"updatePatientDetails\": {\r\n"
			+ "    \"FN\": \"ngpm\",\r\n"
			+ "    \"LN\": \"patient\",\r\n"
			+ "    \"DOB\": \"01/01/2000\",\r\n"
			+ "    \"GENDER\": \"M\",\r\n"
			+ "    \"EMAIL\": null,\r\n"
			+ "    \"PHONE\": null,\r\n"
			+ "    \"INSID\": null,\r\n"
			+ "    \"ADDR1\": null,\r\n"
			+ "    \"ADDR2\": null,\r\n"
			+ "    \"CITY\": null,\r\n"
			+ "    \"STATE\": null,\r\n"
			+ "    \"ZIP\": null\r\n"
			+ "  },\r\n"
			+ "  \"flow\": \"loginless\",\r\n"
			+ "  \"appTypeDetail\": null,\r\n"
			+ "  \"rule\": \"L,T,B\",\r\n"
			+ "  \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  llScheduleAppointmentPayloadLTBWithDecTree(String slotid, String date,String slottime,String locationid, String apptid,String bookId)
{   
	String  scheduleAppointment="{\r\n"
			+ "  \"patientType\": \"PT_NEW\",\r\n"
			+ "  \"slotId\": \""+slotid+"\",\r\n"
			+ "  \"specialty\": null,\r\n"
			+ "  \"book\": "+bookId+",\r\n"
			+ "  \"appointmentType\": "+apptid+",\r\n"
			+ "  \"location\": "+locationid+",\r\n"
			+ "  \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "  \"customQuestion\": null,\r\n"
			+ "  \"insuranceInfo\": null,\r\n"
			+ "  \"patientInfo\": {},\r\n"
			+ "  \"allowDuplicatePatient\": false,\r\n"
			+ "  \"updatePatientDetails\": {\r\n"
			+ "    \"FN\": \"ngpm\",\r\n"
			+ "    \"LN\": \"patient\",\r\n"
			+ "    \"DOB\": \"01/01/2000\",\r\n"
			+ "    \"GENDER\": \"M\",\r\n"
			+ "    \"EMAIL\": null,\r\n"
			+ "    \"PHONE\": null,\r\n"
			+ "    \"INSID\": null,\r\n"
			+ "    \"ADDR1\": null,\r\n"
			+ "    \"ADDR2\": null,\r\n"
			+ "    \"CITY\": null,\r\n"
			+ "    \"STATE\": null,\r\n"
			+ "    \"ZIP\": null\r\n"
			+ "  },\r\n"
			+ "  \"flow\": \"loginless\",\r\n"
			+ "  \"appTypeDetail\": {\r\n"
			+ "    \"categoryId\": \"210138\",\r\n"
			+ "    \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "    \"appTypeId\": \"4237\"\r\n"
			+ "  },\r\n"
			+ "  \"rule\": \"L,T,B\",\r\n"
			+ "  \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  llScheduleAppointmentPayloadLTWithDecTree(String slotid, String date,String slottime,String locationid, String apptid)
{   
	String  scheduleAppointment="{\r\n"
			+ "  \"patientType\": \"PT_NEW\",\r\n"
			+ "  \"slotId\": \""+slotid+"\",\r\n"
			+ "  \"specialty\": null,\r\n"
			+ "  \"book\": null,\r\n"
			+ "  \"appointmentType\": "+apptid+",\r\n"
			+ "  \"location\": "+locationid+",\r\n"
			+ "  \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "  \"customQuestion\": null,\r\n"
			+ "  \"insuranceInfo\": null,\r\n"
			+ "  \"patientInfo\": {},\r\n"
			+ "  \"allowDuplicatePatient\": false,\r\n"
			+ "  \"updatePatientDetails\": {\r\n"
			+ "    \"FN\": \"ngpm\",\r\n"
			+ "    \"LN\": \"patient\",\r\n"
			+ "    \"DOB\": \"01/01/2000\",\r\n"
			+ "    \"GENDER\": \"M\",\r\n"
			+ "    \"EMAIL\": null,\r\n"
			+ "    \"PHONE\": null,\r\n"
			+ "    \"INSID\": null,\r\n"
			+ "    \"ADDR1\": null,\r\n"
			+ "    \"ADDR2\": null,\r\n"
			+ "    \"CITY\": null,\r\n"
			+ "    \"STATE\": null,\r\n"
			+ "    \"ZIP\": null\r\n"
			+ "  },\r\n"
			+ "  \"flow\": \"loginless\",\r\n"
			+ "  \"appTypeDetail\": {\r\n"
			+ "    \"categoryId\": \"210138\",\r\n"
			+ "    \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "    \"appTypeId\": \"4237\"\r\n"
			+ "  },\r\n"
			+ "  \"rule\": \"L,T\",\r\n"
			+ "  \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String  llScheduleAppointmentPayloadLTWithoutDecTree(String slotid, String date,String slottime,String locationid, String apptid)
{   
	String  scheduleAppointment="{\r\n"
			+ "  \"patientType\": \"PT_NEW\",\r\n"
			+ "  \"slotId\": \""+slotid+"\",\r\n"
			+ "  \"specialty\": null,\r\n"
			+ "  \"book\": null,\r\n"
			+ "  \"appointmentType\": "+apptid+",\r\n"
			+ "  \"location\": "+locationid+",\r\n"
			+ "  \"startDateTime\": \""+date+" "+slottime+"\",\r\n"
			+ "  \"customQuestion\": null,\r\n"
			+ "  \"insuranceInfo\": null,\r\n"
			+ "  \"patientInfo\": {},\r\n"
			+ "  \"allowDuplicatePatient\": false,\r\n"
			+ "  \"updatePatientDetails\": {\r\n"
			+ "    \"FN\": \"ngpm\",\r\n"
			+ "    \"LN\": \"patient\",\r\n"
			+ "    \"DOB\": \"01/01/2000\",\r\n"
			+ "    \"GENDER\": \"M\",\r\n"
			+ "    \"EMAIL\": null,\r\n"
			+ "    \"PHONE\": null,\r\n"
			+ "    \"INSID\": null,\r\n"
			+ "    \"ADDR1\": null,\r\n"
			+ "    \"ADDR2\": null,\r\n"
			+ "    \"CITY\": null,\r\n"
			+ "    \"STATE\": null,\r\n"
			+ "    \"ZIP\": null\r\n"
			+ "  },\r\n"
			+ "  \"flow\": \"loginless\",\r\n"
			+ "  \"appTypeDetail\": null,\r\n"
			+ "  \"rule\": \"L,T\",\r\n"
			+ "  \"leafNode\": null\r\n"
			+ "}";
	return scheduleAppointment;
}

public String rescheduleWithCatLT(String slotid, String date,String confirmNo,String locationid, String apptid)
{
	String rescheduleWithCatLT="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_NEW\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": null,\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {},\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atulaa\",\r\n"
			+ "      \"GENDER\": \"M\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"loginless\",\r\n"
			+ "    \"appTypeDetail\": {\r\n"
			+ "      \"categoryId\": \"210138\",\r\n"
			+ "      \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "      \"appTypeId\": \"4237\"\r\n"
			+ "    },\r\n"
			+ "    \"rule\": \"L,T\",\r\n"
			+ "    \"leafNode\": \"[ANSWER1]\"\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": null,\r\n"
			+ "      \"name\": \"otherCancelReason\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return rescheduleWithCatLT;
	
}

public String rescheduleWithoutCatLT(String slotid, String date,String confirmNo,String locationid, String apptid)
{
	String rescheduleWithoutCatLT="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_NEW\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": null,\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {},\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atulaa\",\r\n"
			+ "      \"GENDER\": \"M\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"loginless\",\r\n"
			+ "    \"appTypeDetail\": null,\r\n"
			+ "    \"rule\": \"L,T\",\r\n"
			+ "    \"leafNode\": null\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": \"B02315FC-A614-40E2-8B96-CF5D7703A325\",\r\n"
			+ "      \"name\": \"No Referral / Authorization\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return rescheduleWithoutCatLT;
	
}

public String rescheduleWithCatLTB(String slotid, String date,String confirmNo,String locationid, String apptid,String bookid)
{
	String rescheduleWithCatLTB="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_NEW\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": "+bookid+",\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {},\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atulaa\",\r\n"
			+ "      \"GENDER\": \"M\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"loginless\",\r\n"
			+ "    \"appTypeDetail\": {\r\n"
			+ "      \"categoryId\": \"210138\",\r\n"
			+ "      \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "      \"appTypeId\": \"4237\"\r\n"
			+ "    },\r\n"
			+ "    \"rule\": \"L,T,B\",\r\n"
			+ "    \"leafNode\": \"[ANSWER1]\"\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": null,\r\n"
			+ "      \"name\": \"otherCancelReason\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return rescheduleWithCatLTB;
	
}

public String anoRescheduleWithCatLTB(String slotid, String date,String confirmNo,String locationid, String apptid,String bookid)
{
	String rescheduleWithCatLTB="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": "+bookid+",\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {\r\n"
			+ "      \"patientMatches\": [\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"first name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"FN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your first name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 1\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"last name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"LN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your last name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 2\r\n"
			+ "        }\r\n"
			+ "      ],\r\n"
			+ "      \"type\": \"ANONYMOUS\",\r\n"
			+ "      \"allowDuplicatePatient\": false\r\n"
			+ "    },\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atul\",\r\n"
			+ "      \"LN\": \"ano\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": {\r\n"
			+ "      \"categoryId\": \"210138\",\r\n"
			+ "      \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "      \"appTypeId\": \"4237\"\r\n"
			+ "    },\r\n"
			+ "    \"rule\": \"T,L,B\",\r\n"
			+ "    \"leafNode\": \"[ANSWER1]\"\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": null,\r\n"
			+ "      \"name\": \"otherCancelReason\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return rescheduleWithCatLTB;
	
}

public String anoRescheduleWithoutCatLTB(String slotid, String date,String confirmNo,String locationid, String apptid,String bookid)
{
	String rescheduleWithCatLTB="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": "+bookid+",\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {\r\n"
			+ "      \"patientMatches\": [\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"first name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"FN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your first name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 1\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"last name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"LN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your last name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 2\r\n"
			+ "        }\r\n"
			+ "      ],\r\n"
			+ "      \"type\": \"ANONYMOUS\",\r\n"
			+ "      \"allowDuplicatePatient\": false\r\n"
			+ "    },\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atul\",\r\n"
			+ "      \"LN\": \"ano11\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": null,\r\n"
			+ "    \"rule\": \"L,T,B\",\r\n"
			+ "    \"leafNode\": null\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": null,\r\n"
			+ "      \"name\": \"otherCancelReason\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return rescheduleWithCatLTB;
	
}

public String anoRescheduleWithCatLT(String slotid, String date,String confirmNo,String locationid, String apptid)
{
	String rescheduleWithCatLTB="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": null,\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {\r\n"
			+ "      \"patientMatches\": [\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"first name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"FN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your first name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 1\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"last name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"LN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your last name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 2\r\n"
			+ "        }\r\n"
			+ "      ],\r\n"
			+ "      \"type\": \"ANONYMOUS\",\r\n"
			+ "      \"allowDuplicatePatient\": false\r\n"
			+ "    },\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atul\",\r\n"
			+ "      \"LN\": \"ano11\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": {\r\n"
			+ "      \"categoryId\": \"210138\",\r\n"
			+ "      \"guid\": \"3dd1053e-70a6-46cf-aa70-8eb19c2e5e7c\",\r\n"
			+ "      \"appTypeId\": \"4237\"\r\n"
			+ "    },\r\n"
			+ "    \"rule\": \"L,T\",\r\n"
			+ "    \"leafNode\": \"[ANSWER1]\"\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": null,\r\n"
			+ "      \"name\": \"otherCancelReason\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return rescheduleWithCatLTB;
	
}
public String anoRescheduleWithoutCatLT(String slotid, String date,String confirmNo,String locationid, String apptid)
{
	String anoRescheduleWithoutCatLT="{\r\n"
			+ "  \"apptToSchedule\": {\r\n"
			+ "    \"patientType\": \"PT_ALL\",\r\n"
			+ "    \"slotId\": \""+slotid+"\",\r\n"
			+ "    \"specialty\": null,\r\n"
			+ "    \"book\": null,\r\n"
			+ "    \"appointmentType\": "+apptid+",\r\n"
			+ "    \"location\": "+locationid+",\r\n"
			+ "    \"startDateTime\": \""+date+"\",\r\n"
			+ "    \"customQuestion\": null,\r\n"
			+ "    \"insuranceInfo\": null,\r\n"
			+ "    \"patientInfo\": {\r\n"
			+ "      \"patientMatches\": [\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"first name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"FN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your first name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 1\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "          \"entity\": \"last name\",\r\n"
			+ "          \"isMandatory\": true,\r\n"
			+ "          \"code\": \"LN\",\r\n"
			+ "          \"value\": null,\r\n"
			+ "          \"selected\": true,\r\n"
			+ "          \"search\": true,\r\n"
			+ "          \"error\": \"\",\r\n"
			+ "          \"message\": \"Please enter your last name\",\r\n"
			+ "          \"regex\": \"^(?!\\\\s*$).+\",\r\n"
			+ "          \"type\": \"TEXT\",\r\n"
			+ "          \"key\": null,\r\n"
			+ "          \"seq\": 2\r\n"
			+ "        }\r\n"
			+ "      ],\r\n"
			+ "      \"type\": \"ANONYMOUS\",\r\n"
			+ "      \"allowDuplicatePatient\": false\r\n"
			+ "    },\r\n"
			+ "    \"allowDuplicatePatient\": false,\r\n"
			+ "    \"updatePatientDetails\": {\r\n"
			+ "      \"FN\": \"atul\",\r\n"
			+ "      \"LN\": \"ano11\"\r\n"
			+ "    },\r\n"
			+ "    \"flow\": \"anonymous\",\r\n"
			+ "    \"appTypeDetail\": null,\r\n"
			+ "    \"rule\": \"L,T\",\r\n"
			+ "    \"leafNode\": null\r\n"
			+ "  },\r\n"
			+ "  \"apptToReschedule\": {\r\n"
			+ "    \"appointmentId\": \""+confirmNo+"\",\r\n"
			+ "    \"cancellationMap\": {\r\n"
			+ "      \"id\": null,\r\n"
			+ "      \"name\": \"otherCancelReason\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
	return anoRescheduleWithoutCatLT;
	
}
}
