// Copyright 2022 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.pss2patientapi.payload;

public class PayloadAM02 {
	
	public String openTokenPayload(String practiceid,String authUser) {
		String openToken = "{\r\n"
		+ " \"practiceId\": \""+practiceid+"\",\r\n"
		+ " \"authUserId\": \""+authUser+"\"\r\n"
		+ "}";
		return openToken;
	}

		

	public String reserveForSameDay(String value) {			
			String reserveForSameDay = "{\r\n"
					+ " \"id\": 203099,\r\n"
					+ " \"appointmentStacking\": false,\r\n"
					+ " \"slotCount\": 1,\r\n"
					+ " \"allowSameDayAppts\": true,\r\n"
					+ " \"apptTimeMark\": 0,\r\n"
					+ " \"apptTypeAllocated\": true,\r\n"
					+ " \"isContiguous\": false,\r\n"
					+ " \"leadTime\": {\r\n"
					+ " \"days\": 0,\r\n"
					+ " \"hours\": \"0\",\r\n"
					+ " \"mins\": \"0\"\r\n"
					+ " },\r\n"
					+ " \"excludeSlots\": [],\r\n"
					+ " \"apptTypeReservedReason\": \""+value+"\",\r\n"
					+ " \"acceptComment\": false,\r\n"
					+ " \"allowOnlineCancellation\": true,\r\n"
					+ " \"slotSize\": 5,\r\n"
					+ " \"schedulingDuration\": 0,\r\n"
					+ " \"pttype\": \"PT_ALL\",\r\n"
					+ " \"lastQuestRequired\": false\r\n"
					+ "}";
					return reserveForSameDay;
	}
	
	public String timeMarkPayload(String timemark) {			
		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": \""+timemark+"\",\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206532\",\r\n"
				+ "      \"name\": \"PSS Cary\",\r\n"
				+ "      \"displayName\": \"PSS Cary\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206432,\r\n"
				+ "        \"address1\": \"\",\r\n"
				+ "        \"address2\": \"\",\r\n"
				+ "        \"city\": \"Test\",\r\n"
				+ "        \"state\": \"AL\",\r\n"
				+ "        \"zipCode\": \"555555555\",\r\n"
				+ "        \"latitude\": 0,\r\n"
				+ "        \"longitude\": 0,\r\n"
				+ "        \"locAddress\": \"  Test AL 555555555\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"1B595F99-278A-4956-8F04-1879B12FB43D\",\r\n"
				+ "      \"selected\": false,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
				return payload;
	}

	public String turnOFFShowProvider(boolean bool) {

		String turnOFFShowProvider = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"showProvider\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  }\r\n"
				+ "]";
		return turnOFFShowProvider;
	}	
	
	public String confgSaveAdmin(String key,boolean bool) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \""+key+"\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
						

	public String timeMark() {
			
	String timeMark = "{\r\n"
					+ " \"id\": 201750,\r\n"
					+ " \"appointmentStacking\": false,\r\n"
					+ " \"slotCount\": 1,\r\n"
					+ " \"allowSameDayAppts\": true,\r\n"
					+ " \"apptTimeMark\": 30,\r\n"
					+ " \"apptTypeAllocated\": true,\r\n"
					+ " \"isContiguous\": false,\r\n"
					+ " \"leadTime\": {\r\n"
					+ " \"days\": \"0\",\r\n"
					+ " \"hours\": \"0\",\r\n"
					+ " \"mins\": \"0\"\r\n"
					+ " },\r\n"
					+ " \"excludeSlots\": [],\r\n"
					+ " \"apptTypeReservedReason\": \"n\",\r\n"
					+ " \"acceptComment\": false,\r\n"
					+ " \"allowOnlineCancellation\": true,\r\n"
					+ " \"slotSize\": 5,\r\n"
					+ " \"schedulingDuration\": 0,\r\n"
					+ " \"pttype\": \"PT_ALL\",\r\n"
					+ " \"lastQuestRequired\": false\r\n"
					+ "}";
		return timeMark;
	}
	
	public String practicePyaload() {

		String payload = "{\r\n"
				+ "  \"id\": 24702,\r\n"
				+ "  \"name\": \"PSS-NG-PG16CN\",\r\n"
				+ "  \"practiceId\": \"24702\",\r\n"
				+ "  \"themeColor\": \"#008c7f\",\r\n"
				+ "  \"extPracticeId\": \"24702\",\r\n"
				+ "  \"partner\": \"NG\",\r\n"
				+ "  \"timezone\": \"America/Chicago\",\r\n"
				+ "  \"active\": true,\r\n"
				+ "  \"languages\": [\r\n"
				+ "    {\r\n"
				+ "      \"code\": \"EN\",\r\n"
				+ "      \"flag\": \"us\",\r\n"
				+ "      \"name\": \"English\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"starttime\": \"00:00\",\r\n"
				+ "  \"endtime\": \"23:59\",\r\n"
				+ "  \"logo\": null,\r\n"
				+ "  \"type\": null\r\n"
				+ "}";
		return payload;
	}	
	
	public String cancelReasonOffPyaload(boolean bool) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"allowCancellationHours\",\r\n"
				+ "    \"value\": \"00:00\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PATIENT_ACCESS\",\r\n"
				+ "    \"key\": \"ValidDuration\",\r\n"
				+ "    \"value\": \"12\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"displaySlotsCount\",\r\n"
				+ "    \"value\": 2\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"maxCalendarMonths\",\r\n"
				+ "    \"value\": 2\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ageRestriction\",\r\n"
				+ "    \"value\": \"18\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"maxAppointments\",\r\n"
				+ "    \"value\": 10\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ShowPastAppointmentMonths\",\r\n"
				+ "    \"value\": 5\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"showNextAvailable\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"LOCATION\",\r\n"
				+ "    \"key\": \"searchLocation\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showUpcoming\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showPast\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"patientUpdateConfig\",\r\n"
				+ "    \"value\": \"PATIENT_NOTES\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"establishPatientLastVisit\",\r\n"
				+ "    \"value\": \"1095\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showCancelReason\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"patientCreationDuration\",\r\n"
				+ "    \"value\": \"1095\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MULTI_PRACTICE_SETTING\",\r\n"
				+ "    \"key\": \"sharePatientAcrossPractices\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String rescheduleOnCancelPyaload(String days) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": \"Insomnia\",\r\n"
				+ "    \"displayName\": \"Insomnia\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": \"ss\"\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": null\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 1,\r\n"
				+ "    \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "    \"preventRescheduleOnCancel\": \""+days+"\",\r\n"
				+ "    \"preventScheduling\": 0,\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"206321\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"PSS WLA\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 206321,\r\n"
				+ "          \"address1\": \"Address line 1\",\r\n"
				+ "          \"address2\": \"Address line 2\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"NC\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"country\": \"string\",\r\n"
				+ "          \"latitude\": 35.7469276,\r\n"
				+ "          \"longitude\": -78.77481569999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": false,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4052,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [\r\n"
				+ "        {\r\n"
				+ "          \"startTime\": \"05:00\",\r\n"
				+ "          \"endTime\": \"06:00\",\r\n"
				+ "          \"id\": 202374,\r\n"
				+ "          \"beforeAfterStart\": \">\",\r\n"
				+ "          \"beforeAfterEnd\": \"<\"\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": false,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 30,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String bookappointmenttypePyaload(int days) {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212092,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4303,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": "+days+",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	
	public String locationsByNextAvailablePyaload() {

		String payload = "";
		return payload;
	}	
	public String apptTypeConfgPyaload(boolean bool) {

		String payload = "{\r\n"
				+ "  \"id\": 4052,\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": "+bool+",\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"acceptComment\": false,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"slotSize\": 5,\r\n"
				+ "  \"schedulingDuration\": 30,\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	public String inactivePatientPyaload(int id) {

		String payload = "{\r\n"
				+ "  \"id\": "+id+",\r\n"
				+ "  \"key\": \"Bad Debt\",\r\n"
				+ "  \"value\": \"Bad Debt\",\r\n"
				+ "  \"type\": \"NOTES\",\r\n"
				+ "  \"messages\": {\r\n"
				+ "    \"EN\": \"Bad Debt English\",\r\n"
				+ "    \"ES\": \"Bad Debt Spanish\"\r\n"
				+ "  },\r\n"
				+ "  \"group\": \"ALERTS\",\r\n"
				+ "  \"displayMessage\": \"Bad Debt English\"\r\n"
				+ "}";
		return payload;
	}	
	public String activeLockoutPyaload() {

		String payload = "{\r\n"
				+ "  \"key\": \"Active\",\r\n"
				+ "  \"value\": \"Active\",\r\n"
				+ "  \"type\": \"PATIENT_STATUS\",\r\n"
				+ "  \"selected\": true,\r\n"
				+ "  \"group\": \"LOCKOUT\",\r\n"
				+ "  \"id\": null\r\n"
				+ "}";
		return payload;
	}	
	
	public String overbookingPyaload(boolean bool) {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": "+bool+",\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	public String apptDurationPyaload(int apptduration) {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": "+apptduration+",\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}
	
	public String mergeSlotPyaload(int slotcount) {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": "+slotcount+",\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	public String preventBackToBackPyaload(boolean isContiguous) {
		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": "+isContiguous+",\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	public String maxPerDayPyaload(int maxPerDay) {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212092,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4303,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": "+maxPerDay+",\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	public String slotPyaload() {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"timeZone\": null,\r\n"
				+ "    \"date\": \"01/06/2022\",\r\n"
				+ "    \"slotList\": [\r\n"
				+ "      {\r\n"
				+ "        \"slotTime\": \"22:30:00\",\r\n"
				+ "        \"slotId\": \"0001\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"slotTime\": \"22:35:00\",\r\n"
				+ "        \"slotId\": \"0001\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"timeZone\": null,\r\n"
				+ "    \"date\": \"01/07/2022\",\r\n"
				+ "    \"slotList\": [\r\n"
				+ "      {\r\n"
				+ "        \"slotTime\": \"02:05:00\",\r\n"
				+ "        \"slotId\": \"0001\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"slotTime\": \"02:10:00\",\r\n"
				+ "        \"slotId\": \"0001\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	public String preventSchedPyaload(int day) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": \"Insomnia\",\r\n"
				+ "    \"displayName\": \"Insomnia\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": \"ss\"\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": null\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 1,\r\n"
				+ "    \"categoryId\": \"73D35CC3-EACA-447C-B728-17BD077D3FD5\",\r\n"
				+ "    \"categoryName\": \"Insomnia\",\r\n"
				+ "    \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": \""+day+"\",\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"206321\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"PSS WLA\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 206321,\r\n"
				+ "          \"address1\": \"Address line 1\",\r\n"
				+ "          \"address2\": \"Address line 2\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"NC\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"country\": \"string\",\r\n"
				+ "          \"latitude\": 35.7469276,\r\n"
				+ "          \"longitude\": -78.77481569999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": false,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4052,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": false,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 30,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	public String apptTabSettingPyaload(int displaySlotsCount, int maxCalendarMonths) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"allowCancellationHours\",\r\n"
				+ "    \"value\": \"00:00\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PATIENT_ACCESS\",\r\n"
				+ "    \"key\": \"ValidDuration\",\r\n"
				+ "    \"value\": \"12\"\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"displaySlotsCount\",\r\n"
				+ "    \"value\": "+displaySlotsCount+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"maxCalendarMonths\",\r\n"
				+ "    \"value\": "+maxCalendarMonths+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ageRestriction\",\r\n"
				+ "    \"value\": \"18\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"maxAppointments\",\r\n"
				+ "    \"value\": \"1\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ShowPastAppointmentMonths\",\r\n"
				+ "    \"value\": \"5\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"showNextAvailable\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"LOCATION\",\r\n"
				+ "    \"key\": \"searchLocation\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showUpcoming\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showPast\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"patientUpdateConfig\",\r\n"
				+ "    \"value\": \"PATIENT_NOTES\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"establishPatientLastVisit\",\r\n"
				+ "    \"value\": \"1095\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showCancelReason\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"patientCreationDuration\",\r\n"
				+ "    \"value\": \"1095\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MULTI_PRACTICE_SETTING\",\r\n"
				+ "    \"key\": \"sharePatientAcrossPractices\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	public String excludeSlotPyaload() {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [\r\n"
				+ "    {\r\n"
				+ "      \"startTime\": \"01:00\",\r\n"
				+ "      \"endTime\": \"00:00\",\r\n"
				+ "      \"beforeAfterStart\": \"<\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"startTime\": \"01:15\",\r\n"
				+ "      \"endTime\": \"00:00\",\r\n"
				+ "      \"beforeAfterStart\": \">\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206532\",\r\n"
				+ "      \"name\": \"PSS Cary\",\r\n"
				+ "      \"displayName\": \"PSS Cary\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206432,\r\n"
				+ "        \"address1\": \"\",\r\n"
				+ "        \"address2\": \"\",\r\n"
				+ "        \"city\": \"Test\",\r\n"
				+ "        \"state\": \"AL\",\r\n"
				+ "        \"zipCode\": \"555555555\",\r\n"
				+ "        \"latitude\": 0,\r\n"
				+ "        \"longitude\": 0,\r\n"
				+ "        \"locAddress\": \"  Test AL 555555555\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"1B595F99-278A-4956-8F04-1879B12FB43D\",\r\n"
				+ "      \"selected\": false,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	public String resetExcludePyaload() {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206532\",\r\n"
				+ "      \"name\": \"PSS Cary\",\r\n"
				+ "      \"displayName\": \"PSS Cary\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206432,\r\n"
				+ "        \"address1\": \"\",\r\n"
				+ "        \"address2\": \"\",\r\n"
				+ "        \"city\": \"Test\",\r\n"
				+ "        \"state\": \"AL\",\r\n"
				+ "        \"zipCode\": \"555555555\",\r\n"
				+ "        \"latitude\": 0,\r\n"
				+ "        \"longitude\": 0,\r\n"
				+ "        \"locAddress\": \"  Test AL 555555555\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"1B595F99-278A-4956-8F04-1879B12FB43D\",\r\n"
				+ "      \"selected\": false,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	public String lastSeenProviderPyaload(int lastSeenMonth) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MF_SERVICES\",\r\n"
				+ "    \"key\": \"ShowProviderImages\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"PrimaryCareProvider\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"displayLastSeenProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"lastSeenProviderMonths\",\r\n"
				+ "    \"value\": \""+lastSeenMonth+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeam\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeamDuration\",\r\n"
				+ "    \"value\": \"6\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"pcpAvailabilityDuration\",\r\n"
				+ "    \"value\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"rcp\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"pcp\",\r\n"
				+ "    \"value\": \"false\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String lastSeenProviderPyaloadAT(int lastSeenMonth) {
		
		String payload="[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MF_SERVICES\",\r\n"
				+ "    \"key\": \"ShowProviderImages\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"PrimaryCareProvider\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"displayLastSeenProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"lastSeenProviderMonths\",\r\n"
				+ "    \"value\": \""+lastSeenMonth+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeam\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeamDuration\",\r\n"
				+ "    \"value\": \"6\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"pcpAvailabilityDuration\",\r\n"
				+ "    \"value\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"pcp\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	public String bookRulePyaload(int location, int appt) {

		String payload = "{\r\n"
				+ "  \"specialty\": null,\r\n"
				+ "  \"location\": "+location+",\r\n"
				+ "  \"book\": null,\r\n"
				+ "  \"appointmentType\": "+appt+",\r\n"
				+ "  \"slotId\": null,\r\n"
				+ "  \"patientType\": \"PT_EXISTING\",\r\n"
				+ "  \"linkGenerationFlow\": false,\r\n"
				+ "  \"patientDetails\": {\r\n"
				+ "    \"FN\": \"shri\",\r\n"
				+ "    \"LN\": \"kant\",\r\n"
				+ "    \"DOB\": \"01/01/2001\",\r\n"
				+ "    \"GENDER\": \"UN\",\r\n"
				+ "    \"EMAIL\": null,\r\n"
				+ "    \"PHONE\": null,\r\n"
				+ "    \"INSID\": null,\r\n"
				+ "    \"ADDR1\": null,\r\n"
				+ "    \"ADDR2\": null,\r\n"
				+ "    \"CITY\": null,\r\n"
				+ "    \"STATE\": null,\r\n"
				+ "    \"ZIP\": null\r\n"
				+ "  },\r\n"
				+ "  \"flow\": \"loginless\"\r\n"
				+ "}";
		return payload;
	}	
	
	public String lastSeenNewPatientPyaload() {

		String payload = "{\r\n"
				+ "  \"specialty\": null,\r\n"
				+ "  \"location\": 206321,\r\n"
				+ "  \"book\": null,\r\n"
				+ "  \"appointmentType\": 209180,\r\n"
				+ "  \"startDateTime\": \"01/15/2022 00:35:00\",\r\n"
				+ "  \"slotId\": null,\r\n"
				+ "  \"traversal\": false,\r\n"
				+ "  \"patientType\": \"PT_NEW\",\r\n"
				+ "  \"extApptId\": null,\r\n"
				+ "  \"linkGenerationFlow\": false,\r\n"
				+ "  \"patientDetails\": {\r\n"
				+ "    \"FN\": \"lastseen\",\r\n"
				+ "    \"LN\": \"lastseen\",\r\n"
				+ "    \"DOB\": \"01/01/2000\",\r\n"
				+ "    \"GENDER\": \"M\",\r\n"
				+ "    \"EMAIL\": null,\r\n"
				+ "    \"PHONE\": null,\r\n"
				+ "    \"INSID\": null,\r\n"
				+ "    \"ADDR1\": null,\r\n"
				+ "    \"ADDR2\": null,\r\n"
				+ "    \"CITY\": null,\r\n"
				+ "    \"STATE\": null,\r\n"
				+ "    \"ZIP\": null\r\n"
				+ "  },\r\n"
				+ "  \"flow\": \"loginless\"\r\n"
				+ "}";
		return payload;
	}	
	
	public String patientTypeAdminSetting(int a, int b) {
		
		String payload="[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"allowCancellationHours\",\r\n"
				+ "    \"value\": \"00:00\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PATIENT_ACCESS\",\r\n"
				+ "    \"key\": \"ValidDuration\",\r\n"
				+ "    \"value\": \"12\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"displaySlotsCount\",\r\n"
				+ "    \"value\": \"2\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"maxCalendarMonths\",\r\n"
				+ "    \"value\": \"121\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ageRestriction\",\r\n"
				+ "    \"value\": \"18\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"maxAppointments\",\r\n"
				+ "    \"value\": \"1\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ShowPastAppointmentMonths\",\r\n"
				+ "    \"value\": \"5\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"showNextAvailable\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"LOCATION\",\r\n"
				+ "    \"key\": \"searchLocation\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showUpcoming\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showPast\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"patientUpdateConfig\",\r\n"
				+ "    \"value\": \"PATIENT_NOTES\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"establishPatientLastVisit\",\r\n"
				+ "    \"value\": \""+a+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showCancelReason\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"patientCreationDuration\",\r\n"
				+ "    \"value\": \""+b+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MULTI_PRACTICE_SETTING\",\r\n"
				+ "    \"key\": \"sharePatientAcrossPractices\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  }\r\n"
				+ "]";
		
		return payload;
	}
	
	public String forceLastSeenPyaload(int days) {

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212092,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4303,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": \"0\",\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \"n\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": "+days+",\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	public String reserveSameDayWithBookPyaload(String daytype){

		String payload = "{\r\n"
				+ "  \"isageRule\": false,\r\n"
				+ "  \"id\": 212093,\r\n"
				+ "  \"description\": null,\r\n"
				+ "  \"book\": {\r\n"
				+ "    \"id\": 4305,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"emailAddress\": null,\r\n"
				+ "    \"extBookId\": null,\r\n"
				+ "    \"acceptComment\": null,\r\n"
				+ "    \"acceptEmail\": null,\r\n"
				+ "    \"acceptNew\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"deleted\": null,\r\n"
				+ "    \"providerMessage\": null,\r\n"
				+ "    \"sharePatients\": null,\r\n"
				+ "    \"slotSize\": null,\r\n"
				+ "    \"status\": false,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"practice\": null,\r\n"
				+ "    \"specialty\": null,\r\n"
				+ "    \"bookSort\": null,\r\n"
				+ "    \"bookTranslations\": null,\r\n"
				+ "    \"bookType\": null,\r\n"
				+ "    \"bookLevel\": null,\r\n"
				+ "    \"careteam\": null,\r\n"
				+ "    \"links\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentType\": {\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": null,\r\n"
				+ "    \"displayName\": null,\r\n"
				+ "    \"description\": null,\r\n"
				+ "    \"extAppointmentTypeId\": null,\r\n"
				+ "    \"duration\": null,\r\n"
				+ "    \"categoryId\": null,\r\n"
				+ "    \"categoryName\": null,\r\n"
				+ "    \"messages\": null,\r\n"
				+ "    \"customQuestion\": null,\r\n"
				+ "    \"customMessage\": null,\r\n"
				+ "    \"appointmentTypeTranslation\": null,\r\n"
				+ "    \"preventRescheduleOnCancel\": null,\r\n"
				+ "    \"ageRule\": null,\r\n"
				+ "    \"preventScheduling\": null,\r\n"
				+ "    \"appointmentTypeSort\": null\r\n"
				+ "  },\r\n"
				+ "  \"appointmentStacking\": false,\r\n"
				+ "  \"preventScheduling\": 0,\r\n"
				+ "  \"slotCount\": 1,\r\n"
				+ "  \"allowSameDayAppts\": true,\r\n"
				+ "  \"apptTimeMark\": 0,\r\n"
				+ "  \"apptTypeAllocated\": true,\r\n"
				+ "  \"isContiguous\": false,\r\n"
				+ "  \"leadTime\": {\r\n"
				+ "    \"days\": 0,\r\n"
				+ "    \"hours\": \"0\",\r\n"
				+ "    \"mins\": \"0\"\r\n"
				+ "  },\r\n"
				+ "  \"maxPerDay\": 0,\r\n"
				+ "  \"excludeSlots\": [],\r\n"
				+ "  \"apptTypeReservedReason\": \""+daytype+"\",\r\n"
				+ "  \"ageRule\": \"\",\r\n"
				+ "  \"status\": true,\r\n"
				+ "  \"allowOnlineCancellation\": true,\r\n"
				+ "  \"providerAvailabilityDays\": 0,\r\n"
				+ "  \"schedulingDuration\": 0,\r\n"
				+ "  \"locations\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206532\",\r\n"
				+ "      \"name\": \"PSS Cary\",\r\n"
				+ "      \"displayName\": \"PSS Cary\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206432,\r\n"
				+ "        \"address1\": \"\",\r\n"
				+ "        \"address2\": \"\",\r\n"
				+ "        \"city\": \"Test\",\r\n"
				+ "        \"state\": \"AL\",\r\n"
				+ "        \"zipCode\": \"555555555\",\r\n"
				+ "        \"latitude\": 0,\r\n"
				+ "        \"longitude\": 0,\r\n"
				+ "        \"locAddress\": \"  Test AL 555555555\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"1B595F99-278A-4956-8F04-1879B12FB43D\",\r\n"
				+ "      \"selected\": false,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"206321\",\r\n"
				+ "      \"name\": \"PSS WLA\",\r\n"
				+ "      \"displayName\": \"PSS WLA\",\r\n"
				+ "      \"address\": {\r\n"
				+ "        \"id\": 206321,\r\n"
				+ "        \"address1\": \"Address line 1\",\r\n"
				+ "        \"address2\": \"Address line 2\",\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"NC\",\r\n"
				+ "        \"zipCode\": \"27518\",\r\n"
				+ "        \"country\": \"string\",\r\n"
				+ "        \"latitude\": 35.7469276,\r\n"
				+ "        \"longitude\": -78.77481569999999,\r\n"
				+ "        \"locAddress\": \"Address line 1 Address line 2 Cary NC 27518\"\r\n"
				+ "      },\r\n"
				+ "      \"timezone\": \"\",\r\n"
				+ "      \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "      \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "      \"selected\": true,\r\n"
				+ "      \"phoneNumber\": \"\",\r\n"
				+ "      \"restrictToCareteam\": false,\r\n"
				+ "      \"locationLinks\": {}\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"pttype\": \"PT_ALL\",\r\n"
				+ "  \"lastQuestRequired\": false\r\n"
				+ "}";
		return payload;
	}	
	
	public String allowDuplicatePyaload(boolean bool) {
		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"showPrivacyForAnonymous\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"allowDuplicatePatient\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String careTeamSettingPyaload(int pcp, int fct) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MF_SERVICES\",\r\n"
				+ "    \"key\": \"ShowProviderImages\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"PrimaryCareProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"displayLastSeenProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"lastSeenProviderMonths\",\r\n"
				+ "    \"value\": \""+pcp+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeam\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeamDuration\",\r\n"
				+ "    \"value\": \""+fct+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"pcpAvailabilityDuration\",\r\n"
				+ "    \"value\": \"1\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"rcp\",\r\n"
				+ "    \"value\": \"false\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"pcp\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String fctOnOffPyaload(boolean bool) {
		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MF_SERVICES\",\r\n"
				+ "    \"key\": \"ShowProviderImages\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"PrimaryCareProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"displayLastSeenProvider\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"lastSeenProviderMonths\",\r\n"
				+ "    \"value\": \"1\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeam\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"forceCareTeamDuration\",\r\n"
				+ "    \"value\": \"60\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"pcpAvailabilityDuration\",\r\n"
				+ "    \"value\": \"1\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"rcp\",\r\n"
				+ "    \"value\": \"false\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"CARE_TEAM\",\r\n"
				+ "    \"key\": \"pcp\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String pcpSharePatientPyaload(boolean bool) {
		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 4303,\r\n"
				+ "    \"name\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Ng1 Pss [PSS, NG1]\"\r\n"
				+ "    },\r\n"
				+ "    \"displayName\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "    \"ageRule\": \"\",\r\n"
				+ "    \"extBookId\": \"FB84CDED-8A67-4A40-81F8-9401F59DC6C6\",\r\n"
				+ "    \"sharePatients\": "+bool+",\r\n"
				+ "    \"slotSize\": 5,\r\n"
				+ "    \"status\": true,\r\n"
				+ "    \"providerImage\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/pss-adapter-modulator/24702/book/FB84CDED-8A67-4A40-81F8-9401F59DC6C6/image\",\r\n"
				+ "    \"specialty\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"isgenderRule\": false,\r\n"
				+ "        \"id\": 204921,\r\n"
				+ "        \"name\": \"sp1\",\r\n"
				+ "        \"displayName\": \"sp1\",\r\n"
				+ "        \"ageRule\": \"\",\r\n"
				+ "        \"description\": \"spq\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"location\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"206321\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"PSS WLA\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 206321,\r\n"
				+ "          \"address1\": \"Address line 1\",\r\n"
				+ "          \"address2\": \"Address line 2\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"NC\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"country\": \"string\",\r\n"
				+ "          \"latitude\": 35.7469276,\r\n"
				+ "          \"longitude\": -78.77481569999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": false,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"appointmentType\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 209180,\r\n"
				+ "        \"name\": \"Insomnia\",\r\n"
				+ "        \"displayName\": \"Insomnia\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"73D35CC3-EACA-447C-B728-17BD077D3FD5\",\r\n"
				+ "        \"categoryName\": \"Insomnia\",\r\n"
				+ "        \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 206528,\r\n"
				+ "        \"name\": \"Covid-19\",\r\n"
				+ "        \"displayName\": \"Covid-19\",\r\n"
				+ "        \"displayNames\": {},\r\n"
				+ "        \"message\": {},\r\n"
				+ "        \"question\": {},\r\n"
				+ "        \"customMessages\": {},\r\n"
				+ "        \"categoryId\": \"8F563A6C-7098-4446-97E2-7EF9345ED469\",\r\n"
				+ "        \"categoryName\": \"Covid-19\",\r\n"
				+ "        \"extAppointmentTypeId\": \"86D0E00F-C136-4A24-BF7A-6C17E9AB35ED\",\r\n"
				+ "        \"preventRescheduleOnCancel\": 0,\r\n"
				+ "        \"preventScheduling\": 0\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"sortOrder\": 9,\r\n"
				+ "    \"acceptComment\": true,\r\n"
				+ "    \"acceptNew\": false,\r\n"
				+ "    \"categoryId\": \"730C6F5E-4F8C-482F-BB81-F6050841FD8D\",\r\n"
				+ "    \"categoryName\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "    \"bookType\": {\r\n"
				+ "      \"name\": \"PERSON\",\r\n"
				+ "      \"code\": \"RS_PERSON\",\r\n"
				+ "      \"grouptype\": \"RESOURCE\"\r\n"
				+ "    },\r\n"
				+ "    \"bookLevel\": {\r\n"
				+ "      \"name\": \"None\",\r\n"
				+ "      \"code\": \"RS_NONE\",\r\n"
				+ "      \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "    },\r\n"
				+ "    \"careteam\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": 4068,\r\n"
				+ "        \"name\": \"Flower Care Team Automation\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"providerlinks\": {}\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	public String llPrivactPolicyPyaload(boolean bool) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"ANNOUNCEMENT\",\r\n"
				+ "    \"key\": \"showPrivacyPolicyMessage\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String preventSchedPyaload1(int day) {
		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"isageRule\": false,\r\n"
				+ "    \"id\": 209180,\r\n"
				+ "    \"name\": \"Insomnia\",\r\n"
				+ "    \"displayName\": \"Insomnia\",\r\n"
				+ "    \"displayNames\": {\r\n"
				+ "      \"EN\": \"Insomnia\"\r\n"
				+ "    },\r\n"
				+ "    \"message\": {\r\n"
				+ "      \"EN\": \"ss\"\r\n"
				+ "    },\r\n"
				+ "    \"question\": {\r\n"
				+ "      \"EN\": null\r\n"
				+ "    },\r\n"
				+ "    \"customMessages\": {\r\n"
				+ "      \"EN\": null\r\n"
				+ "    },\r\n"
				+ "    \"sortOrder\": 1,\r\n"
				+ "    \"categoryId\": \"73D35CC3-EACA-447C-B728-17BD077D3FD5\",\r\n"
				+ "    \"categoryName\": \"Insomnia\",\r\n"
				+ "    \"extAppointmentTypeId\": \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "    \"preventRescheduleOnCancel\": 0,\r\n"
				+ "    \"preventScheduling\": \""+day+"\",\r\n"
				+ "    \"locations\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"206321\",\r\n"
				+ "        \"name\": \"PSS WLA\",\r\n"
				+ "        \"displayName\": \"PSS WLA\",\r\n"
				+ "        \"address\": {\r\n"
				+ "          \"id\": 206321,\r\n"
				+ "          \"address1\": \"Address line 1\",\r\n"
				+ "          \"address2\": \"Address line 2\",\r\n"
				+ "          \"city\": \"Cary\",\r\n"
				+ "          \"state\": \"NC\",\r\n"
				+ "          \"zipCode\": \"27518\",\r\n"
				+ "          \"country\": \"string\",\r\n"
				+ "          \"latitude\": 35.7469276,\r\n"
				+ "          \"longitude\": -78.77481569999999\r\n"
				+ "        },\r\n"
				+ "        \"timezone\": \"\",\r\n"
				+ "        \"extLocationId\": \"283BB437-B0C6-4626-A7CC-57FD0D1D6574\",\r\n"
				+ "        \"directionUrl\": \"https://dev3-pss-adminportal-ui.dev.medfusion.net/#/app/location\",\r\n"
				+ "        \"selected\": false,\r\n"
				+ "        \"phoneNumber\": \"\",\r\n"
				+ "        \"restrictToCareteam\": false,\r\n"
				+ "        \"locationLinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"param\": {\r\n"
				+ "      \"id\": 4052,\r\n"
				+ "      \"appointmentStacking\": false,\r\n"
				+ "      \"slotCount\": 1,\r\n"
				+ "      \"allowSameDayAppts\": true,\r\n"
				+ "      \"apptTimeMark\": 0,\r\n"
				+ "      \"apptTypeAllocated\": true,\r\n"
				+ "      \"isContiguous\": false,\r\n"
				+ "      \"leadTime\": {\r\n"
				+ "        \"days\": \"0\",\r\n"
				+ "        \"hours\": \"0\",\r\n"
				+ "        \"mins\": \"0\"\r\n"
				+ "      },\r\n"
				+ "      \"excludeSlots\": [],\r\n"
				+ "      \"apptTypeReservedReason\": \"n\",\r\n"
				+ "      \"acceptComment\": false,\r\n"
				+ "      \"allowOnlineCancellation\": true,\r\n"
				+ "      \"slotSize\": 5,\r\n"
				+ "      \"schedulingDuration\": 30,\r\n"
				+ "      \"pttype\": \"PT_ALL\",\r\n"
				+ "      \"lastQuestRequired\": false\r\n"
				+ "    },\r\n"
				+ "    \"ageRule\": \"\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	
	public String onlineCancelLeadTimePyaload(String time) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"allowCancellationHours\",\r\n"
				+ "    \"value\": \""+time+"\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PATIENT_ACCESS\",\r\n"
				+ "    \"key\": \"ValidDuration\",\r\n"
				+ "    \"value\": \"12\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"displaySlotsCount\",\r\n"
				+ "    \"value\": 10\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"SLOTS\",\r\n"
				+ "    \"key\": \"maxCalendarMonths\",\r\n"
				+ "    \"value\": \"2\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ageRestriction\",\r\n"
				+ "    \"value\": \"18\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"maxAppointments\",\r\n"
				+ "    \"value\": \"10\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"ShowPastAppointmentMonths\",\r\n"
				+ "    \"value\": \"5\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"PROVIDER\",\r\n"
				+ "    \"key\": \"showNextAvailable\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"LOCATION\",\r\n"
				+ "    \"key\": \"searchLocation\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showUpcoming\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showPast\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"patientUpdateConfig\",\r\n"
				+ "    \"value\": \"PATIENT_NOTES\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"establishPatientLastVisit\",\r\n"
				+ "    \"value\": \"1095\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"APPOINTMENT\",\r\n"
				+ "    \"key\": \"showCancelReason\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"RULEENGINE\",\r\n"
				+ "    \"key\": \"patientCreationDuration\",\r\n"
				+ "    \"value\": \"1095\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"MULTI_PRACTICE_SETTING\",\r\n"
				+ "    \"key\": \"sharePatientAcrossPractices\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}	
	
	public String addBookInCareTeamPyaload(int bookid) {
		String payload = "{\r\n"
				+ "  \"careTeam\": {\r\n"
				+ "    \"id\": 4068\r\n"
				+ "  },\r\n"
				+ "  \"book\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": "+bookid+"\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}";
		return payload;
	}	
	
	
	public String insurancePyaload(boolean bool) {

		String payload = "[\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE\",\r\n"
				+ "    \"key\": \"showInsuranceStart\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE\",\r\n"
				+ "    \"key\": \"insuranceMandatory\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE\",\r\n"
				+ "    \"key\": \"selfPay\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE\",\r\n"
				+ "    \"key\": \"showInsuranceCarrierFromPM\",\r\n"
				+ "    \"value\": "+bool+"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE\",\r\n"
				+ "    \"key\": \"restrictPatient\",\r\n"
				+ "    \"value\": true\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE\",\r\n"
				+ "    \"key\": \"allowSpecialCharForInsurance\",\r\n"
				+ "    \"value\": false\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE_ROUTING\",\r\n"
				+ "    \"key\": \"one\",\r\n"
				+ "    \"value\": \"true\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"group\": \"INSURANCE_ROUTING\",\r\n"
				+ "    \"key\": \"two\",\r\n"
				+ "    \"value\": \"false\"\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	
	
}