// Copyright 2021 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.pss2patientapi.payload;

public class PayloadDBAdapter {
	
	public String saveAnnouncementPayload(int id, String type,String code ) {
		String saveAnn = "{\r\n"
				+ "    \"id\": "+id+",\r\n"
				+ "    \"text\": {\r\n"
				+ "        \"EN\": \"Good Night\",\r\n"
				+ "        \"ES\": \"Espanol Good Night\"\r\n"
				+ "    },\r\n"
				+ "    \"display\": \"Your welcome message will be displayed here. Please contact Medfusion support to add your own text or disable this message.\",\r\n"
				+ "    \"type\": \""+type+"\",\r\n"
				+ "    \"code\": \""+code+"\",\r\n"
				+ "    \"selected\": true,\r\n"
				+ "    \"description\": \"Displayed in dialog when PSS first page loads\"\r\n"
				+ "}";
		return saveAnn;
	}
	
	
	public String saveBookPayload_new() {
		String payload ="[\r\n"
				+ "    {\r\n"
				+ "        \"id\": 4303,\r\n"
				+ "        \"name\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "        \"displayName\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "        \"emailAddress\": null,\r\n"
				+ "        \"extBookId\": \"FB84CDED-8A67-4A40-81F8-9401F59DC6C6\",\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"acceptEmail\": false,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"ageRule\": \"\",\r\n"
				+ "        \"deleted\": false,\r\n"
				+ "        \"providerMessage\": null,\r\n"
				+ "        \"sharePatients\": true,\r\n"
				+ "        \"slotSize\": 5,\r\n"
				+ "        \"status\": true,\r\n"
				+ "        \"categoryId\": \"730C6F5E-4F8C-482F-BB81-F6050841FD8D\",\r\n"
				+ "        \"categoryName\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "        \"specialty\": null,\r\n"
				+ "        \"bookTranslations\": [\r\n"
				+ "            {\r\n"
				+ "                \"id\": null,\r\n"
				+ "                \"language\": {\r\n"
				+ "                    \"code\": \"EN\",\r\n"
				+ "                    \"name\": null,\r\n"
				+ "                    \"flag\": null\r\n"
				+ "                },\r\n"
				+ "                \"displayName\": \"Ng1 Pss [PSS, NG1]\",\r\n"
				+ "                \"createdUserId\": null,\r\n"
				+ "                \"updatedUserId\": null\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"bookSort\": null,\r\n"
				+ "        \"bookType\": {\r\n"
				+ "            \"code\": \"RS_PERSON\",\r\n"
				+ "            \"name\": \"PERSON\",\r\n"
				+ "            \"grouptype\": \"RESOURCE\"\r\n"
				+ "        },\r\n"
				+ "        \"bookLevel\": {\r\n"
				+ "            \"code\": \"RS_NONE\",\r\n"
				+ "            \"name\": \"None\",\r\n"
				+ "            \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "        },\r\n"
				+ "        \"careteam\": null,\r\n"
				+ "        \"createdUserId\": null,\r\n"
				+ "        \"updatedUserId\": null,\r\n"
				+ "        \"links\": [\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"LG_ANO\",\r\n"
				+ "                \"extBookId\": \"FB84CDED-8A67-4A40-81F8-9401F59DC6C6\",\r\n"
				+ "                \"guid\": \"43e5be88-7321-47ee-87bf-b86c8fe6d724\",\r\n"
				+ "                \"extBookCategoryId\": \"730C6F5E-4F8C-482F-BB81-F6050841FD8D\",\r\n"
				+ "                \"deleted\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"LG_LOG\",\r\n"
				+ "                \"extBookId\": \"FB84CDED-8A67-4A40-81F8-9401F59DC6C6\",\r\n"
				+ "                \"guid\": \"1c4ccc09-9381-464b-a972-39cda6230047\",\r\n"
				+ "                \"extBookCategoryId\": \"730C6F5E-4F8C-482F-BB81-F6050841FD8D\",\r\n"
				+ "                \"deleted\": false\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    }\r\n"
				+ "]";
		return payload;
	}
	
	public String createBook() {
		String payload ="[\r\n"
				+ "    {\r\n"
				+ "        \"name\": \"Gates1 Bil [BilGate1]\",\r\n"
				+ "        \"displayName\": \"Gates1 Bil [BilGate1]\",\r\n"
				+ "        \"emailAddress\": null,\r\n"
				+ "        \"extBookId\": \"89C26EFE-5572-4A61-B550-07FE979977DC\",\r\n"
				+ "        \"acceptComment\": false,\r\n"
				+ "        \"acceptEmail\": false,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"ageRule\": \"\",\r\n"
				+ "        \"deleted\": false,\r\n"
				+ "        \"providerMessage\": null,\r\n"
				+ "        \"sharePatients\": false,\r\n"
				+ "        \"slotSize\": 0,\r\n"
				+ "        \"status\": false,\r\n"
				+ "        \"categoryId\": \"A8D202D1-17A9-4BD7-B7A2-49AAE945157C\",\r\n"
				+ "        \"categoryName\": \"Gates1 Bil [BilGate1]\",\r\n"
				+ "        \"specialty\": null,\r\n"
				+ "        \"bookTranslations\": [\r\n"
				+ "            {\r\n"
				+ "                \"id\": null,\r\n"
				+ "                \"language\": {\r\n"
				+ "                    \"code\": \"EN\",\r\n"
				+ "                    \"name\": null,\r\n"
				+ "                    \"flag\": null\r\n"
				+ "                },\r\n"
				+ "                \"displayName\": \"Gates1 Bil [BilGate1]\",\r\n"
				+ "                \"createdUserId\": null,\r\n"
				+ "                \"updatedUserId\": null\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"bookSort\": null,\r\n"
				+ "        \"bookType\": {\r\n"
				+ "            \"code\": \"RS_PERSON\",\r\n"
				+ "            \"name\": \"PERSON\",\r\n"
				+ "            \"grouptype\": \"RESOURCE\"\r\n"
				+ "        },\r\n"
				+ "        \"bookLevel\": {\r\n"
				+ "            \"code\": \"RS_NONE\",\r\n"
				+ "            \"name\": \"None\",\r\n"
				+ "            \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "        },\r\n"
				+ "        \"careteam\": null,\r\n"
				+ "        \"createdUserId\": null,\r\n"
				+ "        \"updatedUserId\": null,\r\n"
				+ "        \"links\": [\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"LG_ANO\",\r\n"
				+ "                \"extBookId\": \"89C26EFE-5572-4A61-B550-07FE979977DC\",\r\n"
				+ "                \"guid\": \"42ae37f3-3d22-40c9-8089-4cf0ad8b1ffb\",\r\n"
				+ "                \"extBookCategoryId\": \"A8D202D1-17A9-4BD7-B7A2-49AAE945157C\",\r\n"
				+ "                \"deleted\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"type\": \"LG_LOG\",\r\n"
				+ "                \"extBookId\": \"89C26EFE-5572-4A61-B550-07FE979977DC\",\r\n"
				+ "                \"guid\": \"60d65f80-09a6-4f63-9364-7bf177f895b6\",\r\n"
				+ "                \"extBookCategoryId\": \"A8D202D1-17A9-4BD7-B7A2-49AAE945157C\",\r\n"
				+ "                \"deleted\": false\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    }\r\n"
				+ "]";
		return payload;
	}
	
	public String saveBookLocationPayload() {
		String payload ="{\r\n"
				+ "    \"book\": {\r\n"
				+ "        \"id\": 206457,\r\n"
				+ "        \"name\": null,\r\n"
				+ "        \"displayName\": null,\r\n"
				+ "        \"emailAddress\": null,\r\n"
				+ "        \"extBookId\": null,\r\n"
				+ "        \"acceptComment\": false,\r\n"
				+ "        \"acceptEmail\": false,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"ageRule\": null,\r\n"
				+ "        \"deleted\": false,\r\n"
				+ "        \"providerMessage\": null,\r\n"
				+ "        \"sharePatients\": false,\r\n"
				+ "        \"slotSize\": 0,\r\n"
				+ "        \"status\": false,\r\n"
				+ "        \"categoryId\": null,\r\n"
				+ "        \"categoryName\": null,\r\n"
				+ "        \"specialty\": null,\r\n"
				+ "        \"bookTranslations\": null,\r\n"
				+ "        \"bookSort\": null,\r\n"
				+ "        \"bookType\": null,\r\n"
				+ "        \"bookLevel\": null,\r\n"
				+ "        \"careteam\": null,\r\n"
				+ "        \"createdUserId\": null,\r\n"
				+ "        \"updatedUserId\": null\r\n"
				+ "    },\r\n"
				+ "    \"location\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": 4139,\r\n"
				+ "            \"displayName\": null,\r\n"
				+ "            \"extLocationId\": null,\r\n"
				+ "            \"name\": null,\r\n"
				+ "            \"description\": null,\r\n"
				+ "            \"directionUrl\": null,\r\n"
				+ "            \"address\": null,\r\n"
				+ "            \"timeZone\": null,\r\n"
				+ "            \"locationTranslations\": null,\r\n"
				+ "            \"locationSort\": null,\r\n"
				+ "            \"createdUserId\": null,\r\n"
				+ "            \"updatedUserId\": null,\r\n"
				+ "            \"locationPhones\": null,\r\n"
				+ "            \"restrictToCareteam\": false\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return payload;
	}
	
	public String bookLocationsGetPayload() {
		String payload ="{\r\n"
				+ "  \"id\" : 206502,\r\n"
				+ "  \"name\" : null,\r\n"
				+ "  \"displayName\" : null,\r\n"
				+ "  \"emailAddress\" : null,\r\n"
				+ "  \"extBookId\" : null,\r\n"
				+ "  \"acceptComment\" : false,\r\n"
				+ "  \"acceptEmail\" : false,\r\n"
				+ "  \"acceptNew\" : false,\r\n"
				+ "  \"ageRule\" : null,\r\n"
				+ "  \"deleted\" : false,\r\n"
				+ "  \"providerMessage\" : null,\r\n"
				+ "  \"sharePatients\" : false,\r\n"
				+ "  \"slotSize\" : 0,\r\n"
				+ "  \"status\" : false,\r\n"
				+ "  \"categoryId\" : null,\r\n"
				+ "  \"categoryName\" : null,\r\n"
				+ "  \"specialty\" : null,\r\n"
				+ "  \"bookTranslations\" : null,\r\n"
				+ "  \"bookSort\" : null,\r\n"
				+ "  \"bookType\" : null,\r\n"
				+ "  \"bookLevel\" : null,\r\n"
				+ "  \"careteam\" : null,\r\n"
				+ "  \"createdUserId\" : null,\r\n"
				+ "  \"updatedUserId\" : null\r\n"
				+ "}";
		return payload;
	}
	
	public String cancellationReasonPayload() {
		String payload ="[{\r\n"
				+ "  \"id\" : null,\r\n"
				+ "  \"extCancellationReasonId\" : \"1297CE8A-C43A-4FF8-9DFB-4922F69AC14E\",\r\n"
				+ "  \"name\" : \"Not Covered By Insurance\",\r\n"
				+ "  \"displayName\" : \"Not Covered By Insurance\",\r\n"
				+ "  \"cancellationReasonSort\" : null,\r\n"
				+ "  \"practice\" : null,\r\n"
				+ "  \"createdUserId\" : null,\r\n"
				+ "  \"updatedUserId\" : null,\r\n"
				+ "  \"type\" : {\r\n"
				+ "    \"code\" : \"CR_CANCEL\",\r\n"
				+ "    \"name\" : \"Cancellation Reason\",\r\n"
				+ "    \"grouptype\" : \"CANCEL_REASON\"\r\n"
				+ "  }\r\n"
				+ "}]";
		return payload;
	}
	
	public String reorderPayload() {
		String payload ="{\r\n"
				+ "  \"source\": 0,\r\n"
				+ "  \"target\": 1\r\n"
				+ "}";
		return payload;
	}
	
	public String saveCareTeamPayload() {
		String payload ="[\r\n"
				+ "  {\r\n"
				+ "    \"id\": 4068,\r\n"
				+ "    \"name\": \"Flower Care Team Automation\",\r\n"
				+ "    \"book\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 206456,\r\n"
				+ "        \"name\": \"Saif PSS [Saif PSS]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Saif PSS [Saif PSS]\"\r\n"
				+ "        },\r\n"
				+ "        \"displayName\": \"Saif PSS [Saif PSS]\",\r\n"
				+ "        \"extBookId\": \"6A6269EE-E9F3-4880-B36F-C90E51EB33CF\",\r\n"
				+ "        \"sharePatients\": true,\r\n"
				+ "        \"slotSize\": 15,\r\n"
				+ "        \"status\": true,\r\n"
				+ "        \"specialty\": [\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 203604,\r\n"
				+ "            \"name\": \"specialty\",\r\n"
				+ "            \"displayName\": \"specialty\",\r\n"
				+ "            \"ageRule\": \"\"\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 4134,\r\n"
				+ "            \"name\": \"sp3\",\r\n"
				+ "            \"displayName\": \"sp3\",\r\n"
				+ "            \"ageRule\": \"\",\r\n"
				+ "            \"description\": \"yes\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"categoryId\": \"10F8A2F7-4291-4855-BBFA-87AB3E3A6C60\",\r\n"
				+ "        \"categoryName\": \"Saif PSS [Saif PSS]\",\r\n"
				+ "        \"bookType\": {\r\n"
				+ "          \"name\": \"PERSON\",\r\n"
				+ "          \"code\": \"RS_PERSON\",\r\n"
				+ "          \"grouptype\": \"RESOURCE\"\r\n"
				+ "        },\r\n"
				+ "        \"bookLevel\": {\r\n"
				+ "          \"name\": \"None\",\r\n"
				+ "          \"code\": \"RS_NONE\",\r\n"
				+ "          \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "        },\r\n"
				+ "        \"careteam\": [\r\n"
				+ "          {\r\n"
				+ "            \"id\": 4068,\r\n"
				+ "            \"name\": \"Flower Care Team Automation\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"providerlinks\": {}\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 206457,\r\n"
				+ "        \"name\": \"Dinesh PSS [Dinesh PSS]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Dinesh PSS [Dinesh PSS]\"\r\n"
				+ "        },\r\n"
				+ "        \"displayName\": \"Dinesh PSS [Dinesh PSS]\",\r\n"
				+ "        \"extBookId\": \"78E497EF-0C8F-4D59-AD40-FE7BE12B9842\",\r\n"
				+ "        \"sharePatients\": true,\r\n"
				+ "        \"slotSize\": 15,\r\n"
				+ "        \"status\": true,\r\n"
				+ "        \"specialty\": [\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 203604,\r\n"
				+ "            \"name\": \"specialty\",\r\n"
				+ "            \"displayName\": \"specialty\",\r\n"
				+ "            \"ageRule\": \"\"\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 4134,\r\n"
				+ "            \"name\": \"sp3\",\r\n"
				+ "            \"displayName\": \"sp3\",\r\n"
				+ "            \"ageRule\": \"\",\r\n"
				+ "            \"description\": \"yes\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"categoryId\": \"437DCCDB-8D78-475F-B661-EF393674F1F8\",\r\n"
				+ "        \"categoryName\": \"Dinesh PSS [Dinesh PSS]\",\r\n"
				+ "        \"bookType\": {\r\n"
				+ "          \"name\": \"PERSON\",\r\n"
				+ "          \"code\": \"RS_PERSON\",\r\n"
				+ "          \"grouptype\": \"RESOURCE\"\r\n"
				+ "        },\r\n"
				+ "        \"bookLevel\": {\r\n"
				+ "          \"name\": \"None\",\r\n"
				+ "          \"code\": \"RS_NONE\",\r\n"
				+ "          \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "        },\r\n"
				+ "        \"careteam\": [\r\n"
				+ "          {\r\n"
				+ "            \"id\": 4068,\r\n"
				+ "            \"name\": \"Flower Care Team Automation\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"providerlinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	
	public String createCareTeam() {
		String payload ="[\r\n"
				+ "  {\r\n"
				+ "    \"name\": \"Lovely Care Team Automation\",\r\n"
				+ "    \"book\": [\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 206456,\r\n"
				+ "        \"name\": \"Saif PSS [Saif PSS]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Saif PSS [Saif PSS]\"\r\n"
				+ "        },\r\n"
				+ "        \"displayName\": \"Saif PSS [Saif PSS]\",\r\n"
				+ "        \"extBookId\": \"6A6269EE-E9F3-4880-B36F-C90E51EB33CF\",\r\n"
				+ "        \"sharePatients\": true,\r\n"
				+ "        \"slotSize\": 15,\r\n"
				+ "        \"status\": true,\r\n"
				+ "        \"specialty\": [\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 203604,\r\n"
				+ "            \"name\": \"specialty\",\r\n"
				+ "            \"displayName\": \"specialty\",\r\n"
				+ "            \"ageRule\": \"\"\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 4134,\r\n"
				+ "            \"name\": \"sp3\",\r\n"
				+ "            \"displayName\": \"sp3\",\r\n"
				+ "            \"ageRule\": \"\",\r\n"
				+ "            \"description\": \"yes\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"categoryId\": \"10F8A2F7-4291-4855-BBFA-87AB3E3A6C60\",\r\n"
				+ "        \"categoryName\": \"Saif PSS [Saif PSS]\",\r\n"
				+ "        \"bookType\": {\r\n"
				+ "          \"name\": \"PERSON\",\r\n"
				+ "          \"code\": \"RS_PERSON\",\r\n"
				+ "          \"grouptype\": \"RESOURCE\"\r\n"
				+ "        },\r\n"
				+ "        \"bookLevel\": {\r\n"
				+ "          \"name\": \"None\",\r\n"
				+ "          \"code\": \"RS_NONE\",\r\n"
				+ "          \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "        },\r\n"
				+ "        \"careteam\": [\r\n"
				+ "          {\r\n"
				+ "            \"id\": 4068,\r\n"
				+ "            \"name\": \"Flower Care Team Automation\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"providerlinks\": {}\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"isageRule\": false,\r\n"
				+ "        \"id\": 206457,\r\n"
				+ "        \"name\": \"Dinesh PSS [Dinesh PSS]\",\r\n"
				+ "        \"displayNames\": {\r\n"
				+ "          \"EN\": \"Dinesh PSS [Dinesh PSS]\"\r\n"
				+ "        },\r\n"
				+ "        \"displayName\": \"Dinesh PSS [Dinesh PSS]\",\r\n"
				+ "        \"extBookId\": \"78E497EF-0C8F-4D59-AD40-FE7BE12B9842\",\r\n"
				+ "        \"sharePatients\": true,\r\n"
				+ "        \"slotSize\": 15,\r\n"
				+ "        \"status\": true,\r\n"
				+ "        \"specialty\": [\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 203604,\r\n"
				+ "            \"name\": \"specialty\",\r\n"
				+ "            \"displayName\": \"specialty\",\r\n"
				+ "            \"ageRule\": \"\"\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"isageRule\": false,\r\n"
				+ "            \"isgenderRule\": false,\r\n"
				+ "            \"id\": 4134,\r\n"
				+ "            \"name\": \"sp3\",\r\n"
				+ "            \"displayName\": \"sp3\",\r\n"
				+ "            \"ageRule\": \"\",\r\n"
				+ "            \"description\": \"yes\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"acceptComment\": true,\r\n"
				+ "        \"acceptNew\": false,\r\n"
				+ "        \"categoryId\": \"437DCCDB-8D78-475F-B661-EF393674F1F8\",\r\n"
				+ "        \"categoryName\": \"Dinesh PSS [Dinesh PSS]\",\r\n"
				+ "        \"bookType\": {\r\n"
				+ "          \"name\": \"PERSON\",\r\n"
				+ "          \"code\": \"RS_PERSON\",\r\n"
				+ "          \"grouptype\": \"RESOURCE\"\r\n"
				+ "        },\r\n"
				+ "        \"bookLevel\": {\r\n"
				+ "          \"name\": \"None\",\r\n"
				+ "          \"code\": \"RS_NONE\",\r\n"
				+ "          \"grouptype\": \"RESOURCE_LEVEL\"\r\n"
				+ "        },\r\n"
				+ "        \"careteam\": [\r\n"
				+ "          {\r\n"
				+ "            \"id\": 4068,\r\n"
				+ "            \"name\": \"Flower Care Team Automation\"\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"providerlinks\": {}\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		return payload;
	}
	
	public String careTeamBookPayload() {
		String payload ="{\r\n"
				+ "  \"careTeam\" : {\r\n"
				+ "    \"id\" : 4068,\r\n"
				+ "    \"name\" : null,\r\n"
				+ "    \"deleted\" : false,\r\n"
				+ "    \"createdTs\" : null,\r\n"
				+ "    \"updatedTs\" : null,\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null\r\n"
				+ "  },\r\n"
				+ "  \"book\" : [ {\r\n"
				+ "    \"id\" : 4305,\r\n"
				+ "    \"name\" : null,\r\n"
				+ "    \"displayName\" : null,\r\n"
				+ "    \"emailAddress\" : null,\r\n"
				+ "    \"extBookId\" : null,\r\n"
				+ "    \"acceptComment\" : false,\r\n"
				+ "    \"acceptEmail\" : false,\r\n"
				+ "    \"acceptNew\" : false,\r\n"
				+ "    \"ageRule\" : null,\r\n"
				+ "    \"deleted\" : false,\r\n"
				+ "    \"providerMessage\" : null,\r\n"
				+ "    \"sharePatients\" : false,\r\n"
				+ "    \"slotSize\" : 0,\r\n"
				+ "    \"status\" : false,\r\n"
				+ "    \"categoryId\" : null,\r\n"
				+ "    \"categoryName\" : null,\r\n"
				+ "    \"specialty\" : null,\r\n"
				+ "    \"bookTranslations\" : null,\r\n"
				+ "    \"bookSort\" : null,\r\n"
				+ "    \"bookType\" : null,\r\n"
				+ "    \"bookLevel\" : null,\r\n"
				+ "    \"careteam\" : null,\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null\r\n"
				+ "  } ]\r\n"
				+ "}";
		return payload;
	}
	
	
	public String saveCategory() {
		String payload =" [ {\r\n"
				+ "\r\n"
				+ "  \"name\" : \"Karishma\",\r\n"
				+ "  \"displayName\" : \"Karishma_Automation\",\r\n"
				+ "  \"lookUp\" : {\r\n"
				+ "    \"code\" : \"CG_APPOINTMENT_TYPE\",\r\n"
				+ "    \"name\" : null,\r\n"
				+ "    \"grouptype\" : null\r\n"
				+ "  },\r\n"
				+ "  \"nodes\" : [ {\r\n"
				+ "    \"guid\" : \"208223\",\r\n"
				+ "    \"type\" : \"CATEGORY\",\r\n"
				+ "    \"displayName\" : \"Karishma_Automation\",\r\n"
				+ "    \"displayNames\" : {\r\n"
				+ "      \"EN\" : \"Karishma_Automation\",\r\n"
				+ "      \"ES\" : \"Karishma_Automation\"\r\n"
				+ "    },\r\n"
				+ "    \"entity\" : null,\r\n"
				+ "    \"children\" : [ \"1da4e6b6-b037-48ae-9b8b-f1e25c922551\" ],\r\n"
				+ "    \"parentId\" : null\r\n"
				+ "  }, {\r\n"
				+ "    \"guid\" : \"1da4e6b6-b037-48ae-9b8b-f1e25c922551\",\r\n"
				+ "    \"type\" : \"QUESTION\",\r\n"
				+ "    \"displayName\" : \"[QUESTION0]\",\r\n"
				+ "    \"displayNames\" : {\r\n"
				+ "      \"EN\" : \"Questio -English\",\r\n"
				+ "      \"ES\" : \"Esapnol Hola amigo\"\r\n"
				+ "    },\r\n"
				+ "    \"entity\" : null,\r\n"
				+ "    \"children\" : [ \"b5aa8f5d-0b65-4f0e-8bd5-e1a05891bf80\" ],\r\n"
				+ "    \"parentId\" : \"208223\"\r\n"
				+ "  }, {\r\n"
				+ "    \"guid\" : \"b5aa8f5d-0b65-4f0e-8bd5-e1a05891bf80\",\r\n"
				+ "    \"type\" : \"ANSWER\",\r\n"
				+ "    \"displayName\" : \"[ANSWER0]\",\r\n"
				+ "    \"displayNames\" : {\r\n"
				+ "      \"EN\" : \"Answer-English\",\r\n"
				+ "      \"ES\" : \"Hola Amiga\"\r\n"
				+ "    },\r\n"
				+ "    \"entity\" : {\r\n"
				+ "      \"id\" : \"4235\",\r\n"
				+ "      \"name\" : \"Insomnia\",\r\n"
				+ "      \"extAppointmentTypeId\" : \"E0F61D51-3AFB-412E-AA3C-18786D23821C\",\r\n"
				+ "      \"categoryId\" : \"24A7DC4F-4DB6-427C-9FA5-EB76FA2142D0\",\r\n"
				+ "      \"categoryName\" : \"Insomnia\",\r\n"
				+ "      \"type\" : \"appointment_type\",\r\n"
				+ "      \"apptmessage\" : null,\r\n"
				+ "      \"reason\" : {\r\n"
				+ "        \"EN\" : \"SSSSSSSSSSSSS\",\r\n"
				+ "        \"ES\" : \"SSSSSSSSSSSSS\"\r\n"
				+ "      }\r\n"
				+ "    },\r\n"
				+ "    \"children\" : [ ],\r\n"
				+ "    \"parentId\" : \"1da4e6b6-b037-48ae-9b8b-f1e25c922551\"\r\n"
				+ "  } ],\r\n"
				+ "  \"categoryTranslations\" : [ {\r\n"
				+ "    \"id\" : null,\r\n"
				+ "    \"language\" : {\r\n"
				+ "      \"code\" : \"ES\",\r\n"
				+ "      \"name\" : null,\r\n"
				+ "      \"flag\" : null\r\n"
				+ "    },\r\n"
				+ "    \"displayName\" : \"Spanish_Karishma\",\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null\r\n"
				+ "  } ],\r\n"
				+ "  \"categorySort\" : null,\r\n"
				+ "  \"createdUserId\" : null,\r\n"
				+ "  \"updatedUserId\" : null,\r\n"
				+ "  \"status\" : \"PUBLISHED\"\r\n"
				+ "} ]";
		return payload;
	}
	
	public String visitReasonPayload() {
		String payload =" {\r\n"
				+ "  \"appTypeDetail\" : {\r\n"
				+ "    \"categoryId\" : \"208262\",\r\n"
				+ "    \"guid\" : \"9a2ec160-97d1-4034-879a-adcbb17c8fe9\",\r\n"
				+ "    \"appTypeId\" : \"208251\"\r\n"
				+ "  }\r\n"
				+ "}";
		return payload;
	}
	
	public String categoryspecialtyPayload() {
		String payload ="{\r\n"
				+ "  \"category\" : {\r\n"
				+ "    \"id\" : 208321,\r\n"
				+ "    \"name\" : null,\r\n"
				+ "    \"displayName\" : null,\r\n"
				+ "    \"lookUp\" : null,\r\n"
				+ "    \"nodes\" : null,\r\n"
				+ "    \"categoryTranslations\" : null,\r\n"
				+ "    \"categorySort\" : null,\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null,\r\n"
				+ "    \"status\" : null\r\n"
				+ "  },\r\n"
				+ "  \"specialty\" : [ {\r\n"
				+ "    \"id\" : 204921,\r\n"
				+ "    \"extSpecialtyId\" : null,\r\n"
				+ "    \"name\" : null,\r\n"
				+ "    \"ageRule\" : null,\r\n"
				+ "    \"genderRule\" : null,\r\n"
				+ "    \"description\" : null,\r\n"
				+ "    \"displayName\" : null,\r\n"
				+ "    \"specialitySort\" : null,\r\n"
				+ "    \"specialtyTranslation\" : null,\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null,\r\n"
				+ "    \"specialtyRule\" : null\r\n"
				+ "  } ]\r\n"
				+ "}";
		return payload;
	}
	
	public String getSpecialtiesAssociatedToCategoryPayload() {
		String payload ="{\r\n"
				+ "  \"id\" : 208321,\r\n"
				+ "  \"name\" : null,\r\n"
				+ "  \"displayName\" : null,\r\n"
				+ "  \"lookUp\" : null,\r\n"
				+ "  \"nodes\" : null,\r\n"
				+ "  \"categoryTranslations\" : null,\r\n"
				+ "  \"categorySort\" : null,\r\n"
				+ "  \"createdUserId\" : null,\r\n"
				+ "  \"updatedUserId\" : null,\r\n"
				+ "  \"status\" : null\r\n"
				+ "}";
		return payload;
	}

	public String createAnnouncementPayload() {
		String payload ="{\r\n"
				+ "  \"id\" : null,\r\n"
				+ "  \"announcementText\" : null,\r\n"
				+ "  \"createdUserId\" : null,\r\n"
				+ "  \"updatedUserId\" : null,\r\n"
				+ "  \"announcementType\" : {\r\n"
				+ "    \"id\" : null,\r\n"
				+ "    \"name\" : \"Patient Not Found\",\r\n"
				+ "    \"code\" : \"PNF\",\r\n"
				+ "    \"active\" : null,\r\n"
				+ "    \"description\" : null\r\n"
				+ "  },\r\n"
				+ "  \"announcementTranslation\" : [ {\r\n"
				+ "    \"id\" : null,\r\n"
				+ "    \"announcementText\" : \"There was no patient found in our system that matches the information you entered. Please check your information and try again or register as new patient.\",\r\n"
				+ "    \"language\" : {\r\n"
				+ "      \"code\" : \"EN\",\r\n"
				+ "      \"name\" : null,\r\n"
				+ "      \"flag\" : null\r\n"
				+ "    },\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null\r\n"
				+ "  }, {\r\n"
				+ "    \"id\" : null,\r\n"
				+ "    \"announcementText\" : \"No hubo ningún paciente en nuestro sistema aue coincide con la información que ingresó. Por favor verifique su información y inténtelo de nuevo.\",\r\n"
				+ "    \"language\" : {\r\n"
				+ "      \"code\" : \"ES\",\r\n"
				+ "      \"name\" : null,\r\n"
				+ "      \"flag\" : null\r\n"
				+ "    },\r\n"
				+ "    \"createdUserId\" : null,\r\n"
				+ "    \"updatedUserId\" : null\r\n"
				+ "  } ]\r\n"
				+ "}";
		return payload;
	}
	
	public String saveAnnouncementPayload() {
		String payload ="{\r\n"
				+ "    \"id\": 206498,\r\n"
				+ "    \"announcementText\": null,\r\n"
				+ "    \"createdUserId\": null,\r\n"
				+ "    \"updatedUserId\": null,\r\n"
				+ "    \"announcementType\": {\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"name\": \"Restrict CareTeam\",\r\n"
				+ "        \"code\": \"RCT\",\r\n"
				+ "        \"active\": null,\r\n"
				+ "        \"description\": null\r\n"
				+ "    },\r\n"
				+ "    \"announcementTranslation\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": null,\r\n"
				+ "            \"announcementText\": \"It seems that there are no appointment slots available for your selected preference. Kindly modify your selection to see the available appointment slots.\\nPlease contact your PSS Admin.\",\r\n"
				+ "            \"language\": {\r\n"
				+ "                \"code\": \"EN\",\r\n"
				+ "                \"name\": null,\r\n"
				+ "                \"flag\": null\r\n"
				+ "            },\r\n"
				+ "            \"createdUserId\": null,\r\n"
				+ "            \"updatedUserId\": null\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": null,\r\n"
				+ "            \"announcementText\": \"Parece que no hay espacios de citas disponibles para su preferencia seleccionada. Modifique amablemente su selección para ver los espacios disponibles para citas.\\nPlease contact your PSS Admin.- Spanish\",\r\n"
				+ "            \"language\": {\r\n"
				+ "                \"code\": \"ES\",\r\n"
				+ "                \"name\": null,\r\n"
				+ "                \"flag\": null\r\n"
				+ "            },\r\n"
				+ "            \"createdUserId\": null,\r\n"
				+ "            \"updatedUserId\": null\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return payload;
	}
	
	public String saveAppointmentPayload() {
		String payload ="{\r\n"
				+ "  \"id\" : 238201,\r\n"
				+ "  \"patientId\" : null,\r\n"
				+ "  \"apptDate\" : null,\r\n"
				+ "  \"duration\" : null,\r\n"
				+ "  \"apptStatus\" : null,\r\n"
				+ "  \"emailAddress\" : null,\r\n"
				+ "  \"extApptId\" : null,\r\n"
				+ "  \"comments\" : null,\r\n"
				+ "  \"trackingNumber\" : null,\r\n"
				+ "  \"dateUpdated\" : null,\r\n"
				+ "  \"notificationStatus\" : \"NOTIFIED\",\r\n"
				+ "  \"practice\" : null,\r\n"
				+ "  \"book\" : null,\r\n"
				+ "  \"appointmentType\" : null,\r\n"
				+ "  \"location\" : null,\r\n"
				+ "  \"specialty\" : null,\r\n"
				+ "  \"refExtAppointmentId\" : null,\r\n"
				+ "  \"retryCount\" : 0\r\n"
				+ "}";
		return payload;
	}
	
	public String updateAppointmentPayload() {
		String payload ="{\r\n"
				+ "  \"id\" : 238118,\r\n"
				+ "  \"notificationStatus\" : \"NOTIFIED\",\r\n"
				+ "  \"retryCount\" : 0\r\n"
				+ "}";
		return payload;
	}
	
}
