package com.intuit.ihg.product.integrationplatform.utils;

public class BulkAdmin {
	public String[] PatientsUserNameArray = new String[3];
	public String[] PatientsPasswordArray = new String[3];
	public String[] PatientsIDArray = new String[3];
	public String[] PatientsArray = new String[20];
	public String[] PatientEmailArray = new String[3];
	public String AddAttachment = "";
	public String NumberOfParams = "";
	public String Url = "";
	public String UserName = "";
	public String Password = "";
	public String RestUrl = "";
	public String ResponsePath = "";
	public String From = "";
	public String OAuthProperty = "";
	public String OAuthKeyStore = "";
	public String OAuthAppToken = "";
	public String OAuthUsername = "";
	public String OAuthPassword = "";
	public String ReadCommuniationURL = "";
	public String SecureMessage_AskaStaffXML = "";
	public String Batch_SecureMessage = "";
	public String UserName1 = "";
	public String From1 = "";
	public String UserName2 = "";
	public String Sender1 = "";
	public String Sender2 = "";
	public String Sender3 = "";
	public String IntegrationPracticeID = "";
	public String PatientName1 = "";
	public String PatientName2 = "";
	public String PatientName3 = "";
	public String GmailUserName = "";
	public String GmailPassword = "";
	public String AttachmentLocation = "";
	public String MaxPatients = "";
	public String NumberOfAttachments = "";
	public String previousBulkMessageId = "";
	public String resendPreviousMessage = "";
	public String ParamValue = "";
	public String ParamName = "";
	public String MessageBulk = "";
	public String Subject = "";
	public String FileName = "";
	public String ParamValue1 = "";
	public String ParamName1 = "";
	public String ParamValue2 = "";
	public String ParamName2 = "";
	public String ParamValue3 = "";
	public String ParamName3 = "";
	public String messageID = "";
	public String[] ParamNameArray = new String[20];
	public String[] ParamValueArray = new String[20];
	public String BulkEmailType = "";
	public String PatientExternalId = "";
	public String oUserName = "";
	public String oPassword = "";
	public String oPatientID = "";
	public String oEmailID = "";


}
