package com.intuit.ihg.product.integrationplatform.utils;

public class PIDC {

	public String Url = "";
	public String UserName = "";
	public String Password = "";
	public String RestUrl = "";
	public String PatientPath = "";
	public String ResponsePath = "";
	public String OAuthProperty = "";
	public String OAuthKeyStore = "";
	public String OAuthAppToken = "";
	public String OAuthUsername = "";
	public String OAuthPassword = "";
	public String GmailUsername = "";
	public String GmailPassword = "";
	public String BirthDay = "";
	public String ZipCode = "";
	public String SSN = "";
	public String Email = "";
	public String PatientPassword = "";
	public String SecretQuestion = "";
	public String SecretAnswer = "";
	public String PracticeURL = "";
	public String PracticeUserName = "";
	public String PracticePassword = "";
	public String LastName = "";
	public String City = "";
	public String State = "";
	public String Address1 = "";
	public String Address2 = "";
	public String HomePhoneNo = "";
	public String Insurance_Type = "";
	public String Insurance_Name = "";
	public String Relation = "";
	public String PreferredLanguage = "";
	public String Race = "";
	public String Ethnicity = "";
	public String MaritalStatus = "";
	public String ChooseCommunication = "";
	public String Batch_PatientPath = "";
	public String PortalURL = "";
	public String PortalRestUrl = "";
	public String HealthKeyPatientUserName = "";
	public String HealthKeyPatientPath = "";
	public String InsuranceHealthKeyPatientUserName = "";
	public String InsurancePortalURL = "";
	public String InsurancePortalRestURL = "";
	public String InsurancePatientID = "";
	public String InsuranceHealthKeyPatientUserName1 = "";
	public String InsurancePatientID1 = "";
	public String SecondInsuranceName = "";
	public String TestPatientIDUserName = "";
	public String FnameSC = "";
	public String MnameSC = "";
	public String LnameSC = "";
	public String Address1SC = "";
	public String Address2SC = "";
	public String GI = "";
	public String SO = "";
	public String NewPassword = "";
	public String Restv1Url = "";
	public String Restv2Url = "";
	public String Restv3Url = "";

}
