package com.medfusion.product.appt.precheck.payload;

public class MfAppointmentSchedulerPayload {
	
	private static MfAppointmentSchedulerPayload payload = new MfAppointmentSchedulerPayload();
	private MfAppointmentSchedulerPayload() {
		
	}
	public static MfAppointmentSchedulerPayload getMfAppointmentSchedulerPayload() {
		return payload;
	}
	
	public String putAppointmentPayload(long time, String phone,String email) {
		String Apptdata="{\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS- GE-DEV5\",\r\n"
				+ "\"providerName\": \"Brown, Jennifer\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\", \r\n"
				+ "\"locationName\": \"River Oaks Main\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"TX\",\r\n"
				+ "\"zip\": \"75248\",\r\n"
				+ "\"phone\": 4344344433, \r\n"
				+ "\"timezoneId\": \"America/New_York\"\r\n"
				+ " },\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"AppScheduler\",\r\n"
				+ "\"middleName\": null, \r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"gender\": \"MALE\",    \r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": \"123 street lane\",\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": \"LA\",\r\n"
				+ "\"state\": \"NY\",\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"phoneType\": \"HOME\",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"insurances\": [\r\n"
				+ "{\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupNumber\": \"123ddd\",\r\n"
				+ "\"gender\": \"Female\",\r\n"
				+ "\r\n"
				+ "\"ssn\": true,\r\n"
				+ "\"type\": \"PRIMARY\",\r\n"
				+ "\"memberId\": \"12345\",\r\n"
				+ "\"payerId\": \"21212\",\r\n"
				+ "\"subscriberDoB\": \"2001-01-01\",\r\n"
				+ "\"subscriberFirstName\": \"priya\",\r\n"
				+ "\"subscriberLastName\": \"chavan\",\r\n"
				+ "\"subscriberMiddleName\": \"rannas\",\r\n"
				+ "\"coPayment\": 30,\r\n"
				+ "\"relationToSubscriber\": {\r\n"
				+ "\"code\": \"09\",\r\n"
				+ "\"name\": \"adopted\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\"name\": \"Blue cross insurance\",\r\n"
				+ "\"groupNumber\": \"12366\",\r\n"
				+ "\"ssn\": false,\r\n"
				+ "\"type\": \"OTHER\",\r\n"
				+ "\"memberId\": \"2345\",\r\n"
				+ "\"payerId\": \"32212\",\r\n"
				+ "\"subscriberFirstName\": \"\",\r\n"
				+ "\"subscriberMiddleName\": \"\",\r\n"
				+ "\"subscriberLastName\": \"\",\r\n"
				+ "\"subscriberDoB\": \"\",\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\"name\": \"Red cross insurance\",\r\n"
				+ "\"groupNumber\": \"12366\",\r\n"
				+ "\"ssn\": false,\r\n"
				+ "\"type\": \"OTHER1\",\r\n"
				+ "\"memberId\": \"2345\",\r\n"
				+ "\"payerId\": \"34343\",\r\n"
				+ "\"subscriberFirstName\": \"Payor A\",\r\n"
				+ "\"subscriberMiddleName\": \"middle\",\r\n"
				+ "\"subscriberLastName\": \"Added\",\r\n"
				+ "\"subscriberDoB\": \"1991-01-01\",\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"name\": \"Aiva insurance\",\r\n"
				+ "\"groupNumber\": \"13445\",\r\n"
				+ "\"ssn\": true,\r\n"
				+ "\"type\": \"SECONDARY\",\r\n"
				+ "\"memberId\": \"2345\",\r\n"
				+ "\"payerId\": \"34343\",\r\n"
				+ "\"subscriberFirstName\": \"Payor A\",\r\n"
				+ "\"subscriberMiddleName\": \"middle\",\r\n"
				+ "\"subscriberLastName\": \"Added\",\r\n"
				+ "\"subscriberDoB\": \"1991-01-01\",\r\n"
				+ "\"coPayment\": 30,\r\n"
				+ "\"gender\":\"Male\",\r\n"
				+ "\"coPayment\": 30,\r\n"
				+ "\"relationToSubscriber\": {\r\n"
				+ "\"code\": \"101\",\r\n"
				+ "\"name\": \"Brother\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"name\": \"MAX life insurance\",\r\n"
				+ "\"groupNumber\": \"13445\",\r\n"
				+ "\"ssn\": false,\r\n"
				+ "\"type\": \"FOURTH\",\r\n"
				+ "\"memberId\": \"2345\",\r\n"
				+ "\"payerId\": \"34343\",\r\n"
				+ "\"subscriberFirstName\": \"Payor A\",\r\n"
				+ "\"subscriberMiddleName\": \"middle\",\r\n"
				+ "\"subscriberLastName\": \"Added\",\r\n"
				+ "\"subscriberDoB\": \"1991-01-01\",\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"name\": \"CARElife insurance\",\r\n"
				+ "\"groupNumber\": \"13445\",\r\n"
				+ "\"ssn\": false,\r\n"
				+ "\"type\": \"SIXTH\",\r\n"
				+ "\"memberId\": \"2345\",\r\n"
				+ "\"payerId\": \"34343\",\r\n"
				+ "\"subscriberFirstName\": \"Payor A\",\r\n"
				+ "\"subscriberMiddleName\": \"middle\",\r\n"
				+ "\"subscriberLastName\": \"Added\",\r\n"
				+ "\"subscriberDoB\": \"1991-01-01\",\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ "],\r\n"
				+ "\"pharmacies\": [\r\n"
				+ "{\r\n"
				+ "\"address\": {\r\n"
				+ "\"city\": \"NY\",\r\n"
				+ "\"line1\": \"12401 Washington Blvd 9080 Colima Rd\",\r\n"
				+ "\"line2\": \"1025 S Anaheim Blvd Whittier,CA 90605\",\r\n"
				+ "\"state\": \"LA\",\r\n"
				+ "\"zipcode\": \"90605\"\r\n"
				+ "},\r\n"
				+ "\"id\": \"23222\",\r\n"
				+ "\"name\": \"Whittier Hospital & Medical Ctr and Suncity Presbyterian Intercommunity Pharmacy\",\r\n"
				+ "\"number\": 1234567890\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\"address\": {\r\n"
				+ "\"city\": \"NY\",\r\n"
				+ "\"line1\": \"234street & 1720 Termino Ave\",\r\n"
				+ "\"line2\": \"3900 E Pacific Coast Hwy Long Beach,CA 90804\",\r\n"
				+ "\"state\": \"CA\",\r\n"
				+ "\"zipcode\": \"90804\"\r\n"
				+ "},\r\n"
				+ "\"id\": \"34454\",\r\n"
				+ "\"name\": \"Skyui Pharmacy & Community Hospital Long Beach Inpatient Pharmacy\",\r\n"
				+ "\"number\": 9876543211\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "],\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";

		return Apptdata;
	}
	
	public String putAppointmentPayloadwithDifferentlocation(long time, String phone,String email) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \"Donald, Anderson\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \"USA\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"AppScheduler\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}

	public String putAppointmentPastTimePayload() {
		String pastApt=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \"Brown, Jennifer\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \"River Oaks Main\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"AppScheduler\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": 5087437423,\r\n"
				+ "\"email\": \"testpatient.crossasyst@gmail.com\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": 1628168185000\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return pastApt;
	}
	public String putAppointmentCopayPayload(long time) {
		String Apptdata="{\r\n"
				+ "    \"practiceData\": {\r\n"
				+ "        \"pmSystemId\": \"9\",\r\n"
				+ "        \"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "        \"providerName\": \"Brown, Jennifer\",\r\n"
				+ "        \"nationalProviderId\": null,\r\n"
				+ "        \"locationId\": \"3\",\r\n"
				+ "        \"locationName\": \"River Oaks Main\",\r\n"
				+ "        \"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "        \"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "        \"city\": \"Dallas\",\r\n"
				+ "        \"state\": \"GA\",\r\n"
				+ "        \"zip\": \"00000\",\r\n"
				+ "        \"phone\": 4344344433,\r\n"
				+ "        \"timezoneId\": \"America/Chicago\"\r\n"
				+ "    },\r\n"
				+ "    \"patientIdData\": {\r\n"
				+ "        \"pmInternalId\": \"string\"\r\n"
				+ "    },\r\n"
				+ "    \"patientData\": {\r\n"
				+ "        \"firstName\": \"Rijesh\",\r\n"
				+ "        \"middleName\": null,\r\n"
				+ "        \"lastName\": \"R3ichard\",\r\n"
				+ "        \"dob\": \"1999-01-01\",\r\n"
				+ "        \"address\": \"NC\",\r\n"
				+ "        \"address2\": \"nc\",\r\n"
				+ "        \"city\": \"YC\",\r\n"
				+ "        \"state\": \"YC\",\r\n"
				+ "        \"zip\": \"12345\",\r\n"
				+ "        \"phone\": 5087437423,\r\n"
				+ "        \"email\": \"sujit.kolhe@yahoo.com\",\r\n"
				+ "        \"language\": \"en\",\r\n"
				+ "        \"primaryInsurance\": {\r\n"
				+ "            \"name\": \"Blue Sheild insurance\",\r\n"
				+ "            \"groupName\": \"BLSE SE\",\r\n"
				+ "            \"groupNumber\": \"BL1998989\",\r\n"
				+ "            \"memberName\": \"GEprod test1\",\r\n"
				+ "            \"memberId\": \"BL7878\",\r\n"
				+ "            \"dateIssued\": \"2002-01-01\",\r\n"
				+ "            \"claimsPhoneNumber\": 9876543210,\r\n"
				+ "            \"coPayment\": 40\r\n"
				+ "        },\r\n"
				+ "        \"balance\": {\r\n"
				+ "            \"amount\": 30,\r\n"
				+ "            \"dueBy\": \"2021-04-05\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"appointmentData\": {\r\n"
				+ "        \"type\": \"Scot appt type\",\r\n"
				+ "        \"status\": \"NEW\",\r\n"
				+ "        \"time\": "+time+"\r\n"
				+ "    },\r\n"
				+ "    \"managementData\": {\r\n"
				+ "        \"resourceLink\": \"https://dev3-pss.dev.medfusion.net/psspatient/pss-patient-loginless/53085385-2d3b-462f-a474-1e501b5a6a21\"\r\n"
				+ "    }\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putAppointmentPayload(long time, String phone,String email,String providerName,String patientName, String locationName ) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \""+providerName+"\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \""+locationName+"\",\r\n"
				+ "\"address\": \"3790 W. First Station\",\r\n"
				+ "\"address2\": \"marine lines plaza\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \""+patientName+"\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putAppointmentPayload(long time, String phone,String email,String lang,String patientName) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \"Brown, Jennifer\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \"River Oaks Main\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \""+patientName+"\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \""+lang+"\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putAppointmentPayloadwithdifferentProvider(long time, String phone,String email) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \"David , Johnson\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \"River Oaks Main\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"AppScheduler\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putApptPayloadwithDifferentlocationandProvider(long time, String phone,String email) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \"Brown, Jennifer\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \"USA\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"AppScheduler\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putApptPayloadwithblankPhoneandLocation(long time, String phone,String email,String providerName,String patientName, String locationName ) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \""+providerName+"\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": null,\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": null,\r\n"
				+ "\"phone\": null,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \""+patientName+"\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": null,\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": null,\r\n"
				+ "\"state\": null,\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putApptPayload(long time, String phone,String email) {
		String Apptdata=" {\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS-GE-DEV5\",\r\n"
				+ "\"providerName\": \"Brown, Jennifer\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\",\r\n"
				+ "\"locationName\": \"NewYork\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"GA\",\r\n"
				+ "\"zip\": \"00000\",\r\n"
				+ "\"phone\": 4344344433,\r\n"
				+ "\"timezoneId\": \"America/Chicago\"\r\n"
				+ "},\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"Ra\",\r\n"
				+ "\"middleName\": null,\r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"gender\": \"MALE\",\r\n"
				+ "\"dob\": \"1968-01-01\",\r\n"
				+ "\"address\": \"123 street lane\",\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": \"LA\",\r\n"
				+ "\"state\": \"NY\",\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"primaryInsurance\": {\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupName\": \"BLSE SE\",\r\n"
				+ "\"groupNumber\": \"BL1998989\",\r\n"
				+ "\"memberName\": \"GEprod test1\",\r\n"
				+ "\"memberId\": \"BL7878\",\r\n"
				+ "\"dateIssued\": \"2002-01-01\",\r\n"
				+ "\"claimsPhoneNumber\": 9876543210,\r\n"
				+ "\"coPayment\": 30\r\n"
				+ "}\r\n"
				+ ",\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": 15,\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
	
	public String putApptPayload(long time, String phone,String email,int copay,int balancePay) {
		String Apptdata="{\r\n"
				+ "\"practiceData\": {\r\n"
				+ "\"pmSystemId\": \"9\",\r\n"
				+ "\"practiceName\": \"PSS- GE-DEV5\",\r\n"
				+ "\"providerName\": \"Brown, Jennifer\",\r\n"
				+ "\"nationalProviderId\": null,\r\n"
				+ "\"locationId\": \"3\", \r\n"
				+ "\"locationName\": \"River Oaks Main\",\r\n"
				+ "\"address\": \"3790 W. First Station : add line 1\",\r\n"
				+ "\"address2\": \"marine lines plaza : add line 2\",\r\n"
				+ "\"city\": \"Dallas\",\r\n"
				+ "\"state\": \"TX\",\r\n"
				+ "\"zip\": \"75248\",\r\n"
				+ "\"phone\": 4344344433, \r\n"
				+ "\"timezoneId\": \"America/New_York\"\r\n"
				+ " },\r\n"
				+ "\"patientIdData\": {\r\n"
				+ "\"pmInternalId\": \"string\"\r\n"
				+ "},\r\n"
				+ "\"patientData\": {\r\n"
				+ "\"firstName\": \"AppScheduler\",\r\n"
				+ "\"middleName\": null, \r\n"
				+ "\"lastName\": \"One\",\r\n"
				+ "\"gender\": \"MALE\",    \r\n"
				+ "\"dob\": \"1991-01-01\",\r\n"
				+ "\"address\": \"123 street lane\",\r\n"
				+ "\"address2\": null,\r\n"
				+ "\"city\": \"LA\",\r\n"
				+ "\"state\": \"NY\",\r\n"
				+ "\"zip\": \"12345\",\r\n"
				+ "\"phone\": "+phone+",\r\n"
				+ "\"phoneType\": \"HOME\",\r\n"
				+ "\"email\": \"" + email + "\",\r\n"
				+ "\"language\": \"en\",\r\n"
				+ "\"insurances\": [\r\n"
				+ "{\r\n"
				+ "\"name\": \"Blue Sheild insurance\",\r\n"
				+ "\"groupNumber\": \"123ddd\",\r\n"
				+ "\"gender\": \"Female\",\r\n"
				+ "\r\n"
				+ "\"ssn\": true,\r\n"
				+ "\"type\": \"PRIMARY\",\r\n"
				+ "\"memberId\": \"12345\",\r\n"
				+ "\"payerId\": \"21212\",\r\n"
				+ "\"subscriberDoB\": \"2001-01-01\",\r\n"
				+ "\"subscriberFirstName\": \"priya\",\r\n"
				+ "\"subscriberLastName\": \"chavan\",\r\n"
				+ "\"subscriberMiddleName\": \"rannas\",\r\n"
				+ "\"coPayment\": "+copay+",\r\n"
				+ "\"relationToSubscriber\": {\r\n"
				+ "\"code\": \"09\",\r\n"
				+ "\"name\": \"adopted\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"name\": \"CARElife insurance\",\r\n"
				+ "\"groupNumber\": \"13445\",\r\n"
				+ "\"ssn\": false,\r\n"
				+ "\"type\": \"SIXTH\",\r\n"
				+ "\"memberId\": \"2345\",\r\n"
				+ "\"payerId\": \"34343\",\r\n"
				+ "\"subscriberFirstName\": \"Payor A\",\r\n"
				+ "\"subscriberMiddleName\": \"middle\",\r\n"
				+ "\"subscriberLastName\": \"Added\",\r\n"
				+ "\"subscriberDoB\": \"1991-01-01\",\r\n"
				+ "\"coPayment\": "+copay+"\r\n"
				+ "}\r\n"
				+ "],\r\n"
				+ "\"pharmacies\": [\r\n"
				+ "{\r\n"
				+ "\"address\": {\r\n"
				+ "\"city\": \"NY\",\r\n"
				+ "\"line1\": \"12401 Washington Blvd 9080 Colima Rd\",\r\n"
				+ "\"line2\": \"1025 S Anaheim Blvd Whittier,CA 90605\",\r\n"
				+ "\"state\": \"LA\",\r\n"
				+ "\"zipcode\": \"90605\"\r\n"
				+ "},\r\n"
				+ "\"id\": \"23222\",\r\n"
				+ "\"name\": \"Whittier Hospital & Medical Ctr and Suncity Presbyterian Intercommunity Pharmacy\",\r\n"
				+ "\"number\": 1234567890\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"address\": {\r\n"
				+ "\"city\": \"NY\",\r\n"
				+ "\"line1\": \"234street & 1720 Termino Ave\",\r\n"
				+ "\"line2\": \"3900 E Pacific Coast Hwy Long Beach,CA 90804\",\r\n"
				+ "\"state\": \"CA\",\r\n"
				+ "\"zipcode\": \"90804\"\r\n"
				+ "},\r\n"
				+ "\"id\": \"34454\",\r\n"
				+ "\"name\": \"Skyui Pharmacy & Community Hospital Long Beach Inpatient Pharmacy\",\r\n"
				+ "\"number\": 9876543211\r\n"
				+ "}\r\n"
				+ "],\r\n"
				+ "\r\n"
				+ "\"balance\": {\r\n"
				+ "\"amount\": "+balancePay+",\r\n"
				+ "\"dueBy\": \"2021-04-05\"\r\n"
				+ "}\r\n"
				+ "},\r\n"
				+ "\"appointmentData\": {\r\n"
				+ "\"type\": \"Scot appt type\",\r\n"
				+ "\"status\": \"NEW\",\r\n"
				+ "\"time\": " + time + "\r\n"
				+ "},\r\n"
				+ "\"managementData\": {\r\n"
				+ "\"resourceLink\": \"https://www.medfusion.com/\"\r\n"
				+ "}\r\n"
				+ "}";
		return Apptdata;
	}
}
