// Copyright 2022 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.appt.precheck.payload;

public class MfPracticeSettingsManagerPayload {
	private static MfPracticeSettingsManagerPayload payload = new MfPracticeSettingsManagerPayload();

	private MfPracticeSettingsManagerPayload() {

	}

	public static MfPracticeSettingsManagerPayload getMfPracticeSettingsManagerPayload() {
		return payload;
	}
	
	public String getUpdateReminderSettingsPayload(String timing, int periodValue, String id, String deliveryMtd,
			String apptMethod, String status) {
		String updateReminderSettings = " {\r\n"
				+ "    \"cadence\": [\r\n"
				+ "        {\r\n"
				+ "            \"timing\": \""+timing+"\",\r\n"
				+ "            \"periodValue\": "+periodValue+"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"id\": \""+id+"\",\r\n"
				+ "    \"deliveryMethod\": \""+deliveryMtd+"\",\r\n"
				+ "    \"timingUnit\": [\r\n"
				+ "        {\r\n"
				+ "            \"timing\": \""+timing+"\",\r\n"
				+ "            \"units\": [\r\n"
				+ "                0\r\n"
				+ "            ]\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"version\": \"v2\",\r\n"
				+ "    \"apptMethod\": \"" + apptMethod + "\",\r\n"
				+ "    \"status\": \"" + status + "\"\r\n"
				+ "}";
		return updateReminderSettings;
	}
	
	public String getUpdateSettingsPayload(String practiceId, String systemId, String locationId, String deliveryMtd,
			String language) {
		String updateSettings = "{\r\n"
				+ "    \"id\": \""+practiceId+"\",\r\n"
				+ "    \"active\": false,\r\n"
				+ "    \"pmIntegrationSettings\": {\r\n"
				+ "        \"id\": \"" + systemId + "\",\r\n"
				+ "        \"dataSyncEnabled\": false\r\n"
				+ "    },\r\n"
				+ "    \"locationSettings\": {\r\n"
				+ "        \"primaryLocation\": {\r\n"
				+ "            \"id\": \"" + practiceId + "\",\r\n"
				+ "            \"corporateName\": \"PSS-GE-DEV3APP\",\r\n"
				+ "            \"displayName\": \"PSS-GE-DEV3APP\",\r\n"
				+ "            \"streetNumber\": \"5501\",\r\n"
				+ "            \"streetName\": \"Dillard Dr\",\r\n"
				+ "            \"secondaryAddressDesignator\": null,\r\n"
				+ "            \"city\": \"Cary\",\r\n"
				+ "            \"state\": \"North Carolina\",\r\n"
				+ "            \"zipcode\": \"27518\",\r\n"
				+ "            \"phone\": 9198822880,\r\n"
				+ "            \"fax\": null,\r\n"
				+ "            \"email\": null,\r\n"
				+ "            \"latitude\": null,\r\n"
				+ "            \"longitude\": null,\r\n"
				+ "            \"timezone\": null\r\n"
				+ "        },\r\n"
				+ "        \"locations\": {\r\n"
				+ "            \"abc456\": {\r\n"
				+ "                \"id\": \"" + locationId + "\",\r\n"
				+ "                \"corporateName\": \"Brigs at the Village Restaurant Inc.\",\r\n"
				+ "                \"displayName\": \"Brigs at the Village Restaurant\",\r\n"
				+ "                \"streetNumber\": \"1040\",\r\n"
				+ "                \"streetName\": \"Village Dr\",\r\n"
				+ "                \"secondaryAddressDesignator\": null,\r\n"
				+ "                \"city\": \"Cary\",\r\n"
				+ "                \"state\": \"North Carolina\",\r\n"
				+ "                \"zipcode\": \"27518\",\r\n"
				+ "                \"phone\": 9198592151,\r\n"
				+ "                \"fax\": null,\r\n"
				+ "                \"email\": null,\r\n"
				+ "                \"latitude\": null,\r\n"
				+ "                \"longitude\": null,\r\n"
				+ "                \"timezone\": null\r\n"
				+ "            },\r\n"
				+ "            \"abc777\": {\r\n"
				+ "                \"id\": \"abc777\",\r\n"
				+ "                \"corporateName\": \"Brigs at the Village Restaurant Inc.\",\r\n"
				+ "                \"displayName\": \"Brigs at the Village Restaurant\",\r\n"
				+ "                \"streetNumber\": \"1040\",\r\n"
				+ "                \"streetName\": \"Village Dr\",\r\n"
				+ "                \"secondaryAddressDesignator\": null,\r\n"
				+ "                \"city\": \"Cary\",\r\n"
				+ "                \"state\": \"North Carolina\",\r\n"
				+ "                \"zipcode\": \"27518\",\r\n"
				+ "                \"phone\": 9198592151,\r\n"
				+ "                \"fax\": null,\r\n"
				+ "                \"email\": null,\r\n"
				+ "                \"latitude\": null,\r\n"
				+ "                \"longitude\": null,\r\n"
				+ "                \"timezone\": null\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"notifySettings\": {\r\n"
				+ "        \"enabled\": false,\r\n"
				+ "        \"enabledByPractice\": false,\r\n"
				+ "        \"notifyOneDayOut\": false,\r\n"
				+ "        \"notifyThreeDaysOut\": false,\r\n"
				+ "        \"notifyFiveDaysOut\": false,\r\n"
				+ "        \"reminderNotification\": [\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"de766f30-0878-4f4a-87c4-c6659e369aa6\",\r\n"
				+ "                \"deliveryMethod\": \"" + deliveryMtd + "\",\r\n"
				+ "                \"version\": \"v2\",\r\n"
				+ "                \"apptMethod\": \"In Office\",\r\n"
				+ "                \"status\": \"Published\",\r\n"
				+ "                \"cadence\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 1\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 3\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Hours\",\r\n"
				+ "                        \"periodValue\": 2\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Minutes\",\r\n"
				+ "                        \"periodValue\": 30\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"timingUnit\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"units\": [\r\n"
				+ "                            1,\r\n"
				+ "                            3\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Hours\",\r\n"
				+ "                        \"units\": [\r\n"
				+ "                            2\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Minutes\",\r\n"
				+ "                        \"units\": [\r\n"
				+ "                            30\r\n"
				+ "                        ]\r\n"
				+ "                    }\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"78a46f9e-5133-4c46-b965-2ad00af51fc0\",\r\n"
				+ "                \"deliveryMethod\": \"SMS\",\r\n"
				+ "                \"version\": \"Default\",\r\n"
				+ "                \"apptMethod\": \"In Office\",\r\n"
				+ "                \"status\": \"Published\",\r\n"
				+ "                \"cadence\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 1\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 3\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Minutes\",\r\n"
				+ "                        \"periodValue\": 30\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Hours\",\r\n"
				+ "                        \"periodValue\": 2\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"timingUnit\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"units\": [\r\n"
				+ "                            1,\r\n"
				+ "                            3\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Hours\",\r\n"
				+ "                        \"units\": [\r\n"
				+ "                            2\r\n"
				+ "                        ]\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"timing\": \"Minutes\",\r\n"
				+ "                        \"units\": [\r\n"
				+ "                            30\r\n"
				+ "                        ]\r\n"
				+ "                    }\r\n"
				+ "                ]\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"confirmationNotification\": [\r\n"
				+ "            {\r\n"
				+ "                \"deliveryMethod\": \"Email\",\r\n"
				+ "                \"version\": \"Default\",\r\n"
				+ "                \"apptMethod\": \"In Office\",\r\n"
				+ "                \"status\": \"Published\",\r\n"
				+ "                \"timing\": \"Upon Scheduling\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"deliveryMethod\": \"SMS\",\r\n"
				+ "                \"version\": \"Default\",\r\n"
				+ "                \"apptMethod\": \"In Office\",\r\n"
				+ "                \"status\": \"Published\",\r\n"
				+ "                \"timing\": \"Upon Scheduling\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"includePatientFirstName\": true,\r\n"
				+ "        \"notifyLanguage\": \"" + language + "\",\r\n"
				+ "        \"emailEnabled\": true,\r\n"
				+ "        \"textEnabled\": true,\r\n"
				+ "        \"pushEnabled\": false,\r\n"
				+ "        \"notifyCurbsCheckIn\": true,\r\n"
				+ "        \"enableBroadcast\": true,\r\n"
				+ "        \"arrivalMessage\": {\r\n"
				+ "            \"en\": \"\",\r\n"
				+ "            \"es\": \"\"\r\n"
				+ "        },\r\n"
				+ "        \"defaultArrivalMessage\": {\r\n"
				+ "            \"en\": \"The practice front office staff has been notified that you have arrived. Wait in the parking lot until you receive a message to come in. Call the office at [appointment phone number] if you have been waiting more than 15 minutes.\",\r\n"
				+ "            \"es\": \"Se ha notificado al personal de recepci�n de la pr�ctica que ha llegado. Espere en el estacionamiento hasta que reciba un mensaje para entrar. Llame a la oficina al [n�mero de tel�fono de la cita] si ha estado esperando m�s de 15 minutos.\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"merchantSettings\": {\r\n"
				+ "        \"id\": \"2560794497\",\r\n"
				+ "        \"name\": \"DEV3 Test Practice 7\",\r\n"
				+ "        \"acceptedCreditCards\": [\r\n"
				+ "            \"American Express\",\r\n"
				+ "            \"Mastercard\"\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"precheckSettings\": {\r\n"
				+ "        \"enabled\": true,\r\n"
				+ "        \"disableDemographics\": false,\r\n"
				+ "        \"insuranceSettings\": {\r\n"
				+ "            \"enabled\": true,\r\n"
				+ "            \"textEntryEnabled\": true,\r\n"
				+ "            \"ocrEnabled\": false\r\n"
				+ "        },\r\n"
				+ "        \"disableCopay\": false,\r\n"
				+ "        \"disableBalance\": false,\r\n"
				+ "        \"enablePatientMode\": true,\r\n"
				+ "        \"enableForms\": true,\r\n"
				+ "        \"minBalanceAmount\": null,\r\n"
				+ "        \"minBalancePercent\": null,\r\n"
				+ "        \"minBalanceThreshold\": null,\r\n"
				+ "        \"forms\": [\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"df969390-5564-11eb-bd4e-2104e266e238\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/2b217edb-909d-466e-bed2-b8bb50b5b922/24333\",\r\n"
				+ "                \"title\": \"Adult ADHD Self-Report Scale (ASRS-v1.1) Symptom Checklist\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"51f22160-5566-11eb-bd4e-2104e266e238\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/e548230a-ab05-4433-8925-80c3e379aa82/24333\",\r\n"
				+ "                \"title\": \"General Registration and Health History PK\",\r\n"
				+ "                \"enabledByAppointmentType\": false\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"17877950-556e-11eb-93ea-918e24c9be00\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/f2e7d60c-b8e1-409e-a9a1-3c7e18096d4d/24333\",\r\n"
				+ "                \"title\": \"Prakash Custom Form\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"73684cc0-69e3-11eb-942b-95b607c89218\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/4fff1ec9-d393-4065-873b-eecf5e9503f0/24333\",\r\n"
				+ "                \"title\": \"smoke custom form\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4c2fe1a5-5aa4-4baf-ab39-67b111eb9a0f\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"853f72f0-6f8a-11eb-b906-974e9c601cee\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/816ad4de-0327-425f-b0a6-1ba3fc50c57a/24333\",\r\n"
				+ "                \"title\": \"test check\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4c2fe1a5-5aa4-4baf-ab39-67b111eb9a0f\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"779f9c60-75ed-11eb-bca9-195f117b03b3\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/e006a20f-5323-4761-b696-5849e9314c40/24333\",\r\n"
				+ "                \"title\": \"Custom Form - Gender Consent\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"944adda0-75ef-11eb-bca9-195f117b03b3\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/fa7af328-9864-48a2-8189-68f6333ec24c/24333\",\r\n"
				+ "                \"title\": \"Custom Form - Gender Consent - new\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"f3c9cd00-75f8-11eb-95a4-53adf23bc545\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/dd3f18c6-88dd-4569-8425-42e60dc9381d/24333\",\r\n"
				+ "                \"title\": \"Custom Form - Gender Consent - multiple signature\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"eac2e090-76aa-11eb-8bbe-3f8559a073f2\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/168eb536-0d24-48a2-90f9-81bade250527/24333\",\r\n"
				+ "                \"title\": \"Copy of Custom Form - gender specific 24 Feb-Mobile\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"02ea8060-76ab-11eb-8bbe-3f8559a073f2\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/4d720873-3cd4-4d1b-b3d7-07c36fed2b15/24333\",\r\n"
				+ "                \"title\": \"Custom Form - gender specific 24 Feb\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"83127d00-772e-11eb-97b4-018e702129d3\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/a3e7e60d-5861-47da-8acf-d61383f0db4f/24333\",\r\n"
				+ "                \"title\": \"Custom Form - gender specific 25 Feb-Mobile\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"b3a394b0-773b-11eb-bb4a-d1c60bdba8be\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/6b043384-19b6-48ee-9398-f08f4e3b51bf/24333\",\r\n"
				+ "                \"title\": \"prakash precheck  3\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"38a95030-773e-11eb-bb4a-d1c60bdba8be\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/8f7c4f95-b6d8-467b-8528-d42ed5f8f631/24333\",\r\n"
				+ "                \"title\": \"prakash precheck 4\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"9b2a18e0-9b6d-11eb-ae76-312205e3ee33\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/b391eae4-3163-4628-9263-7269f8bd00f5/24333\",\r\n"
				+ "                \"title\": \"Khushboo form\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"39c9d6c0-c36e-11eb-bc6b-ad587c6fce85\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/ad8fa0be-3578-4656-9908-2d7beb6b3d1d/24333\",\r\n"
				+ "                \"title\": \"General Registration and Health History-Test\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "                ]\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"id\": \"f4a56010-c501-11eb-8cb3-75c6e97eb3c9\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/84e4ed94-1c3c-46e7-b032-779b56560217/24625\",\r\n"
				+ "                \"title\": \"Nishant test form1\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": []\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"messages\": {\r\n"
				+ "            \"secondaryInsuranceMessageEn\": \"Provide your secondary insurance card below.\",\r\n"
				+ "            \"secondaryInsuranceMessageEs\": \"Facilitar fotos de la tarjeta secundario o ingresar la información manualmente.\",\r\n"
				+ "            \"primaryInsuranceMessageEs\": \"Facilitar fotos de la tarjeta primario o ingresar la información manualmente.\",\r\n"
				+ "            \"tertiaryInsuranceMessageEs\": \"Facilitar fotos de la tarjeta terciario o ingresar la información manualmente.\",\r\n"
				+ "            \"primaryInsuranceMessageEn\": \"Provide your primary insurance card below.\",\r\n"
				+ "            \"tertiaryInsuranceMessageEn\": \"Provide your tertiary insurance card below.\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"pssSettings\": {\r\n"
				+ "        \"enabled\": true\r\n"
				+ "    },\r\n"
				+ "    \"ocrSettings\": null,\r\n"
				+ "    \"created\": null,\r\n"
				+ "    \"updated\": null\r\n"
				+ "}";
		return updateSettings;
	}

	public String getUpdateLocationSettingPayload(String practiceId, String displayName, String streetName,
			String city,String state) {
		String updateLocationSettings = "{\r\n"
				+ "    \"primaryLocation\": {\r\n"
				+ "        \"id\": \"" + practiceId + "\",\r\n"
				+ "        \"corporateName\": \"PSS-GE-DEV3APP\",\r\n"
				+ "        \"displayName\": \"" + displayName + "\",\r\n"
				+ "        \"streetNumber\": \"5501\",\r\n"
				+ "        \"streetName\": \"" + streetName + "\",\r\n"
				+ "        \"secondaryAddressDesignator\": null,\r\n"
				+ "        \"city\": \""+city+"\",\r\n"
				+ "        \"state\": \""+state+"\",\r\n"
				+ "        \"zipcode\": \"27518\",\r\n"
				+ "        \"phone\": 3313304741,\r\n"
				+ "        \"fax\": null,\r\n"
				+ "        \"email\": null,\r\n"
				+ "        \"latitude\": null,\r\n"
				+ "        \"longitude\": null,\r\n"
				+ "        \"timezone\": null\r\n"
				+ "    }\r\n"
				+ "}";
		return updateLocationSettings;
	}

	public String getUpdateLocationSettingPayloadWithoutPracticeId(String displayName, String streetName, String city,
			String state) {
		String updateLocationSettings = "{\r\n"
				+ "    \"primaryLocation\": {\r\n"
				+ "        \"corporateName\": \"PSS-GE-DEV3APP\",\r\n"
				+ "        \"displayName\": \"" + displayName + "\",\r\n"
				+ "        \"streetNumber\": \"5501\",\r\n"
				+ "        \"streetName\": \"" + streetName + "\",\r\n"
				+ "        \"secondaryAddressDesignator\": null,\r\n"
				+ "        \"city\": \""+city+"\",\r\n"
				+ "        \"state\": \""+state+"\",\r\n"
				+ "        \"zipcode\": \"27518\",\r\n"
				+ "        \"phone\": 3313304741,\r\n"
				+ "        \"fax\": null,\r\n"
				+ "        \"email\": null,\r\n"
				+ "        \"latitude\": null,\r\n"
				+ "        \"longitude\": null,\r\n"
				+ "        \"timezone\": null\r\n"
				+ "    }\r\n"
				+ "}";
		return updateLocationSettings;
	}

	public String getUpdateMerchantSettingPayload(String merchantId, String name) {
		String updateMerchantSettings = "{\r\n"
				+ "    \"id\": \""+merchantId+"\",\r\n"
				+ "    \"name\": \""+name+"\",\r\n"
				+ "    \"acceptedCreditCards\": [\r\n"
				+ "        \"American Express\",\r\n"
				+ "        \"Mastercard\",\r\n"
				+ "        \"Visa\"\r\n"
				+ "    ]\r\n"
				+ "}";
		return updateMerchantSettings;
	}

	public String getUpdateMerchantSettingPayloadWithInvalidCard(String merchantId, String name) {
		String updateMerchantSettings = "{\r\n"
				+ "    \"id\": \""+merchantId+"\",\r\n"
				+ "    \"name\": \""+name+"\",\r\n"
				+ "    \"acceptedCreditCards\": [\r\n"
				+ "        \"Axis\",\r\n"
				+ "        \"American Express\",\r\n"
				+ "        \"Mastercard\",\r\n"
				+ "        \"Visa\"\r\n"
				+ "    ]\r\n"
				+ "}";
		return updateMerchantSettings;
	}

	public String getUpdateMerchantSettingPayloadWithoutIdName() {
		String updateMerchantSettings = "{\r\n"
				+ "    \"acceptedCreditCards\": [\r\n"
				+ "        \"American Express\",\r\n"
				+ "        \"Mastercard\",\r\n"
				+ "        \"Visa\"\r\n"
				+ "    ]\r\n"
				+ "}";
		return updateMerchantSettings;
	}

	public String getUpdateNotifySettingPayload(String enabled, String enabledByPractice, String notifyOneDayOut,
			String notifyThreeDaysOut, String notifyFiveDaysOut, String notifyId, String deliveryMethod,
			String apptMethod, String status) {
		String updateNotifySettings = "{\r\n"
				+ "    \"enabled\": \""+enabled+"\",\r\n"
				+ "    \"enabledByPractice\": \""+enabledByPractice+"\",\r\n"
				+ "    \"notifyOneDayOut\": \""+notifyOneDayOut+"\",\r\n"
				+ "    \"notifyThreeDaysOut\": \""+notifyThreeDaysOut+"\",\r\n"
				+ "    \"notifyFiveDaysOut\": \""+notifyFiveDaysOut+"\",\r\n"
				+ "    \"reminderNotification\": [\r\n"
				+ "        {\r\n"
				+ "            \"cadence\": [\r\n"
				+ "                {\r\n"
				+ "                    \"timing\": \"Days\",\r\n"
				+ "                    \"periodValue\": 1\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"id\": \"" + notifyId + "\",\r\n"
				+ "            \"deliveryMethod\": \""+deliveryMethod+"\",\r\n"
				+ "            \"timingUnit\": [\r\n"
				+ "                {\r\n"
				+ "                    \"timing\": \"Days\",\r\n"
				+ "                    \"units\": [\r\n"
				+ "                        0\r\n"
				+ "                    ]\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"version\": \"v2\",\r\n"
				+ "            \"apptMethod\": \""+apptMethod+"\",\r\n"
				+ "            \"status\": \"" + status + "\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"confirmationNotification\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"de766f30-0878-4f4a-87c4-c6659e369aa6\",\r\n"
				+ "            \"timing\": \"Days\",\r\n"
				+ "            \"deliveryMethod\": \"Email\",\r\n"
				+ "            \"version\": \"v2\",\r\n"
				+ "            \"apptMethod\": \"In Office\",\r\n"
				+ "            \"status\": \"Published\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"includePatientFirstName\": true,\r\n"
				+ "    \"notifyLanguage\": \"en-es\",\r\n"
				+ "    \"emailEnabled\": true,\r\n"
				+ "    \"textEnabled\": true,\r\n"
				+ "    \"pushEnabled\": false,\r\n"
				+ "    \"notifyCurbsCheckIn\": true,\r\n"
				+ "    \"enableBroadcast\": true,\r\n"
				+ "    \"arrivalMessage\": {\r\n"
				+ "        \"en\": \"\",\r\n"
				+ "        \"es\": \"\"\r\n"
				+ "    }\r\n"
				+ "}";
		return updateNotifySettings;
	}

	public String getUpdatePmIntegrationSettingPayload(String systemId, String dataSyncEnabled) {
		String updatePmIntegrationSettings = " {\r\n"
				+ "  \"id\": \"" + systemId + "\",\r\n"
				+ "  \"dataSyncEnabled\": \"" + dataSyncEnabled + "\"\r\n"
				+ "}";
		return updatePmIntegrationSettings;
	}

	public String getUpdatePmIntegrationSettingPayloadWithoutDataSyncEnabled(String SystemId) {
		String updatePmIntegrationSettings = " {\r\n"
				+ "  \"id\": \"" + SystemId + "\"\r\n"
				+ "}";
		return updatePmIntegrationSettings;
	}

	public String getUpdatePrecheckSettingPayload(String enabled, String dataSyncEnabled, String insuranceSettings,
			String textEntryEnabled, String ocrEnabled, String disableCopay, String disableBalance,
			String enablePatientMode, String enableForms) {
		String updatePrecheckSetting = "{\r\n"
				+ "  \"enabled\": \""+enabled+"\",\r\n"
				+ "  \"disableDemographics\": \""+dataSyncEnabled+"\",\r\n"
				+ "  \"insuranceSettings\": {\r\n"
				+ "    \"enabled\": \"" + insuranceSettings + "\",\r\n"
				+ "    \"textEntryEnabled\": \""+textEntryEnabled+"\",\r\n"
				+ "    \"ocrEnabled\": \""+ocrEnabled+"\"\r\n"
				+ "  },\r\n"
				+ "  \"disableCopay\": \""+disableCopay+"\",\r\n"
				+ "  \"disableBalance\": \""+disableBalance+"\",\r\n"
				+ "  \"enablePatientMode\": \""+enablePatientMode+"\",\r\n"
				+ "  \"enableForms\": \""+enableForms+"\",\r\n"
				+ "  \"minBalanceAmount\": 0,\r\n"
				+ "  \"minBalancePercent\": 0,\r\n"
				+ "  \"minBalanceThreshold\": 0,\r\n"
				+ "  \"forms\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"df969390-5564-11eb-bd4e-2104e266e238\",\r\n"
				+ "      \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/2b217edb-909d-466e-bed2-b8bb50b5b922/24333\",\r\n"
				+ "      \"title\": \"Adult ADHD Self-Report Scale (ASRS-v1.1) Symptom Checklist\",\r\n"
				+ "      \"enabledByAppointmentType\": true,\r\n"
				+ "      \"appointmentTypes\": [\r\n"
				+ "        \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n"
				+ "      ]\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}";
		return updatePrecheckSetting;
	}

	public String getUpdatePssSettingPayload(boolean pssSetting) {
		String updatePssSetting = "{\r\n"
				+ "  \"enabled\": true,\r\n"
				+ "  \"url\": \"https://www.medfusion.com/\"\r\n"
				+ "}";
		return updatePssSetting;
	}

	public String getCreateSettingPayload(String Practiceid) {
		String createSetting = "{\r\n" 
	            + "    \"id\": \"" + Practiceid + "\",\r\n" 
	            + "    \"active\": true,\r\n"
				+ "    \"pmIntegrationSettings\": {\r\n" 
	            + "        \"id\": \"84\",\r\n"
				+ "        \"dataSyncEnabled\": false\r\n" 
	            + "    },\r\n" 
				+ "    \"locationSettings\": {\r\n"
				+ "        \"primaryLocation\": {\r\n" 
				+ "            \"id\": \"" + Practiceid + "\",\r\n"
				+ "            \"corporateName\": \"PSS-GE-DEV3APP\",\r\n"
				+ "            \"displayName\": \"PSS-GE-DEV3APP\",\r\n" 
				+ "            \"streetNumber\": \"5501\",\r\n"
				+ "            \"streetName\": \"Dillard Dr\",\r\n"
				+ "            \"secondaryAddressDesignator\": null,\r\n" 
				+ "            \"city\": \"Cary\",\r\n"
				+ "            \"state\": \"North Carolina\",\r\n" 
				+ "            \"zipcode\": \"27518\",\r\n"
				+ "            \"phone\": 9198822880,\r\n" 
				+ "            \"fax\": null,\r\n"
				+ "            \"email\": null,\r\n" 
				+ "            \"timezone\": null\r\n" 
				+ "        },\r\n"
				+ "        \"locations\": {\r\n" 
				+ "            \"abc456\": {\r\n"
				+ "                \"id\": \"abc456\",\r\n"
				+ "                \"corporateName\": \"Brigs at the Village Restaurant Inc.\",\r\n"
				+ "                \"displayName\": \"Brigs at the Village Restaurant\",\r\n"
				+ "                \"streetNumber\": \"1040\",\r\n"
				+ "                \"streetName\": \"Village Dr\",\r\n"
				+ "                \"secondaryAddressDesignator\": null,\r\n"
				+ "                \"city\": \"Cary\",\r\n" 
				+ "                \"state\": \"North Carolina\",\r\n"
				+ "                \"zipcode\": \"27518\",\r\n" 
				+ "                \"phone\": 9198592151\r\n"
				+ "            },\r\n" 
				+ "            \"abc777\": {\r\n" 
				+ "                \"id\": \"abc777\",\r\n"
				+ "                \"corporateName\": \"Brigs at the Village Restaurant Inc.\",\r\n"
				+ "                \"displayName\": \"Brigs at the Village Restaurant\",\r\n"
				+ "                \"streetNumber\": \"1040\",\r\n"
				+ "                \"streetName\": \"Village Dr\",\r\n"
				+ "                \"secondaryAddressDesignator\": null,\r\n"
				+ "                \"city\": \"Cary\",\r\n" 
				+ "                \"state\": \"North Carolina\",\r\n"
				+ "                \"zipcode\": \"27518\",\r\n" 
				+ "                \"phone\": 9198592151\r\n"
				+ "            }\r\n" 
				+ "        }\r\n" 
				+ "    },\r\n" 
				+ "    \"notifySettings\": {\r\n"
				+ "        \"enabled\": true,\r\n" 
				+ "        \"enabledByPractice\": true,\r\n"
				+ "        \"notifyOneDayOut\": true,\r\n" 
				+ "        \"notifyThreeDaysOut\": true,\r\n"
				+ "        \"notifyFiveDaysOut\": true,\r\n" 
				+ "        \"reminderNotification\": [\r\n"
				+ "            {\r\n" 
				+ "                \"id\": \"de766f30-0878-4f4a-87c4-c6659e369aa6\",\r\n"
				+ "                \"deliveryMethod\": \"Email\",\r\n" 
				+ "                \"version\": \"Default\",\r\n"
				+ "                \"apptMethod\": \"In Office\",\r\n"
				+ "                \"status\": \"Published\",\r\n" 
				+ "                \"cadence\": [\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 1\r\n" 
				+ "                    },\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 3\r\n" 
				+ "                    },\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Hours\",\r\n"
				+ "                        \"periodValue\": 2\r\n" 
				+ "                    },\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Minutes\",\r\n"
				+ "                        \"periodValue\": 30\r\n" 
				+ "                    }\r\n"
				+ "                ]\r\n" 
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"78a46f9e-5133-4c46-b965-2ad00af51fc0\",\r\n"
				+ "                \"deliveryMethod\": \"SMS\",\r\n" 
				+ "                \"version\": \"Default\",\r\n"
				+ "                \"apptMethod\": \"In Office\",\r\n"
				+ "                \"status\": \"Published\",\r\n" 
				+ "                \"cadence\": [\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 1\r\n" 
				+ "                    },\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Days\",\r\n"
				+ "                        \"periodValue\": 3\r\n" 
				+ "                    },\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Minutes\",\r\n"
				+ "                        \"periodValue\": 30\r\n" 
				+ "                    },\r\n"
				+ "                    {\r\n" 
				+ "                        \"timing\": \"Hours\",\r\n"
				+ "                        \"periodValue\": 2\r\n" 
				+ "                    }\r\n"
				+ "                ]\r\n" 
				+ "            }\r\n" 
				+ "        ],\r\n"
				+ "        \"confirmationNotification\": null,\r\n" 
				+ "        \"includePatientFirstName\": true,\r\n"
				+ "        \"notifyLanguage\": \"en-es\",\r\n" 
				+ "        \"emailEnabled\": true,\r\n"
				+ "        \"textEnabled\": true,\r\n" 
				+ "        \"pushEnabled\": false,\r\n"
				+ "        \"notifyCurbsCheckIn\": true,\r\n" 
				+ "        \"enableBroadcast\": true,\r\n"
				+ "        \"arrivalMessage\": {\r\n" 
				+ "            \"en\": \"\",\r\n" 
				+ "            \"es\": \"\"\r\n"
				+ "        },\r\n" 
				+ "        \"defaultArrivalMessage\": {}\r\n" 
				+ "    },\r\n"
				+ "    \"merchantSettings\": {\r\n" 
				+ "        \"id\": \"2560794497\",\r\n"
				+ "        \"name\": \"DEV3 Test Practice 7\",\r\n" 
				+ "        \"acceptedCreditCards\": [\r\n"
				+ "            \"American Express\",\r\n" 
				+ "            \"Mastercard\"\r\n" 
				+ "        ]\r\n"
				+ "    },\r\n" 
				+ "    \"precheckSettings\": {\r\n" 
				+ "        \"enabled\": true,\r\n"
				+ "        \"disableDemographics\": false,\r\n" 
				+ "        \"insuranceSettings\": {\r\n"
				+ "            \"enabled\": true,\r\n" 
				+ "            \"textEntryEnabled\": true,\r\n"
				+ "            \"ocrEnabled\": false\r\n" 
				+ "        },\r\n" 
				+ "        \"disableCopay\": false,\r\n"
				+ "        \"disableBalance\": false,\r\n" 
				+ "        \"enablePatientMode\": true,\r\n"
				+ "        \"enableForms\": true,\r\n" 
				+ "        \"minBalanceAmount\": null,\r\n"
				+ "        \"minBalancePercent\": null,\r\n" 
				+ "        \"minBalanceThreshold\": null,\r\n"
				+ "        \"forms\": [\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"df969390-5564-11eb-bd4e-2104e266e238\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/2b217edb-909d-466e-bed2-b8bb50b5b922/24333\",\r\n"
				+ "                \"title\": \"Adult ADHD Self-Report Scale (ASRS-v1.1) Symptom Checklist\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"51f22160-5566-11eb-bd4e-2104e266e238\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/e548230a-ab05-4433-8925-80c3e379aa82/24333\",\r\n"
				+ "                \"title\": \"General Registration and Health History PK\",\r\n"
				+ "                \"enabledByAppointmentType\": false\r\n" 
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"17877950-556e-11eb-93ea-918e24c9be00\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/f2e7d60c-b8e1-409e-a9a1-3c7e18096d4d/24333\",\r\n"
				+ "                \"title\": \"Prakash Custom Form\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"73684cc0-69e3-11eb-942b-95b607c89218\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/4fff1ec9-d393-4065-873b-eecf5e9503f0/24333\",\r\n"
				+ "                \"title\": \"smoke custom form\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4c2fe1a5-5aa4-4baf-ab39-67b111eb9a0f\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"853f72f0-6f8a-11eb-b906-974e9c601cee\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/816ad4de-0327-425f-b0a6-1ba3fc50c57a/24333\",\r\n"
				+ "                \"title\": \"test check\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4c2fe1a5-5aa4-4baf-ab39-67b111eb9a0f\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"779f9c60-75ed-11eb-bca9-195f117b03b3\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/e006a20f-5323-4761-b696-5849e9314c40/24333\",\r\n"
				+ "                \"title\": \"Custom Form - Gender Consent\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"944adda0-75ef-11eb-bca9-195f117b03b3\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/fa7af328-9864-48a2-8189-68f6333ec24c/24333\",\r\n"
				+ "                \"title\": \"Custom Form - Gender Consent - new\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"f3c9cd00-75f8-11eb-95a4-53adf23bc545\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/dd3f18c6-88dd-4569-8425-42e60dc9381d/24333\",\r\n"
				+ "                \"title\": \"Custom Form - Gender Consent - multiple signature\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"eac2e090-76aa-11eb-8bbe-3f8559a073f2\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/168eb536-0d24-48a2-90f9-81bade250527/24333\",\r\n"
				+ "                \"title\": \"Copy of Custom Form - gender specific 24 Feb-Mobile\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"02ea8060-76ab-11eb-8bbe-3f8559a073f2\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/4d720873-3cd4-4d1b-b3d7-07c36fed2b15/24333\",\r\n"
				+ "                \"title\": \"Custom Form - gender specific 24 Feb\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"83127d00-772e-11eb-97b4-018e702129d3\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/a3e7e60d-5861-47da-8acf-d61383f0db4f/24333\",\r\n"
				+ "                \"title\": \"Custom Form - gender specific 25 Feb-Mobile\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"b3a394b0-773b-11eb-bb4a-d1c60bdba8be\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/6b043384-19b6-48ee-9398-f08f4e3b51bf/24333\",\r\n"
				+ "                \"title\": \"prakash precheck  3\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"38a95030-773e-11eb-bb4a-d1c60bdba8be\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/8f7c4f95-b6d8-467b-8528-d42ed5f8f631/24333\",\r\n"
				+ "                \"title\": \"prakash precheck 4\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"9b2a18e0-9b6d-11eb-ae76-312205e3ee33\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/b391eae4-3163-4628-9263-7269f8bd00f5/24333\",\r\n"
				+ "                \"title\": \"Khushboo form\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"39c9d6c0-c36e-11eb-bc6b-ad587c6fce85\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/ad8fa0be-3578-4656-9908-2d7beb6b3d1d/24333\",\r\n"
				+ "                \"title\": \"General Registration and Health History-Test\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": [\r\n"
				+ "                    \"4f9cfd65-462d-4b02-8dab-b436772d56f8\"\r\n" 
				+ "                ]\r\n"
				+ "            },\r\n" 
				+ "            {\r\n"
				+ "                \"id\": \"f4a56010-c501-11eb-8cb3-75c6e97eb3c9\",\r\n"
				+ "                \"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/84e4ed94-1c3c-46e7-b032-779b56560217/24625\",\r\n"
				+ "                \"title\": \"Nishant test form1\",\r\n"
				+ "                \"enabledByAppointmentType\": true,\r\n"
				+ "                \"appointmentTypes\": []\r\n" 
				+ "            }\r\n" 
				+ "        ],\r\n"
				+ "        \"messages\": {\r\n" 
				+ "            \"secondaryInsuranceMessageEn\": null,\r\n"
				+ "            \"secondaryInsuranceMessageEs\": null,\r\n"
				+ "            \"primaryInsuranceMessageEs\": null,\r\n"
				+ "            \"tertiaryInsuranceMessageEs\": null,\r\n"
				+ "            \"primaryInsuranceMessageEn\": null,\r\n"
				+ "            \"tertiaryInsuranceMessageEn\": null\r\n" 
				+ "        }\r\n" 
				+ "    },\r\n"
				+ "    \"pssSettings\": {\r\n" 
				+ "        \"enabled\": true,\r\n"
				+ "        \"url\": \"https://www.medfusion.com/\"\r\n" 
				+ "    },\r\n"
				+ "    \"ocrSettings\": null,\r\n" 
				+ "    \"enabled\": true\r\n" 
				+ "}";
		return createSetting;
	}
	public String getGuestTokenPayload(String patientDob,String zipcode) {
		String guestToken = "{\r\n"
				+ "  \"dob\": \""+patientDob+"\",\r\n"
				+ "  \"zip\": \""+zipcode+"\"\r\n"
				+ "}";
		return guestToken;
	}
	public String getUpdateSettingsPayloadDemo(String practiceId, String systemId, String locationId, String deliveryMtd,
			String language) {
		String updateSettings = "{\r\n"
				+ "  \"id\": \"" + practiceId + "\",\r\n"
				+ "  \"active\": true,\r\n"
				+ "  \"pmIntegrationSettings\": {\r\n"
				+ "    \"id\": \"" + systemId + "\",\r\n"
				+ "    \"dataSyncEnabled\": false\r\n"
				+ "  },\r\n"
				+ "  \"locationSettings\": {\r\n"
				+ "    \"primaryLocation\": {\r\n"
				+ "      \"id\": \"" + practiceId + "\",\r\n"
				+ "      \"corporateName\": \"PSS-GE-DEMO1\",\r\n"
				+ "      \"displayName\": \"PSS-GE-DEMO1\",\r\n"
				+ "      \"streetNumber\": \"5501\",\r\n"
				+ "      \"streetName\": \"Dillard Dr\",\r\n"
				+ "      \"secondaryAddressDesignator\": null,\r\n"
				+ "      \"city\": \"Cary\",\r\n"
				+ "      \"state\": \"North Carolina\",\r\n"
				+ "      \"zipcode\": \"27518\",\r\n"
				+ "      \"phone\": 9198822880,\r\n"
				+ "      \"fax\": null,\r\n"
				+ "      \"email\": null,\r\n"
				+ "      \"latitude\": null,\r\n"
				+ "      \"longitude\": null,\r\n"
				+ "      \"timezone\": null\r\n"
				+ "    },\r\n"
				+ "    \"locations\": {\r\n"
				+ "      \"abc456\": {\r\n"
				+ "        \"id\": \"" + locationId + "\",\r\n"
				+ "        \"corporateName\": \"Brigs at the Village Restaurant Inc.\",\r\n"
				+ "        \"displayName\": \"Brigs at the Village Restaurant\",\r\n"
				+ "        \"streetNumber\": \"1040\",\r\n"
				+ "        \"streetName\": \"Village Dr\",\r\n"
				+ "        \"secondaryAddressDesignator\": null,\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"North Carolina\",\r\n"
				+ "        \"zipcode\": \"27518\",\r\n"
				+ "        \"phone\": 9198592151,\r\n"
				+ "        \"fax\": null,\r\n"
				+ "        \"email\": null,\r\n"
				+ "        \"latitude\": null,\r\n"
				+ "        \"longitude\": null,\r\n"
				+ "        \"timezone\": null\r\n"
				+ "      },\r\n"
				+ "      \"abc777\": {\r\n"
				+ "        \"id\": \"abc777\",\r\n"
				+ "        \"corporateName\": \"Brigs at the Village Restaurant Inc.\",\r\n"
				+ "        \"displayName\": \"Brigs at the Village Restaurant\",\r\n"
				+ "        \"streetNumber\": \"1040\",\r\n"
				+ "        \"streetName\": \"Village Dr\",\r\n"
				+ "        \"secondaryAddressDesignator\": null,\r\n"
				+ "        \"city\": \"Cary\",\r\n"
				+ "        \"state\": \"North Carolina\",\r\n"
				+ "        \"zipcode\": \"27518\",\r\n"
				+ "        \"phone\": 9198592151,\r\n"
				+ "        \"fax\": null,\r\n"
				+ "        \"email\": null,\r\n"
				+ "        \"latitude\": null,\r\n"
				+ "        \"longitude\": null,\r\n"
				+ "        \"timezone\": null\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  },\r\n"
				+ "  \"notifySettings\": {\r\n"
				+ "    \"enabled\": true,\r\n"
				+ "    \"enabledByPractice\": true,\r\n"
				+ "    \"notifyOneDayOut\": true,\r\n"
				+ "    \"notifyThreeDaysOut\": true,\r\n"
				+ "    \"notifyFiveDaysOut\": true,\r\n"
				+ "    \"reminderNotification\": [\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"1b48db6f-0f06-42b4-b848-4bad0a819417\",\r\n"
				+ "        \"deliveryMethod\": \"" + deliveryMtd + "\",\r\n"
				+ "        \"version\": \"Default\",\r\n"
				+ "        \"apptMethod\": \"In Office\",\r\n"
				+ "        \"status\": \"Published\",\r\n"
				+ "        \"cadence\": [\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Hours\",\r\n"
				+ "            \"periodValue\": 10\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Hours\",\r\n"
				+ "            \"periodValue\": 20\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Days\",\r\n"
				+ "            \"periodValue\": 1\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Minutes\",\r\n"
				+ "            \"periodValue\": 30\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"timingUnit\": [\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Days\",\r\n"
				+ "            \"units\": [\r\n"
				+ "              1\r\n"
				+ "            ]\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Hours\",\r\n"
				+ "            \"units\": [\r\n"
				+ "              10,\r\n"
				+ "              20\r\n"
				+ "            ]\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Minutes\",\r\n"
				+ "            \"units\": [\r\n"
				+ "              30\r\n"
				+ "            ]\r\n"
				+ "          }\r\n"
				+ "        ]\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"id\": \"8faff8cc-aa94-413e-9236-f035d49877b2\",\r\n"
				+ "        \"deliveryMethod\": \"SMS\",\r\n"
				+ "        \"version\": \"Default\",\r\n"
				+ "        \"apptMethod\": \"In Office\",\r\n"
				+ "        \"status\": \"Published\",\r\n"
				+ "        \"cadence\": [\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Days\",\r\n"
				+ "            \"periodValue\": 1\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Hours\",\r\n"
				+ "            \"periodValue\": 20\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Hours\",\r\n"
				+ "            \"periodValue\": 10\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Minutes\",\r\n"
				+ "            \"periodValue\": 30\r\n"
				+ "          }\r\n"
				+ "        ],\r\n"
				+ "        \"timingUnit\": [\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Days\",\r\n"
				+ "            \"units\": [\r\n"
				+ "              1\r\n"
				+ "            ]\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Hours\",\r\n"
				+ "            \"units\": [\r\n"
				+ "              20,\r\n"
				+ "              10\r\n"
				+ "            ]\r\n"
				+ "          },\r\n"
				+ "          {\r\n"
				+ "            \"timing\": \"Minutes\",\r\n"
				+ "            \"units\": [\r\n"
				+ "              30\r\n"
				+ "            ]\r\n"
				+ "          }\r\n"
				+ "        ]\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"confirmationNotification\": [\r\n"
				+ "      {\r\n"
				+ "        \"deliveryMethod\": \"Email\",\r\n"
				+ "        \"version\": \"Default\",\r\n"
				+ "        \"apptMethod\": \"In Office\",\r\n"
				+ "        \"status\": \"Published\",\r\n"
				+ "        \"timing\": \"Upon Scheduling\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"deliveryMethod\": \"SMS\",\r\n"
				+ "        \"version\": \"Default\",\r\n"
				+ "        \"apptMethod\": \"In Office\",\r\n"
				+ "        \"status\": \"Published\",\r\n"
				+ "        \"timing\": \"Upon Scheduling\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"includePatientFirstName\": true,\r\n"
				+ "    \"notifyLanguage\": \"" + language + "\",\r\n"
				+ "    \"emailEnabled\": true,\r\n"
				+ "    \"textEnabled\": true,\r\n"
				+ "    \"pushEnabled\": false,\r\n"
				+ "    \"notifyCurbsCheckIn\": true,\r\n"
				+ "    \"enableBroadcast\": true,\r\n"
				+ "    \"arrivalMessage\": {},\r\n"
				+ "    \"defaultArrivalMessage\": {\r\n"
				+ "      \"en\": \"The practice front office staff has been notified that you have arrived. Wait in the parking lot until you receive a message to come in. Call the office at [appointment phone number] if you have been waiting more than 15 minutes.\",\r\n"
				+ "      \"es\": \"Se ha notificado al personal de recepci�n de la pr�ctica que ha llegado. Espere en el estacionamiento hasta que reciba un mensaje para entrar. Llame a la oficina al [n�mero de tel�fono de la cita] si ha estado esperando m�s de 15 minutos.\"\r\n"
				+ "    }\r\n"
				+ "  },\r\n"
				+ "  \"merchantSettings\": {\r\n"
				+ "    \"id\": \"2560794517\",\r\n"
				+ "    \"name\": \"Test Merchant\",\r\n"
				+ "    \"acceptedCreditCards\": [\r\n"
				+ "      \"American Express\",\r\n"
				+ "      \"Mastercard\"\r\n"
				+ "    ]\r\n"
				+ "  },\r\n"
				+ "  \"precheckSettings\": {\r\n"
				+ "    \"enabled\": true,\r\n"
				+ "    \"disableDemographics\": false,\r\n"
				+ "    \"insuranceSettings\": {\r\n"
				+ "      \"enabled\": true,\r\n"
				+ "      \"textEntryEnabled\": true,\r\n"
				+ "      \"ocrEnabled\": false\r\n"
				+ "    },\r\n"
				+ "    \"disableCopay\": false,\r\n"
				+ "    \"disableBalance\": false,\r\n"
				+ "    \"enablePatientMode\": true,\r\n"
				+ "    \"enableForms\": true,\r\n"
				+ "    \"minBalanceAmount\": 0,\r\n"
				+ "    \"minBalancePercent\": 0,\r\n"
				+ "    \"minBalanceThreshold\": 0,\r\n"
				+ "    \"forms\": [],\r\n"
				+ "    \"messages\": {\r\n"
				+ "      \"secondaryInsuranceMessageEn\": \"Provide your secondary insurance card below.\",\r\n"
				+ "      \"secondaryInsuranceMessageEs\": \"Facilitar fotos de la tarjeta secundario o ingresar la información manualmente.\",\r\n"
				+ "      \"primaryInsuranceMessageEs\": \"Facilitar fotos de la tarjeta primario o ingresar la información manualmente.\",\r\n"
				+ "      \"patientModeCompletionMessage\": \"You may enter a custom message for patients to see after checking in at your office. For example, \\\"Thank you for completing the precheck process. Please hand the tablet back to the front desk.\\\"\",\r\n"
				+ "      \"tertiaryInsuranceMessageEs\": \"Facilitar fotos de la tarjeta terciario o ingresar la información manualmente.\",\r\n"
				+ "      \"primaryInsuranceMessageEn\": \"Provide your primary insurance card below.\",\r\n"
				+ "      \"tertiaryInsuranceMessageEn\": \"Provide your tertiary insurance card below.\"\r\n"
				+ "    }\r\n"
				+ "  },\r\n"
				+ "  \"pssSettings\": {\r\n"
				+ "    \"enabled\": true,\r\n"
				+ "    \"url\": \"https://www.medfusion.com/\"\r\n"
				+ "  },\r\n"
				+ "  \"ocrSettings\": null,\r\n"
				+ "  \"created\": null,\r\n"
				+ "  \"updated\": null\r\n"
				+ "}";
		return updateSettings;
	}
	
	public String getSaveImhFormPayload(String conceptId, String conceptName, String formId, String practiceId) {
		String saveImhForm = "{\r\n"
				+ "  \"conceptId\": \""+conceptId+"\",\r\n"
				+ "  \"conceptName\": \""+conceptName+"\",\r\n"
				+ "  \"formId\": \""+formId+"\",\r\n"
				+ "  \"formSource\": \"IMH\",\r\n"
				+ "  \"id\": null,\r\n"
				+ "  \"practiceId\": \""+practiceId+"\"\r\n"
				+ "}";
		return saveImhForm;
	}
	
	public String getUpdateFormPayload(boolean apptType,String title) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ "	\"appointmentTypes\":[ null\r\n"
				+ "	],\r\n"
				+ "	\"enabledByAppointmentType\": \""+apptType+"\",\r\n"
				+ "	\"formSource\": null,\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ "	\"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/51353c10-09f3-43d0-a537-303b439c3909/24249\"\r\n"
				+ "	}\r\n"
				+ "	]";
		return saveImhForm;
	}
	
	public String getUpdateAppointmentTypesPayload(boolean apptType, String firstApptType,String secApptType,String thirdApptType, String  forthApptType,String title) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ " \"appointmentTypes\": [\r\n"
				+ " \""+firstApptType+"\",\r\n"
				+ " \""+secApptType+"\",\r\n"
				+ " \""+thirdApptType+"\",\r\n"
				+ " \""+forthApptType+"\"\r\n"
				+ " ],\r\n"
				+ "	\"enabledByAppointmentType\": "+apptType+",\r\n"
				+ " \"formSource\": \"Medfusion\",\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ " \"url\": \"www.medfusion.com\"\r\n"
				+ "  }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getUpdateAppointmentTypesPayload(boolean apptType, String firstApptType,String secApptType,String title,String formSource) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ " \"appointmentTypes\": [\r\n"
				+ " \""+firstApptType+"\",\r\n"
				+ " \""+secApptType+"\"\r\n"
				+ " ],\r\n"
				+ "	\"enabledByAppointmentType\": "+apptType+",\r\n"
				+ " \"formSource\": \""+formSource+"\",\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ " \"url\": \"www.medfusion.com\"\r\n"
				+ "  }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getUpdateNoAppointmentTypesAssociatedPayload(boolean apptType, String title) {
		String saveImhForm = "[\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "    \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \"Medfusion\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \""+title+"\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "    }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getUpdateApptTypesFotImhFormPayload(boolean apptType, String firstApptType,String secApptType,String thirdApptType, String  forthApptType,String title) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ " \"appointmentTypes\": [\r\n"
				+ " \""+firstApptType+"\",\r\n"
				+ " \""+secApptType+"\",\r\n"
				+ " \""+thirdApptType+"\",\r\n"
				+ " \""+forthApptType+"\"\r\n"
				+ " ],\r\n"
				+ "	\"enabledByAppointmentType\": "+apptType+",\r\n"
				+ " \"formSource\": \"Medfusion\",\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ " \"url\": \"www.medfusion.com\"\r\n"
				+ "  }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getActiveOrInactiveApptTypePayload(boolean apptTypeStatus, String apptType,String title) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ " \"appointmentTypes\": [\r\n"
				+ " \""+apptType+"\"\r\n"
				+ " ],\r\n"
				+ "	\"enabledByAppointmentType\": "+apptTypeStatus+",\r\n"
				+ " \"formSource\": \"Medfusion\",\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ " \"url\": \"www.medfusion.com\"\r\n"
				+ "  }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getAllAssociatedApptTypePayload(boolean apptType, String title,String formSource) {
		String saveImhForm = "[\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "          \"fea628e7-0ccc-4f45-b8e0-e6ad1cb0c28c\",\r\n"
				+ "          \"29826a00-553e-44df-b307-8482afe34925\",\r\n"
				+ "          \"95e643b5-3e6c-48b6-a835-14c54f97e49e\",\r\n"
				+ "          \"050d37bd-7e1b-4fae-9a75-ba8ce7d359c9\",\r\n"
				+ "          \"4ddedf8e-8478-4d16-8a49-e938097fe5d1\",\r\n"
				+ "          \"10b898b4-fba6-4eca-b9da-114ca45a5d0a\",\r\n"
				+ "          \"96c09af6-52ed-4043-ad5c-d4ed7c88a5fd\",\r\n"
				+ "          \"522f384d-7d55-41c3-b1fb-06995c40201d\",\r\n"
				+ "          \"97d9d554-603d-4ab4-a9b9-6ca27988f5d2\",\r\n"
				+ "          \"510c67f5-8e21-463b-a230-40035bea12da\"\r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+formSource+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \""+title+"\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "    }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getAddImhAndMedfusionFormPayload(boolean apptType,String imhFormSrc,String medfusionFormSrc) {
		String saveImhForm = " [\r\n"
				+ "      {\r\n"
				+ "        \"appointmentTypes\": [ ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+imhFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \"NECk Pain\",\r\n"
				+ "        \"url\": \"www.imh.com\"\r\n"
				+ "      },\r\n"
				+ " {\r\n"
				+ "        \"appointmentTypes\": [ ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+medfusionFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \"Custom Form\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "      }\r\n"
				+ "    ]";
		return saveImhForm;
	}
	
	public String getAddDuplicateFormPayload(boolean apptType,String imhFormSrc,String medfusionFormSrc) {
		String saveImhForm = "[\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+imhFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \"NECk Pain\",\r\n"
				+ "        \"url\": \"www.imh.com\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+medfusionFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \"Custom Form\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+imhFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \"NECk Pain\",\r\n"
				+ "        \"url\": \"www.imh.com\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+medfusionFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \"Custom Form\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "    }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String getAddMultipleImhAndMedfusionFormPayload(boolean apptType,String imhFormSrc, String title1,String title2,
			String medfusionFormSrc,String title3,String title4) {
		String saveImhForm = "[\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+imhFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \""+title1+"\",\r\n"
				+ "        \"url\": \"www.imh.com\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+medfusionFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \""+title2+"\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+imhFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \""+title3+"\",\r\n"
				+ "        \"url\": \"www.imh.com\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"appointmentTypes\": [\r\n"
				+ "            \r\n"
				+ "        ],\r\n"
				+ "        \"enabledByAppointmentType\": "+apptType+",\r\n"
				+ "        \"formSource\": \""+medfusionFormSrc+"\",\r\n"
				+ "        \"id\": null,\r\n"
				+ "        \"title\": \""+title4+"\",\r\n"
				+ "        \"url\": \"www.medfusion.com\"\r\n"
				+ "    }\r\n"
				+ "]";
		return saveImhForm;
	}
	
	public String addFormPayload(boolean apptType,String formSource,String title) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ "	\"appointmentTypes\":[ null\r\n"
				+ "	],\r\n"
				+ "	\"enabledByAppointmentType\": \""+apptType+"\",\r\n"
				+ "	\"formSource\": \""+formSource+"\",\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ "	\"url\": \"https://dev3.dev.medfusion.net/consumer/index.php/externalForms/start/51353c10-09f3-43d0-a537-303b439c3909/24249\"\r\n"
				+ "	}\r\n"
				+ "	]";
		return saveImhForm;
	}
	
	public String getUpdateFormPayload(boolean apptTypeValue,String title,String apptType) {
		String saveImhForm = "[\r\n"
				+ "  {\r\n"
				+ "	\"appointmentTypes\":[ \r\n"+"\""+apptType+"\"\r\n"
				+ "	],\r\n"
				+ "	\"enabledByAppointmentType\": \""+apptTypeValue+"\",\r\n"
				+ "  \"formSource\": \"IMH\",\r\n"
				+ "	\"id\": null,\r\n"
				+ "	\"title\": \""+title+"\",\r\n"
				+ "	\"url\": null\r\n"
				+ "	}\r\n"
				+ "	]";
		return saveImhForm;
	}

				
}
