// Copyright 2020 NXGN Management, LLC. All Rights Reserved.
package com.medfusion.product.appt.precheck.payload;

public class MfReminderServicePayload {
	private static MfReminderServicePayload payload = new MfReminderServicePayload();
	private MfReminderServicePayload() {
		
	}
	public static MfReminderServicePayload getMfReminderServicePayload() {
		return payload;
	}
	
	public String getMfReminderServicePayload(String appointmentId, String patientId, String practiceId,
			String practiceName, String systemId, String timezoneId, String timezoneLongName, String cadence,
			String notificationType,
			boolean generateEmail, boolean generateText, String email, String language) {
		String mfReminderService = "{\r\n"
				+ "  \"appointmentIdsAndType\": {\r\n"
				+ "    \"pmAppointmentId\": \""+appointmentId+"\",\r\n"
				+ "    \"pmPatientId\": \""+patientId+"\",\r\n"
				+ "    \"practiceId\": \""+practiceId+"\",\r\n"
				+ "    \"practiceName\": \""+practiceName+"\",\r\n"
				+ "    \"systemId\": \""+systemId+"\",\r\n"
				+ "    \"type\": \"Fever n Cold\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentLocation\": {\r\n"
				+ "    \"addressLine\": \"737 ,N Michigan Ave\",\r\n"
				+ "    \"city\": \"Chicago\",\r\n"
				+ "    \"corporateName\": \"RIVER OAK MAIN ENGLISH\",\r\n"
				+ "    \"displayName\": \"RIVER OAK MAIN ENGLISH\",\r\n"
				+ "    \"email\": null,\r\n"
				+ "    \"formattedPhoneNumber\": \"(914)598-8363\",\r\n"
				+ "    \"id\": \"3\",\r\n"
				+ "    \"phone\": 9145988363,\r\n"
				+ "    \"state\": \"Illinois\",\r\n"
				+ "    \"streetName\": null,\r\n"
				+ "    \"streetNumber\": null,\r\n"
				+ "    \"timezone\": \"America/New_York\",\r\n"
				+ "    \"zipcode\": \"60611\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentMetadata\": {\r\n"
				+ "    \"confirmed\": true,\r\n"
				+ "    \"rescheduleUrl\": \"https://dev3-pss.dev.medfusion.net/psspatient/view-appointment/517c593e-ee74-4daf-a6d9-48c3d72d7f85\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentTimeFormats\": {\r\n"
				+ "    \"day\": \"8\",\r\n"
				+ "    \"longDayOfWeek\": \"WEDNESDAY\",\r\n"
				+ "    \"longMonth\": \"July\",\r\n"
				+ "    \"meridiem\": \"AM\",\r\n"
				+ "    \"month\": \"07\",\r\n"
				+ "    \"shortDayOfWeek\": \"WED\",\r\n"
				+ "    \"shortMonth\": \"07\",\r\n"
				+ "    \"time\": \"11:10\",\r\n"
				+ "    \"timezoneId\": \""+timezoneId+"\",\r\n"
				+ "    \"timezoneLongName\": \""+timezoneLongName+"\",\r\n"
				+ "    \"timezoneShortName\": \"Eastern Daylight Time\",\r\n"
				+ "    \"year\": \"2021\"\r\n"
				+ "  },\r\n"
				+ "  \"cadence\": \"" + cadence + "\",\r\n"
				+ "  \"emailNotificationType\": \""+notificationType+"\",\r\n"
				+ "  \"generateEmail\":" + generateEmail + ",\r\n"
				+ "  \"generateText\": " + generateText + ",\r\n"
				+ "  \"includePatientFirstName\": true,\r\n"
				+ "  \"patientDemographics\": {\r\n"
				+ "    \"dob\": \"1999-11-11\",\r\n"
				+ "    \"email\": \""+email+"\",\r\n"
				+ "    \"firstName\": \"Raj\",\r\n"
				+ "    \"language\": \""+language+"\",\r\n"
				+ "    \"lastName\": \"Kumar\",\r\n"
				+ "    \"middleName\": null,\r\n"
				+ "    \"phone\": 3313304741,\r\n"
				+ "    \"zipCode\": \"12345\"\r\n"
				+ "  },\r\n"
				+ "  \"providerMetadata\": {\r\n"
				+ "    \"providerId\": null,\r\n"
				+ "    \"providerName\": \"Brown, Jennifer J.\"\r\n"
				+ "  },\r\n"
				+ "  \"textNotificationType\": \"Appointment Check-In\",\r\n"
				+ "  \"time\": 11.10\r\n"
				+ "}";
		return mfReminderService;
	}

	public String getInvalidApptIdsPayload(String appointmentId, String patientId, String practiceId,
			String practiceName, String systemId, String timezoneId, String timezoneLongName, String cadence,
			String notificationType,
			boolean generateEmail, boolean generateText, String email, String language) {
		String mfReminderService = "{\r\n"
				+ "  \"appointmentIdsAndType\": {\r\n"
				+ "    \"pmAppointmentId\": "+appointmentId+",\r\n"
				+ "    \"pmPatientId\": "+patientId+",\r\n"
				+ "    \"practiceId\": "+practiceId+",\r\n"
				+ "    \"practiceName\": \""+practiceName+"\",\r\n"
				+ "    \"systemId\": \""+systemId+"\",\r\n"
				+ "    \"type\": \"Fever n Cold\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentLocation\": {\r\n"
				+ "    \"addressLine\": \"737 ,N Michigan Ave\",\r\n"
				+ "    \"city\": \"Chicago\",\r\n"
				+ "    \"corporateName\": \"RIVER OAK MAIN ENGLISH\",\r\n"
				+ "    \"displayName\": \"RIVER OAK MAIN ENGLISH\",\r\n"
				+ "    \"email\": null,\r\n"
				+ "    \"formattedPhoneNumber\": \"(914)598-8363\",\r\n"
				+ "    \"id\": \"3\",\r\n"
				+ "    \"phone\": 9145988363,\r\n"
				+ "    \"state\": \"Illinois\",\r\n"
				+ "    \"streetName\": null,\r\n"
				+ "    \"streetNumber\": null,\r\n"
				+ "    \"timezone\": \"America/New_York\",\r\n"
				+ "    \"zipcode\": \"60611\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentMetadata\": {\r\n"
				+ "    \"confirmed\": true,\r\n"
				+ "    \"rescheduleUrl\": \"https://dev3-pss.dev.medfusion.net/psspatient/view-appointment/517c593e-ee74-4daf-a6d9-48c3d72d7f85\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentTimeFormats\": {\r\n"
				+ "    \"day\": \"8\",\r\n"
				+ "    \"longDayOfWeek\": \"WEDNESDAY\",\r\n"
				+ "    \"longMonth\": \"July\",\r\n"
				+ "    \"meridiem\": \"AM\",\r\n"
				+ "    \"month\": \"07\",\r\n"
				+ "    \"shortDayOfWeek\": \"WED\",\r\n"
				+ "    \"shortMonth\": \"07\",\r\n"
				+ "    \"time\": \"11:10\",\r\n"
				+ "    \"timezoneId\": \""+timezoneId+"\",\r\n"
				+ "    \"timezoneLongName\": \""+timezoneLongName+"\",\r\n"
				+ "    \"timezoneShortName\": \"Eastern Daylight Time\",\r\n"
				+ "    \"year\": \"2021\"\r\n"
				+ "  },\r\n"
				+ "  \"cadence\": \"" + cadence + "\",\r\n"
				+ "  \"emailNotificationType\": \""+notificationType+"\",\r\n"
				+ "  \"generateEmail\":" + generateEmail + ",\r\n"
				+ "  \"generateText\": " + generateText + ",\r\n"
				+ "  \"includePatientFirstName\": true,\r\n"
				+ "  \"patientDemographics\": {\r\n"
				+ "    \"dob\": \"1999-11-11\",\r\n"
				+ "    \"email\": \""+email+"\",\r\n"
				+ "    \"firstName\": \"Raj\",\r\n"
				+ "    \"language\": \""+language+"\",\r\n"
				+ "    \"lastName\": \"Kumar\",\r\n"
				+ "    \"middleName\": null,\r\n"
				+ "    \"phone\": 3313304741,\r\n"
				+ "    \"zipCode\": \"12345\"\r\n"
				+ "  },\r\n"
				+ "  \"providerMetadata\": {\r\n"
				+ "    \"providerId\": null,\r\n"
				+ "    \"providerName\": \"Brown, Jennifer J.\"\r\n"
				+ "  },\r\n"
				+ "  \"textNotificationType\": \"Appointment Check-In\",\r\n"
				+ "  \"time\": 11.10\r\n"
				+ "}";
		return mfReminderService;
	}
	
	public String getMfReminderServicePayloadWithoutNotifType(String appointmentId, String patientId, String practiceId,
			String practiceName, String systemId, String timezoneId, String timezoneLongName, String cadence,
			boolean generateEmail, boolean generateText, String email, String language) {
		String mfReminderService = "{\r\n"
				+ "  \"appointmentIdsAndType\": {\r\n"
				+ "    \"pmAppointmentId\": \""+appointmentId+"\",\r\n"
				+ "    \"pmPatientId\": \""+patientId+"\",\r\n"
				+ "    \"practiceId\": \""+practiceId+"\",\r\n"
				+ "    \"practiceName\": \""+practiceName+"\",\r\n"
				+ "    \"systemId\": \""+systemId+"\",\r\n"
				+ "    \"type\": \"Fever n Cold\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentLocation\": {\r\n"
				+ "    \"addressLine\": \"737 ,N Michigan Ave\",\r\n"
				+ "    \"city\": \"Chicago\",\r\n"
				+ "    \"corporateName\": \"RIVER OAK MAIN ENGLISH\",\r\n"
				+ "    \"displayName\": \"RIVER OAK MAIN ENGLISH\",\r\n"
				+ "    \"email\": null,\r\n"
				+ "    \"formattedPhoneNumber\": \"(914)598-8363\",\r\n"
				+ "    \"id\": \"3\",\r\n"
				+ "    \"phone\": 9145988363,\r\n"
				+ "    \"state\": \"Illinois\",\r\n"
				+ "    \"streetName\": null,\r\n"
				+ "    \"streetNumber\": null,\r\n"
				+ "    \"timezone\": \"America/New_York\",\r\n"
				+ "    \"zipcode\": \"60611\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentMetadata\": {\r\n"
				+ "    \"confirmed\": true,\r\n"
				+ "    \"rescheduleUrl\": \"https://dev3-pss.dev.medfusion.net/psspatient/view-appointment/517c593e-ee74-4daf-a6d9-48c3d72d7f85\"\r\n"
				+ "  },\r\n"
				+ "  \"appointmentTimeFormats\": {\r\n"
				+ "    \"day\": \"8\",\r\n"
				+ "    \"longDayOfWeek\": \"WEDNESDAY\",\r\n"
				+ "    \"longMonth\": \"July\",\r\n"
				+ "    \"meridiem\": \"AM\",\r\n"
				+ "    \"month\": \"07\",\r\n"
				+ "    \"shortDayOfWeek\": \"WED\",\r\n"
				+ "    \"shortMonth\": \"07\",\r\n"
				+ "    \"time\": \"11:10\",\r\n"
				+ "    \"timezoneId\": \""+timezoneId+"\",\r\n"
				+ "    \"timezoneLongName\": \""+timezoneLongName+"\",\r\n"
				+ "    \"timezoneShortName\": \"Eastern Daylight Time\",\r\n"
				+ "    \"year\": \"2021\"\r\n"
				+ "  },\r\n"
				+ "  \"cadence\": \"" + cadence + "\",\r\n"
				+ "  \"generateEmail\":" + generateEmail + ",\r\n"
				+ "  \"generateText\": " + generateText + ",\r\n"
				+ "  \"includePatientFirstName\": true,\r\n"
				+ "  \"patientDemographics\": {\r\n"
				+ "    \"dob\": \"1999-11-11\",\r\n"
				+ "    \"email\": \""+email+"\",\r\n"
				+ "    \"firstName\": \"Raj\",\r\n"
				+ "    \"language\": \""+language+"\",\r\n"
				+ "    \"lastName\": \"Kumar\",\r\n"
				+ "    \"middleName\": null,\r\n"
				+ "    \"phone\": 3313304741,\r\n"
				+ "    \"zipCode\": \"12345\"\r\n"
				+ "  },\r\n"
				+ "  \"providerMetadata\": {\r\n"
				+ "    \"providerId\": null,\r\n"
				+ "    \"providerName\": \"Brown, Jennifer J.\"\r\n"
				+ "  },\r\n"
				+ "  \"textNotificationType\": \"Appointment Check-In\",\r\n"
				+ "  \"time\": 11.10\r\n"
				+ "}";
		return mfReminderService;
	}
}
